embulk-core/src/main/java/org/embulk/spi/Extension.java
This fix is necessary to make `./gradlew build` work with Java8.
=> Escape code example within javadoc

build.gradle
Since I found aws-java-sdk and other libs are old version, I've checked dependency updates by using [gradle-versions-plugin](https://github.com/ben-manes/gradle-versions-plugIn).
gradle-versions-plugin is a useful Gradle plugin which provides a task to determine which dependencies have updates.
This pull request also contains several dependency upgrades. `gradle test` and `bundle exec rake` have been successfully completed. 
If you don't prefer upgrading them right now, please let me know. I'll revert dependencies upgrade.
```
$ gradle dependencyUpdates
:copy depend to /Users/k-sera/tmp/embulk/embulk/embulk-cli/build/libs/dependencies
:copy depend to /Users/k-sera/tmp/embulk/embulk/embulk-core/build/libs/dependencies
:copy depend to …
```
=> Introduce Gradle Versions Plugin

embulk-core/src/main/java/org/embulk/spi/PluginClassLoader.java, lib/embulk/buffer.rb, lib/embulk/column.rb, lib/embulk/data_source.rb, lib/embulk/decoder_plugin.rb, lib/embulk/encoder_plugin.rb, lib/embulk/file_input_plugin.rb, lib/embulk/file_output_plugin.rb, lib/embulk/filter_plugin.rb, lib/embulk/formatter_plugin.rb, lib/embulk/guess_plugin.rb, lib/embulk/input_plugin.rb, lib/embulk/java/bootstrap.rb, lib/embulk/java/imports.rb, lib/embulk/java_plugin.rb, lib/embulk/output_plugin.rb, lib/embulk/page.rb, lib/embulk/page_builder.rb, lib/embulk/parser_plugin.rb, lib/embulk/plugin.rb, lib/embulk/schema.rb
Implemented Java plugin loader [#28].
Here is the first example plugin using this plugin loader: https://github.com/embulk/embulk-plugin-s3
How it works: (example case: loading S3FileInputPlugin):
1. `plugin.JRubyPluginSource` calls `Plugin.new_java_input`
2. it looks up for `embulk/input_s3.rb` file as an usual ruby-based plugins
3. it ([input_s3.rb](https://github.com/embulk/embulk-plugin-s3/blob/master/lib/embulk/input_s3.rb)) calls `JavaPlugin.register_input`
4. it creates `spi.PluginClassLoader` with jar file list
5. `spi.PluginClassLoader` is designed to load class from the specified jar file list first. If one doesn't exist, it loads class from the parent classloader (=JRubyClassLoader)
6. `JavaPlugin.register_input` loads `S3FileInputPlugin` from the new classloader and calls …
=> Java plugin loader

lib/embulk/data/new/java/build.gradle.erb, lib/embulk/data/new/java/file_input.java.erb, lib/embulk/data/new/java/file_output.java.erb, lib/embulk/data/new/java/input.java.erb, lib/embulk/data/new/java/output.java.erb, lib/embulk/data/new/ruby/gemspec.erb
* fixed license declarations within the templates of java/build.gradle and gemspec.
* changed the method bodies within the templates of Java plugin classes. By the changing, the generated Java plugin classes can be compiled.
=> Minor fixed plugin templates

lib/embulk/command/embulk_example.rb, lib/embulk/guess/csv.rb
This changes add support for guessing `escape` and `null_string` options to `csv` guess plugin.
The algorithms are:
* null_string
* count number of `(line-begin | delimiter) candidate (line-end | delimiter)`
* For example, if it finds `,NULL,`, it increments point of `NULL`. It uses the string with the highest point.
* If not found, use default (which means nothing will be null).
* escape
* count number of `candidate (delimiter | quote)`
* For example, if it finds `\"`, it increments point of `\`. It uses the string with the highest point.
* If not found, use "" (empty string).
=> csv guess plugin guesses null_string and escape options

lib/embulk/command/embulk_run.rb, lib/embulk/data/new/ruby/filter.rb.erb, lib/embulk/data/new/ruby/output.rb.erb, lib/embulk/data/new/ruby/parser.rb.erb, lib/embulk/file_input.rb, lib/embulk/parser_plugin.rb, lib/embulk/plugin.rb
For #33. This pull-request adds basic support for ruby-based parser plugins.
It doesn't have convenient utilities such as LineDecoder. We need something similar to TextGuessPlugin or LineGuessPlugin.
=> added basic support for ruby-based parser plugins

lib/embulk/java_plugin.rb
This pull-request fixes ClassNotFoundException on Windows when embulk loads a java-based plugin.
=> Embulk::JavaPlugin.classloader fixed java.net.URL on Windows

lib/embulk/java/time_helper.rb
Please review this patch. 
Detail
https://gist.github.com/hiroyuki-sato/61e5da934ccf41a258ca
Epoch time : 1424770450 is '2015-02-24 18:34:10 +0900'
But, preview result is show 47119-03-07 17:26:40 UTC.
=> Fix timestamp format '%s'

embulk-cli/src/main/sh/selfrun.sh
When a command is "embulk.bat", "%0" is "embulk.bat".
But when a command is "embulk" (an extension can be omitted), "%0" is "embulk", and the error "Error: Unable to access jarfile embulk" will be raised.
I think "%0" should be changed to "%~f0", which means the absolute path (containing an extension) of the bat file.
(http://pf-j.sakura.ne.jp/program/dos/doscmd/str_percent.htm)
Please check it.
=> Fix a problem of embulk.bat (in Windows environment)

embulk-standards/src/main/java/org/embulk/standards/GzipFileEncoderPlugin.java
How is this implementation?
output size examples:
```
input:
2221491 sample_11.csv
output:
28140 level-1-sampleo.000.00.csv.gz
12730 level-6-sampleo.000.00.csv.gz
12457 level-9-sampleo.000.00.csv.gz
```
=> Added compress level parameter in gzip encoding

lib/embulk/data/new/ruby/Rakefile
Default template README.md said 'run "rake" to build', but Rakefile have no default task.
And `rake` will raise an error like below.
```
rake aborted!
Don't know how to build task 'default'
```
// or, should I change README.md?
=> set default task as :build to new Rakefile template

lib/embulk/command/embulk_run.rb
In many countries, this PR is invalid. :dizzy_face:
http://en.wikipedia.org/wiki/Decimal_mark#mediaviewer/File:DecimalSeparator.svg
=> Embulk.run: fix timestamp format.

embulk-standards/src/main/java/org/embulk/standards/CsvTokenizer.java, embulk-standards/src/test/java/org/embulk/standards/TestCsvTokenizer.java
max_quoted_size_limit allows users to limit the size of a quoted value.
Issue #108
=> Limit the size of a quoted value

embulk-core/src/main/java/org/embulk/spi/util/FileInputInputStream.java, embulk-core/src/test/java/org/embulk/spi/TestFileInputInputStream.java
org.embulk.spi.util.FileInputInputStream.skip() returns -1 when there is
no data in the stream. skip() calls read() method and use the returned
value without validation. skip() should return 0 or more positive value
when read() returns -1.
=> Fixed FileInputInputStream.skip() to avoid returning -1

embulk-core/src/main/java/org/embulk/command/Runner.java, embulk-core/src/main/java/org/embulk/exec/ForGuess.java, embulk-core/src/main/java/org/embulk/exec/GuessExecutor.java, embulk-core/src/main/java/org/embulk/exec/LoggerProvider.java, embulk-standards/src/main/java/org/embulk/standards/StandardPluginModule.java, lib/embulk/command/embulk_run.rb
For #35.
`guess` subcommand accepts `-g, --guess NAMES` option to use installed guess plugins.
=> guess executor gets list of guess plugin names from system config

embulk-standards/src/main/java/org/embulk/standards/StandardPluginModule.java, lib/embulk/guess_plugin.rb
* TextGuessPlugin invokes charset guess plugin automatically.
* LineGuessPlugin invokes charset and newline guess plugins automatically
* charset and newline guess plugins are not loaded by default
=> Don't load newline and charset plugins by default

embulk-standards/src/main/java/org/embulk/standards/CsvFormatterPlugin.java
It can use another delimiter instead of commna(',').
Reported-by hito4t <thitoshi@cac.co.jp>
=> Add delimiter config in CsvFormatter.

embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java, embulk-standards/src/main/java/org/embulk/standards/CsvTokenizer.java, embulk-standards/src/test/java/org/embulk/standards/TestCsvParserPlugin.java, lib/embulk/guess/csv.rb, lib/embulk/guess_plugin.rb
New `skip_header_lines` (int, optional) replaces `header_line` parameter. `header_line` parameter is obsoleted but kept for backward compatibility.
=> Add skip_header_lines option to CSV parser plugin

build.gradle
Since test utilities in embulk-core project are useful for plugin development, we should create and release embulk-xxx-tests.jar files.
=> build.gradle: create and release embulk-xxx-tests.jar

embulk-core/src/main/java/org/embulk/exec/SamplingParserPlugin.java
When running guess command, 'decoders' is used for sampling and guess. So, when 'decoders' is set explicitly, exception is thrown while running guess.
When running sampling in SamplingParserPlugin.runFileInputSampling(), input config.yml file is used. The method is called from FileInputRunner.guess() and FileInputRunner.guess() also calls guessParserConfig() for the read sampling buffer. In guessParserConfig(), FileInputRunner runs decoders again to guess a file format.
If 'decoders' is set, it is run for both sampling and guess. It will cause a problem when setting decoders in config.yml for guess command.
I think one of using 'decoders' should be removed for guess command. Personally, I thought sampling is better to read a file only. (Or, changing FileInputRunner.guessParserConfig() to …
=> Fix guess command ran decoders plugin for both sampling and guess

lib/embulk/guess/schema_guess.rb
`schema_guess.rb` can detect `true` strings for boolean column. But, if there is a `false` string, then the guessed column type becomes `string` type instead of `boolean`.
Current guess plugin can detect boolean column when all rows have `true` value using `TRUE_STRINGS` hash table. However, there is a `false` value, then the column becomes `string` type. I think this should be able to guess both `true` and `false`. From this, my change is to add `FALSE_STRINGS` and the values are similar values as `TRUE_STRINGS` except all values mean false values.
- Setup latest embulk version to be able to detect true column.
- Create a sample.
```
$ embulk example try1
```
- Remove gz sample csv file.
```
$ rm try1/csv/sample_01.csv.gz
```
- Create like the following csv file
```
$ cat …
```
=> Fix schema_guess.rb fails to detect boolean column when there is false value in the column.

embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java, embulk-standards/src/test/java/org/embulk/standards/TestCsvParserPlugin.java
I want to parse the CSV with the optional columns, such as the following.
```
id,name,country,favorite(optional)
1,shinichi,JP,karaoke
2,scott,US
```
This pull-request add the option to allow CSV to have insufficient columns.(default is "false")
```
parser:
type: csv
delimiter: ','
allow_optional_columns: true
columns:
- {name: id,       type: long}
- {name: name,     type: string}
- {name: country,  type: string}
- {name: favorite, type: string}
```
=> Add allow_optional_columns option

embulk-core/src/main/java/org/embulk/spi/unit/ByteSize.java, embulk-core/src/test/java/org/embulk/spi/unit/TestByteSize.java
This pull-request adds `org.embulk.spi.unit.ByteSize` so that plugins can get formatted values in configuration parameter. For example,
```
public interface PluginTask implements Task
{
@Config("batch_size")
public ByteSize getBatchSize();
}
```
with this code, we can use this format in configuration file:
```
batch_size: 10B
batch_size: 42KB
batch_size: 4.2MB
batch_size: 0.5GB
```
This fixes part of #156.
=> Added org.embulk.spi.unit.ByteSize

embulk-cli/src/main/java/org/embulk/cli/Main.java, embulk-core/src/main/java/org/embulk/command/Runner.java, embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java, embulk-core/src/main/java/org/embulk/spi/Exec.java, embulk-core/src/main/java/org/embulk/spi/FileInputRunner.java, lib/embulk/command/embulk_run.rb, lib/embulk/java/bootstrap.rb, lib/embulk/plugin.rb
When running test cases, it shows this message:
```
warning: already initialized constant Injector
...
```
This warning happens when a JVM process Instantiates multiple Injectors because `ScriptingContainer` uses `LocalContextScope.SINGLETON` mode which means there is only one JRuby runtime environment in the JVM.
By this pull-request, Injector (`JRubyScriptingModule.ScriptingContainerProvider`) creates JRuby runtime for each Injector instances. So, each Injectors have isolated JRuby runtime and execution environment.
=> Create JRuby run and its execution environment for each Injector instances

lib/embulk/command/embulk_run.rb, lib/embulk/data/new/gitignore.erb, lib/embulk/data/new/java/build.gradle.erb
Background: plugin developers want to try a plugin without releasing it every time.
This pull-request adds `-L, --load PATH` argument to load a plugin without installing it.
```
$ embulk run -L ./path/to/embulk-input-myplugin config.yml
```
This pull-request also includes changes of build script of java-based plugins so that it generates gemspec file to work with the new -L argument.
=> Add -L, --load PATH argument to use a local plugin

embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java, lib/embulk/guess/schema_guess.rb
This pull request changes guessing behavior so that "f" and "t" are gussed as boolean type.
=> Guess 't' and 'f' as boolean type rather than string.

lib/embulk/command/embulk_run.rb, lib/embulk/command/embulk_selfupdate.rb
This pull-request adds `selfupdate` subcommand that upgrades embulk.jar version to the latest released version.
=> Add selfupdate subcommand

embulk-core/build.gradle
=> use processResources.from to include ruby scripts to embulk-core.jar

embulk-core/src/main/java/org/embulk/spi/util/ResumableInputStream.java, embulk-core/src/main/java/org/embulk/spi/util/RetryExecutor.java
This pull-request add RetryExecutor and ResumableInputStream utility classes to org.embulk.spi.util package.
Originally I implemented them for private code. Then I ported them to embulk-input-s3 and embulk-input-ftp. They're generic useful utility classes for all file input plugins.
=> Add RetryExecutor and ResumableInputStream utility classes

embulk-docs/src/built-in.rst, embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java, lib/embulk/guess/csv.rb
Adds `allow_extra_columns` option to csv parser plugin.
The default behavior also changes.
=> csv parser supports allow_extra_columns option to control whether skip orr not rows with too many columns

embulk-core/src/main/java/org/embulk/spi/util/LineEncoder.java
Although FileOutputOutputStream is also buffered, this change improves
performance of CsvFormatterPlugin about 10%.
=> LineEncoder uses BufferedWriter.

lib/embulk/guess/schema_guess.rb
It may cause too many wrong guesses. CSV parser still supports
converting 0/1 to boolean. So, this change affects only to guess.
=> SchemaGuess doesn't guess 0 and 1 as boolean.

embulk-cli/src/main/sh/selfrun.sh, embulk-cli/src/test/java/org/embulk/cli/DummyMain.java, embulk-cli/src/test/java/org/embulk/cli/SelfrunTest.java
The Windows version is not completely same as the Linux version.
If an argument contains '=', it should be enclosed by double quotations, because otherwise the left side and the right side are divided as two arguments in the bat program.
<pre>
embulk.bat "-J-Dembulk.max_threads=1" run mysql.yml
</pre>
=> Implement selfrun.sh for Windows

embulk-core/src/main/java/org/embulk/spi/time/TimestampParseException.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java, lib/embulk/java/time_helper.rb
When preview, I sometimes get warning as below. 
The root cause of the warning is broken data, but I think the messages is not clear.
```
2015-06-11 07:15:59.911 +0000 [WARN] (preview): Skipped line 7 (org.embulk.spi.time.TimestampParseException): abadijo01,1854,11,4,USA,PA,Philadelphia,1905,5,17,USA,NJ,Pemberton,John,Abadie,John W.,192,72,R,R,1875-04-26,1875-06-10,abadj101,abadijo01
```
The change improves it.
```
2015-06-11 07:58:23.784 +0000 [WARN] (preview): Skipped line 7 (org.embulk.spi.time.TimestampParseException: Failed to parse '1875-04-26'): abadijo01,1854,11,4,USA,PA,Philadelphia,1905,5,17,USA,NJ,Pemberton,John,Abadie,John W.,192,72,R,R,1875-04-26,1875-06-10,abadj101,abadijo01
```
=> Improve warning if failed to parse timestamp.

embulk-standards/src/main/java/org/embulk/standards/CsvTokenizer.java
Currently line number in warning messages start at 0 and it makes me confused when investigation problems.
```
2015-06-19 11:56:53.885 +0900 [WARN] (preview): Skipped line 7 (org.embulk.spi.time.TimestampParseException: Failed to parse '1875-04-26'): abadijo01,1854,11,4,USA,PA,Philadelphia,1905,5,17,USA,NJ,Pemberton,John,Abadie,John W.,192,72,R,R,1875-04-26,1875-06-10,abadj101,abadijo01
```
=> Line number in log messages should start at 1

embulk-core/src/main/java/org/embulk/exec/GuessExecutor.java, embulk-core/src/main/java/org/embulk/exec/SamplingParserPlugin.java
If there is an empty file first, guess fails with "No input buffer to
guess" message. Or the first file is too small, guess doesn't work well.
=> GuessExecutor skips files smaller than 40 bytes.

README.md
Access to the current URL gives us 404 status code.
=> Fix unavailable URL to access to 'How to acquire bintray API Keys'

embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java, lib/embulk/guess/csv.rb
If a file format is space-deliminated values, guess-csv doesn't work. It is good if we can write only `type: csv` and `delimiter: ' '` to parser config and run guess. This applies log files created by Amazon ELB, for example.
This pull-request improves guess-csv so that it keeps using `delimiter: ` parameter is already set rather than overwrite it every time.
=> guess-csv keeps delimiter if already set

embulk-standards/src/main/java/org/embulk/standards/CsvFormatterPlugin.java
Hi @frsyuki, I just found a very simple bug which is increment of a counter in loop is missing at CsvFormatterPlugin, when create timeformatters array.
The bug cause for every input which have timestamp field with index bigger then 0 to be Null Exception.
=> Fix trivial increment bug at CsvFormatterPlugin

embulk-core/src/main/java/org/embulk/spi/util/dynamic/AbstractDynamicColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/SkipColumnSetter.java
=> JRuby gives null to an argument of aMethod(IRubyObject)

embulk-core/src/main/java/org/embulk/command/Runner.java, embulk-core/src/main/java/org/embulk/exec/BulkLoader.java, embulk-core/src/main/java/org/embulk/exec/ExecModule.java, embulk-core/src/main/java/org/embulk/exec/PreviewExecutor.java, embulk-core/src/main/java/org/embulk/exec/TempFileAllocator.java, embulk-core/src/main/java/org/embulk/spi/Exec.java, embulk-core/src/main/java/org/embulk/spi/ExecSession.java, embulk-core/src/main/java/org/embulk/spi/FileInputRunner.java, embulk-core/src/main/java/org/embulk/spi/TempFileException.java, embulk-core/src/main/java/org/embulk/spi/TempFileSpace.java, embulk-core/src/main/java/org/embulk/spi/unit/LocalFile.java, embulk-core/src/main/java/org/embulk/spi/unit/LocalFileSerDe.java, embulk-core/src/main/java/org/embulk/spi/util/Inputs.java, embulk-core/src/test/java/org/embulk/EmbulkTestRuntime.java
* ExecSession has cleanup() method. Callers should call it so that
it deletes local temporary files.
* ExecSession should be created using builder. The public constructor of
ExecSession is deprecated.
* ExecSession.getTransactionTimeZone is removed.
=> Add spi.TempFileSpace and spi.unit.LocalFile

lib/embulk/command/embulk_new_plugin.rb, lib/embulk/data/new/README.md.erb, lib/embulk/data/new/java/build.gradle.erb, lib/embulk/data/new/java/decoder.java.erb, lib/embulk/data/new/java/encoder.java.erb, lib/embulk/data/new/java/file_input.java.erb, lib/embulk/data/new/java/file_output.java.erb, lib/embulk/data/new/java/filter.java.erb, lib/embulk/data/new/java/formatter.java.erb, lib/embulk/data/new/java/input.java.erb, lib/embulk/data/new/java/output.java.erb, lib/embulk/data/new/java/parser.java.erb, lib/embulk/data/new/java/plugin_loader.rb.erb, lib/embulk/data/new/java/test.java.erb, lib/embulk/data/new/ruby/filter.rb.erb, lib/embulk/data/new/ruby/formatter.rb.erb, lib/embulk/data/new/ruby/gemspec.erb, lib/embulk/data/new/ruby/input.rb.erb, lib/embulk/data/new/ruby/output.rb.erb, lib/embulk/data/new/ruby/parser.rb.erb
* '-' in plugin name is replaed to '_'.
* package name of java plugins changed from org.embulk.<category> to org.embulk.<category>.<plugin name>.
* java-decode template generator uses InputStreamFileInput.
* java-encoder template generator uses FileOutputOutputStream.
* java-file-input template generator uses InputStreamTransactionalFileInput.
* guess method of generated java-input plugin returns empty config diff
rather throwing an exception.
=> Update plugin template generator

lib/embulk/data/new/README.md.erb
`embulk new ruby-*` commands fails while creating README.md at Embulk v0.6.17.
I fixed it.
```
$ embulk new ruby-input hoge
2015-07-21 18:28:16.154 +0900: Embulk v0.6.17
Creating embulk-input-hoge/
Creating embulk-input-hoge/README.md
NameError: undefined local variable or method `project_name' for Embulk:Module
result at (erb):5
eval at org/jruby/RubyKernel.java:1107
result at /Users/Satoshi/.embulk/bin/embulk!/META-INF/jruby.home/lib/ruby/1.9/erb.rb:838
erb at file:/Users/Satoshi/.embulk/bin/embulk!/embulk/data/package_data.rb:35
cp_erb at file:/Users/Satoshi/.embulk/bin/embulk!/embulk/data/package_data.rb:45
open at org/jruby/RubyIO.java:1181
cp_erb at file:/Users/Satoshi/.embulk/bin/embulk!/embulk/data/package_data.rb:45
new_plugin at …
```
=> Fix failure of `embulk new ruby-*` commands

embulk-core/src/main/java/org/embulk/EmbulkService.java
To override binding, this method is useful like:
```java
class MyEmbulkService extends EmbulkService
{
@Override
Injector newInjector(ImmutableList<Module> modules)
{
return Guice.createInjector(Modules.override(modules).with(new MyExecModule()));
}
}
```
=> Add EmbulkService#newInjector

embulk-standards/src/main/java/org/embulk/standards/RenameFilterPlugin.java, embulk-standards/src/main/java/org/embulk/standards/StandardPluginModule.java, embulk-standards/src/test/java/org/embulk/standards/TestRenameFilterPlugin.java
It allows users to rename existing column names. Users can use like following:
```
filters:
- type: rename
columns:
my_column_name1: new_name1
my_column_name2: new_name2
```
=> add RenameFilterPlugin

lib/embulk/command/embulk_run.rb
Related to #234.
I found that embulk plugins written in ruby always use following code:
```ruby
classpath_dir = Embulk.home("classpath")
jars = Dir.entries(classpath_dir).select{|f| f =~ /\.jar$/ }.sort
jars.each do |jar|
require File.join(classpath_dir, jar)
end
```
How about this patch?
This patch makes above code in embulk plugin test as follows:
```ruby
Embulk.require_jar
```
=> Provide importing Embulk dependent jars utility API

embulk-core/src/main/java/org/embulk/spi/TempFileSpace.java
For JDK 1.7 or later, it can use useful pattern which is combining `java.nio.file.Files` and `java.nio.file.SimpleFileVisitor` to do file operation.
=> Try to clean up temp files recursively in TempFileSpace.java

build.gradle, embulk-core/build.gradle, embulk-core/src/main/java/org/embulk/command/LiquidTemplate.java, embulk-core/src/main/java/org/embulk/command/Runner.java, lib/embulk/command/embulk_run.rb, lib/embulk/gems.rb, lib/embulk/java/bootstrap.rb, lib/embulk/java/liquid_helper.rb
Implements #253.
When Embulk loads a configuration file, if file extension is .yml.liquid, it runs Liquid template engine. In the config file, we can use `env` to embed environment variable. For example,
```yaml
in:
type: file
path_prefix: {{ env.prefix }}
```
This is experimental because of following limitations and concerns:
* Once `guess` runs, all variables are embedded. So, written configuration file is yaml. Not liquid.
* Variables won't be escaped or quoted.
* Liquid itself supports nested objects such as arrays and maps. But this code doesn't support them because all variables are String.
=> Add experimental support for Liquid template engine

embulk-core/src/main/java/org/embulk/exec/TempFileAllocator.java
Because Windows cannot include ':' as file name.
<pre>
2015-08-14 18:04:41.602 +0900 [INFO] (transaction): {done:  1 / 1, running: 0}
java.nio.file.InvalidPathException: Illegal char <:> at index 61: C:\...\Temp\embulk\2015-08-14 09:04:38.267 UTC
at sun.nio.fs.WindowsPathParser.normalize(sun/nio/fs/WindowsPathParser.java:182)
at sun.nio.fs.WindowsPathParser.parse(sun/nio/fs/WindowsPathParser.java:153)
at sun.nio.fs.WindowsPathParser.parse(sun/nio/fs/WindowsPathParser.java:77)
at sun.nio.fs.WindowsPath.parse(sun/nio/fs/WindowsPath.java:94)
at sun.nio.fs.WindowsFileSystem.getPath(sun/nio/fs/WindowsFileSystem.java:255)
at java.io.File.toPath(java/io/File.java:2186)
at org.embulk.spi.TempFileSpace.deleteFilesIfExistsRecursively(org/embulk/spi/TempFileSpace.java:63)
at …
=> Replace ':' with '-' in temp file space name.

appveyor.yml, build.gradle, test/run-test.rb
Windows CI settings for AppVeyor.
And I added `run-test.rb` to avoid curious rubyTest error on Windows.
NOTE: Currently, only 64bit version task is enabled.
=> Add AppVeyor settings to start Windows CI

embulk-core/src/main/java/org/embulk/config/ConfigException.java, embulk-core/src/main/java/org/embulk/config/UserDataException.java, embulk-core/src/main/java/org/embulk/config/UserDataExceptions.java, embulk-core/src/main/java/org/embulk/spi/DataException.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampParseException.java, embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java, embulk-standards/src/main/java/org/embulk/standards/CsvTokenizer.java, lib/embulk/error.rb
An exception class DataException is expected to be thrown if input data
has a problem (e.g. unexpected timestamp format).
An interface UserDataException is implemented by exception classes which
represent a problem of input data by users. For example,
ConfigException, DataException and TimestampParseException. If those
exceptions are thrown, applications are suggested not to retry this bulk
load because retried bulk import will fail again unless user's input
data is fixed.
=> Add DataException and UserDataException tag interface

lib/embulk/command/embulk_run.rb
To avoid curious result, I use `options` in Embulk.selfupdate argument instead of `system`.
Related to #280.
=> Fix selfupdate subcommand

lib/embulk/command/embulk_migrate_plugin.rb, lib/embulk/data/package_data.rb
Use File#binread, when copy 'gradle-wrapper.jar'.
see #286 issue.
=> Fix fail migrate on windows.

lib/embulk/data/new/ruby/filter.rb.erb
ruby-filter template does not define ``out_columns``
alternative idea
```ruby
yield(task, in_schema)
```
=> Add out_columns parameter definition (ruby-filter template)

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/config/CommitReport.java, embulk-core/src/main/java/org/embulk/config/ConfigDiff.java, embulk-core/src/main/java/org/embulk/config/ConfigSource.java, embulk-core/src/main/java/org/embulk/config/DataSource.java, embulk-core/src/main/java/org/embulk/config/DataSourceImpl.java, embulk-core/src/main/java/org/embulk/config/TaskReport.java, embulk-core/src/main/java/org/embulk/config/TaskSource.java, embulk-core/src/main/java/org/embulk/exec/ConfigurableGuessInputPlugin.java, embulk-core/src/main/java/org/embulk/exec/GuessExecutor.java, embulk-core/src/main/java/org/embulk/spi/FileInputRunner.java
New `exec: {guess_plugins: [array]}` option allows users to configure
list of guess plugins within a configuration file.
This is implemented as following: if an input plugin implements
ConfigurableGuessInputPlugin interface, GuessExecutor gives exec config
to guess method. FileInputRunner implements it and takes
guess.guess_plugins parameter.
Fixes [#266].
=> Added exec.guess_plugins option for guess executor

build.gradle, embulk-core/src/test/java/org/embulk/spi/util/TestLineDecoder.java
This PR adds basic multibyte tests to LineDecoder.
It world be better more character type in test data?
=> Add basic multiline basic LineDecoder tests

embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java
Because this deprecated function has no effect in JRuby 9.0.0.0 or later.
see:
https://github.com/jruby/jruby/blob/e10ec96f39d236e947d969877d138123a8af5344/core/src/main/java/org/jruby/embed/ScriptingContainer.java#L508
=> Purge setCompatVersion code

lib/embulk/data/new/java/decoder.java.erb, lib/embulk/data/new/java/encoder.java.erb, lib/embulk/data/new/java/file_input.java.erb, lib/embulk/data/new/java/file_output.java.erb, lib/embulk/data/new/java/filter.java.erb, lib/embulk/data/new/java/formatter.java.erb, lib/embulk/data/new/java/input.java.erb, lib/embulk/data/new/java/output.java.erb, lib/embulk/data/new/java/parser.java.erb
I found some typos in Java-based plugin's templates and fixed it.
=> Fix typos in Java-based plugin's templates

lib/embulk/command/embulk_run.rb
Please review this patch.
Fix following exception.
```
embulk bundle /tmp/hoge2
2015-09-17 19:21:53.252 +0900: Embulk v0.7.4
NameError: undefined local variable or method `path' for Embulk:Module
run at /path/to/.embulk/bin/embulk!/embulk/command/embulk_run.rb:133
<top> at /path/to/.embulk/bin/embulk!/embulk/command/embulk_main.rb:2
require at org/jruby/RubyKernel.java:940
(root) at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
<top> at file:/path/to/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:55
```
=> Fix: NameError exception.

embulk-cli/src/main/sh/selfrun.sh
For execute on Cygwin, return java command exit code.
=> selfrun.sh: Added argument ERRORLEVEL to exit/b after java command

embulk-core/src/main/java/org/embulk/exec/BulkLoader.java
This commit fixes this error happens when an executor finishes without
throwing exceptions but some tasks failed:
```
2015-10-28_20:18:29.04862 Caused by: org.embulk.exec.PartialExecutionException: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
2015-10-28_20:18:29.04864     at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:333)
2015-10-28_20:18:29.04875     at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:531)
2015-10-28_20:18:29.04878     at org.embulk.exec.BulkLoader.access$100(BulkLoader.java:33)
2015-10-28_20:18:29.04882     at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:344)
2015-10-28_20:18:29.04887     at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:340)
2015-10-28_20:18:29.04896     at …
```
=> state.isAllTasksCommitted() should be check to throw an exception

embulk-core/src/main/java/org/embulk/spi/AbortTransactionResource.java, embulk-core/src/main/java/org/embulk/spi/CloseResource.java, embulk-core/src/main/java/org/embulk/spi/FileInputRunner.java, embulk-core/src/main/java/org/embulk/spi/FileOutputRunner.java, embulk-core/src/main/java/org/embulk/spi/util/Executors.java
If an exception happens both in `try` block and `finally` block,
exception by `finally` block overwrites exception by `try` block. Thus
the ssential exception information will be lost if `close()` call at
`finally` block throws an exception.
But with try-with-resource, exception happend at `close()` will be added
to suppressed exception of the exception at `try` block.
=> Prevent exceptions at close() from overwriting essential exception

Gemfile.lock, bin/embulk, embulk-cli/src/main/java/org/embulk/cli/Main.java, embulk-core/build.gradle, embulk.gemspec, lib/embulk.rb, lib/embulk/command/embulk_bundle.rb, lib/embulk/command/embulk_generate_bin.rb, lib/embulk/command/embulk_run.rb
When we deploy embulk to a production environment using chef or
capistrano, gems should be installed to a shared directory
(shared/bundler) but Gemfile.lock should be isolated. --path optoin
works for that case.
This change includes bundler itself to embulk-core.jar so that
embulk_run doesn't have to install bundler. Thus initialization of
bundler becomes less magical.
Following-up of #334.
=> Support "mkbundle --path" option

Gemfile.lock, README.md, bin/embulk, embulk-cli/src/main/java/org/embulk/cli/Main.java, embulk-core/build.gradle, embulk.gemspec, lib/embulk.rb, lib/embulk/command/embulk_bundle.rb, lib/embulk/command/embulk_generate_bin.rb, lib/embulk/command/embulk_run.rb, lib/embulk/data/bundle/Gemfile
`embulk bundle -h` shows help message of bundler. So there are little
chance to know how to use plugin bundles.
This change adds `embulk mkbundle` subcommand that creates new bundle,
and `embulk mkbundle -h` shows usage of plugin bundle.
Mitigates #320.
=> Make "embulk bundle" command less confusing

lib/embulk/runner.rb
Liquid by default is lax (silent) when syntax errors are encountered while parsing a template. It should be configured so they are fatal. For example if you accidentally wrote:
`path_prefix: {{ env.MY_VAR || 'input.csv' }}` instead of
`path_prefix: {{ env.MY_VAR | default: 'input.csv' }}`
Current error message (cryptic and unhelpful): 
`com.fasterxml.jackson.databind.JsonMappingException: Setting null to a task field is not allowed. Use Optional<T> (com.google.common.base.Optional) to represent null.`
With this patch (sane):
`Liquid syntax error: Expected id but found pipe in "{{ env.MY_VAR || 'file' }}"`
=> [Trivial] Use strict mode when rendering liquid templates.

lib/embulk/command/embulk_run.rb
Related #334 
```
./embulk-0.7.8.jar bundle -h 
2015-11-10 13:12:52.282 +0900: Embulk v0.7.8
/path/to/embulk/pkg/embulk-0.7.8.jar!/bundler/man/bundle: No such file or directory
No manual entry for /pat/to/embulk/pkg/embulk-0.7.8.jar!/bundler/man/bundle
```
Add http://bundler.io URL in usage.
=> [Propose] Add bundler URL in help.

embulk-standards/src/main/java/org/embulk/standards/GzipFileDecoderPlugin.java
When a guess executor tries to read a gzipped file, it sometimes cannot read an enough sized sample buffer to guess effectively. In my case, it read about 800 bytes only from the file as a sample buffer and cannot suggest column names and types by the sample buffer.
I changed the internal buffer size in GZIPInputStream to 8*1024 bytes. I think that 4096 bytes are also fine. But default 512 bytes are too small for my case.
=> Change internal buffer size of GzipFileDecoderPlugin for a guess executor

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/exec/BulkLoader.java, embulk-core/src/main/java/org/embulk/exec/PartialExecutionException.java, embulk-core/src/main/java/org/embulk/exec/TransactionStage.java, lib/embulk/runner.rb
Previous implementation was throwing RuntimeException when exception
happens before starting any tasks. But with it, applications can't get
TransactionState.***_BEGIN stages from PartialExecutionException.
This change changes the behavior to throw PartialExecutionException.
This follows-up #342.
=> Throw PartialExecutionException when exception happens before any tasks

embulk-core/src/main/java/org/embulk/exec/BulkLoader.java, embulk-core/src/main/java/org/embulk/exec/PartialExecutionException.java, embulk-core/src/main/java/org/embulk/exec/TransactionStage.java
This new attribute is useful for applications embedding Embulk so that
they can tell at which stage exception happens.
=> Add TransactionStage to PartialExecutionException

lib/embulk/command/embulk_run.rb
no ``cleanup`` command help
```
Embulk v0.7.10
usage: <command> [--options]
commands:
mkbundle   <directory>                             # create a new plugin bundle environment.
bundle     [directory]                             # update a plugin bundle environment.
run        <config.yml>                            # run a bulk load transaction.
preview    <config.yml>                            # dry-run the bulk load without output and show preview.
guess      <partial-config.yml> -o <output.yml>    # guess missing parameters to create a complete configuration file.
gem        <install | list | help>                 # install a plugin or show installed plugins.
new        <category> <name>                       # generates new plugin template
migrate    <path> …
```
=> Add usage cleanup command

test/guess/test_csv_guess.rb, test/helper.rb
Added CSV guess tests except `escape` option.
The reason is as [pending comment](https://github.com/embulk/embulk/pull/352/files#diff-3b3b0c90c6f748ef34ae306fd6c6f441R42), but I'm not sure that is intentional or bug...
=> Add CSV guess test

embulk-standards/src/main/java/org/embulk/standards/CsvTokenizer.java
When `trim_if_not_quoted` is true, `AB C` will be parsed as "".
=> Fix bug of trimming in CsvTokenizer 

lib/embulk/command/embulk_new_plugin.rb, lib/embulk/data/new/java/build.gradle.erb, lib/embulk/data/new/java/config/checkstyle/checkstyle.xml
Add recommend codestyle setting by default in Java generator.
* They want to unify codestyle. [Twitter](https://twitter.com/Civitaspo/status/685048411159019521)(Japanese)
* Some people want to know what kind of codestyle use.
[Twitter](https://twitter.com/hanpen_good/status/623266724763140096)(Japanese)
This is also follow-up https://github.com/embulk/embulk-executor-mapreduce/issues/15
=> [Propose] Add checkstyle settings in Java plugin generator

lib/embulk/command/embulk_migrate_plugin.rb, lib/embulk/data/new/java/build.gradle.erb, lib/embulk/data/new/java/config/checkstyle/default.xml
Follow-up pull-request of #361.
Running strict checkstyle every time is annoying. I want to avoid it. This pull-request solves this issue as following:
* defines 2 types of checkstyles: looser (default.xml) and stricter (checkstyle.xml).
* "check" task uses looser rule.
* "check" task doesn't fail even if checkstyle fails. Checkstyle should be warning.
* "checkstyle" task uses stricter rule. developers can run it optionally at the end of CI.
=> add migrate for checkstyle

lib/embulk/command/embulk_new_plugin.rb
Copy missing default.xml in new command. 
```
./gradlew check
:compileJava
:processResources UP-TO-DATE
:classes
:checkstyleMain FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':checkstyleMain'.
> Unable to create a Checker: configLocation {/private/tmp/embulk-parser-hoge/config/checkstyle/default.xml}, classpath {/private/tmp/embulk-parser-hoge/build/classes/main:/private/tmp/embulk-parser-hoge/build/resources/main}.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 4.036 secs
```
=> Copy default checkstyle config in new command

lib/embulk/command/embulk_migrate_plugin.rb, lib/embulk/data/new/java/build.gradle.erb
this migrate should be updated once embulk is build with JDK 8.
=> new and migrate add sourceCompatibility = 1.7 and targetCompatibility = 1.7 to build.gradle

embulk-core/src/main/java/org/embulk/config/ConfigLoader.java, embulk-core/src/main/java/org/embulk/config/YamlTagResolver.java
This change includes following restrictions:
* Strings starting with 0 such as 019 will be string instead of float.
This is changed to be compatible with YAML 1.1 generators.
This is a workaround for https://bugs.ruby-lang.org/issues/11988
* Dates like 2015-01-01 00:00:00 will be string instead of java.util.Date.
This is changed because jackson uses UNIX timestamp numbers
unexpectedly when it converts from Date to String.
* 'on', 'off', 'yes' or 'no' (case insensitive) will be string instead
of boolean. Only 'True', 'true', 'False' and 'false' (case sensitive)
are accepted as boolean.
=> customize Yaml tag resolver to be more strict

embulk-core/src/main/java/org/embulk/exec/LocalExecutorPlugin.java
When input task count is 0 (ex. input file for file input plugin is empty), following exception will be thrown.
<pre>
Caused by: java.lang.ArithmeticException: / by zero
at org.embulk.exec.LocalExecutorPlugin.newExecutor(LocalExecutorPlugin.java:64)
at org.embulk.exec.LocalExecutorPlugin.transaction(LocalExecutorPlugin.java:53)
</pre>
=> Avoid /0 when no input task

lib/embulk/runner.rb
``embulk run config.yml -c diff.yml`` command fail if ``diff.yml``  not exists.
[test code](https://gist.github.com/hiroyuki-sato/64792328449d6099953a)
This code create empty file. 
https://github.com/embulk/embulk/blob/master/lib/embulk/runner.rb#L61
So I ignore if file size == 0
=> Fix embulk run config.yml -c diff.yml fail.

lib/embulk/guess/schema_guess.rb
=> SchemaGuess guesses ruby hash and array objects as a json column

embulk-core/src/main/java/org/embulk/exec/SetCurrentThreadName.java
SetCurrentThreadName can set same names to multiple threads such as
"preview", "guess", or "task-1". It makes it hard to debug problems such
as deadlock because Java stacktrace includes these names.
=> Thread name should be always unique for debug purpose

embulk-core/src/main/java/org/embulk/spi/PageBuilder.java
Fixes https://github.com/sonots/embulk-filter-column/issues/8
=> PageBuilder#close doesn't close underlaying output

embulk-core/build.gradle
Let's upgrade msgpack-core:-)
The following is diff between v0.8.1 and v0.8.3. I think that we can safely upgrade it. 
https://github.com/msgpack/msgpack-java/compare/0.8.1...0.8.3
=> Upgrade msgpack-core v0.8.3

embulk-core/build.gradle
Release notes:
https://github.com/msgpack/msgpack-java/blob/develop/RELEASE_NOTES.md
=> Update msgpack-java to v0.8.3

lib/embulk/schema.rb
Using json type with jruby plugin, I got `Fix uninitialized constant MessagePack` as https://gist.github.com/sonots/617c7cf246a0c522651c. 
I am not sure a correct way to fix, but this patch fixed the issue anyway.
=> Fix uninitialized constant MessagePack

embulk-core/src/main/java/org/embulk/config/TaskSerDe.java
TaskDeserializer checks existance of JsonToken.END_OBJECT to break a
loop. But END_OBJECT never comes if cursor is not a object.
This configuration reproduce the problem:
filters:
- type: add_time
to_column:
name: time
from_column:
foo
=> Fix possible busy loop at TaskDeserializer

lib/embulk/guess/time_format_guess.rb, test/guess/test_time_format_guess.rb
Guessed value should always be %z.
See https://github.com/jruby/jruby/issues/3702 for the discussion.
=> TimeFormatGuess doesn't guess %Z because it doesn't work.

embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampFormatterParser.java
This option is useful when a timestamp string doesn't include date and
user wants to set date in a config file. For example, a CSV file
includes "02:46:29" and a config file includes "date: 2016-02-03".
=> Added 'date' option to timestamp type field

embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java, embulk-standards/src/main/java/org/embulk/standards/CsvTokenizer.java, embulk-standards/src/test/java/org/embulk/standards/TestCsvParserPlugin.java
For example,
```
id::name::comment
1::foo::bar
2::bar::baz
```
=> CSV parser supports delimiter longer than 1 character

embulk-standards/src/main/java/org/embulk/standards/CsvTokenizer.java
CSV Tokenizer should set lineNumber to 0 when CSV Parser's nextFile method is called.
=> CSV Parser: CSV Tokenizer should set lineNumber to 0

embulk-standards/src/main/java/org/embulk/standards/CsvTokenizer.java
since guess uses `CsvTokenizer.wasQuotedColumn()`
Fix https://github.com/embulk/embulk/issues/439
cc: @muga
=> Revert "remove unused public wasQuotedColumn()"

embulk-core/src/main/java/org/embulk/exec/LocalExecutorPlugin.java
I think dontAbort() should be called after commit() call
when using AbortTransactionResource.
AbortTransactionResource is used in try-with-resource block.
When leaving the block, tran.abort() is called. When commit()
is finished without failure, the abort() call is not required.
From other usage of AbortTransactionResource in embulk,
dontAbort() is called after commit() or just before leaving
try-with-resource block. I think runInputTask() should call
dontAbort() at the end of the block.
Note:
This change doesn't affect actual behavior because
ScatterTransactionalPageOutput.commit()
set null to trans field. So, abort doesn't affect to transactions
except a little bit of cpu time.
=> Add dontAbort() after commit() to skip abort()

embulk-core/src/main/java/org/embulk/exec/LocalExecutorPlugin.java
=> fixes 'IllegalArgumentException: Self-suppression not permitted' when output plugin throws a runtime exception

lib/embulk/guess/schema_guess.rb, test/guess/test_schema_guess.rb
This fixes unexpected guess results of integer types.
Gussing `[1456012800, 1456014800]` is expected to be long but it becomes
string because `1456012800` is guessed as timestamp with `%Y%m%d%H`
format, `1456014800` is guessed as long, and type coalescing from timestamp
to long was not allowed. This adds coalescing from timestamp to long to
fix this issue.
=> Allow type coalesce from timestamp to long at guess

embulk-core/src/main/java/org/embulk/spi/util/ResumableInputStream.java
Because if input stream is already closed, `in.close()` may raise IOException.
In such a situation, Reopener cannot reopen even if input stream is resumable.
ex. SSL connection of embulk-input-gcs is sometimes closed by server side.
=> Ignore IOException when embulk closes input stream in `reopen`

lib/embulk/file_input_plugin.rb, lib/embulk/file_output_plugin.rb, lib/embulk/guess_plugin.rb, lib/embulk/java_plugin.rb
Since the names of methods that Embulk genetes are simple like `java_class`, `java_object`, etc, there might be name conflict with code generation libraries in the future. To avoid the issues, it's better to rename such methods in advance.
=> Rename methods that Embulk generates to avoid name conflict with JRuby

lib/embulk/guess/csv.rb, lib/embulk/guess/csv_all_strings.rb, test/guess/test_csv_all_strings.rb
This guess plugin suggests column types within Csv files as string types. The default Csv guess plugin suggests column types unexpected by users. To execute Embulk correctly, users sometimes need to edit Embulk config manually and fix column types that users expect. But, some users don't want to edit Embulk config so much. 
This plugin is not included in the list of default guess plugins. And to use this plugin, users explicitly need to exclude default csv guess plugin from the list of default guess plugins like:
```
exec:
exclude_guess_plugins: ['csv']
guess_plugins: ['csv_all_strings']
in:
type: file
path_prefix: path/to/csvfile
```
=> Add csv_all_strings guess plugin

embulk-docs/src/built-in.rst
Add `guess_plugins` and `exclude_guess_plugins` description.
Please fix if my English is wrong.
About `guess_plugins` default value, Which is better(correct) ?
* `[]` [GuessExecutor.java](https://github.com/embulk/embulk/blob/master/embulk-core/src/main/java/org/embulk/exec/GuessExecutor.java#L52)
* `['gzip','bzip2','json','csv']` [StandardPluginModule.java](https://github.com/embulk/embulk/blob/master/embulk-standards/src/main/java/org/embulk/standards/StandardPluginModule.java#L52-L55)
It's better to write about guess `csv_all_strings` #489 later. 
Is it better to add  `guess` section?
=> Add missing guess_plugins and exclude_guess_plugins docs

embulk-core/src/main/java/org/embulk/exec/BulkLoader.java, embulk-core/src/main/java/org/embulk/exec/ExecutionResult.java, embulk-core/src/main/java/org/embulk/exec/SkipTransactionException.java
Input/output plugins might need to stop Embulk before the transaction starts by depending
on the conditions of input/output data sources/destinations. They can throw this exception
if they want to do that. Embulk handles it and then stops the transaction.
Currently Embulk hits NPE when input/output plugins return an empty ConfigDiff before the transaction starts to stop Embulk.
```
org.embulk.exec.PartialExecutionException: java.lang.NullPointerException
at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:363)
at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:572)
at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:33)
at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:374)
at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:370)
at …
```
=> Introduce SkipTransactionException to stop Embulk before the transaction starts

embulk-docs/src/built-in.rst
@muga The descriptions of all renaming rules are nested, and may be so long. I'd separate them out if it's not good.
=> Add document for the new "rules" option in the built-in rename filter plugin.

embulk-test/src/main/java/org/embulk/test/TestingEmbulk.java
To test input plugin, we sometimes need custom out: config or exec: config. TestConfigSourceBuilder allows users to custom ConfigSource that they use for input plugin tests.
=> embulk-test: Add RunInputBuilder

embulk-test/src/main/java/org/embulk/test/TestingEmbulk.java
RunOutputBuilder allows plugin developers to write unit tests simply and easily like runInput method.
This PR expects to merge #513.
=> embulk-test: Add OutputBuilder

README.md
Can not be executed with the configuration file of the document.
like below: 
> Field 'parser' is required but not set
> 
> ```
> $ embulk run ./config.yml
> 2016-09-24 11:44:03.959 +0900: Embulk v0.8.13
> 2016-09-24 11:44:06.954 +0900 [INFO] (0001:transaction): Loaded plugin embulk-output-command (0.1.4)
> org.embulk.exec.PartialExecutionException: org.embulk.config.ConfigException: com.fasterxml.jackson.databind.JsonMappingException: Field 'parser' is required but not set
>  at [Source: N/A; line: -1, column: -1]
>     at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:363)
>     at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:572)
>     at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)
> …
```
=> Fix an example in Quick Start

embulk-core/src/main/java/org/embulk/spi/PageBuilder.java
The problem is that PageBuilder#set{String,Timestamp,Json} throw NPE if null object is given.
Basically plugins should handle null object appropriately. But, I think that the #set{String,Timestamp,Json} should take one of the following:
a. Accept null object and call #setNull. 
b. Throw an appropriate exception instead of NPE.
This PR takes a. 
```
2017-01-23 11:51:23.083 +0000 [WARN] (main): null 
org.embulk.exec.PartialExecutionException: java.lang.NullPointerException 
at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:373) ~[embulk-core-0.8.15.jar:na] 
at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:591) ~[embulk-core-0.8.15.jar:na] 
at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:33) ~[embulk-core-0.8.15.jar:na] 
at …
```
=> Avoid NPE is thrown by PageBuilder#set{String,Timestamp,Json}

build.gradle
Fix build.gradle to solve warning that the leftShift method has been deprecated.
```
$ ./gradlew task
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
at build_3un9xu433va9p4g0k416sca11.run(/path/to/embulk/build.gradle:204)
```
=> build.gradle: Use Task.doLast instead of Task.leftShift

build.gradle
JRuby 9.1.7.0 released at 11/Jan/2017. 
http://jruby.org/2017/01/11/jruby-9-1-7-0.html
I made the `updateJRuby` task. 
If the command `./gradlew updateJRuby -Pto=9.1.7.0` execute,
The following change will generate. 
If those feature already implemented, please ignore this PR. 
```diff
a/Gemfile.lock b/Gemfile.lock
index cf7cb56..7099ad1 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -2,12 +2,12 @@ PATH
remote: .
specs:
embulk (0.8.13)
-      jruby-jars (= 9.1.5.0)
+      jruby-jars (= 9.1.7.0)
GEM
remote: https://rubygems.org/
specs:
-    jruby-jars (9.1.5.0)
+    jruby-jars (9.1.7.0)
kramdown (1.5.0)
power_assert (0.2.2)
rake (10.4.2)
diff --git a/build.gradle b/build.gradle
index af261105..b56f237 100644
--- a/build.gradle
+++ b/build.gradle
@@ -19,7 +19,7 @@ allprojects {
version = …
```
=> Add updateJRuby task

embulk-core/src/main/java/org/embulk/spi/json/JsonParser.java
I got the following exception and the JsonParser could not change Java type for mapping Json numbers from long type to BigInteger type. 
```
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (12246234245276851497) out of range of long (-9223372036854775808 - 9223372036854775807)
at [Source: org.embulk.spi.util.FileInputInputStream@6533629; line: 3073, column: 264]
at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
at com.fasterxml.jackson.core.base.ParserBase.reportOverflowLong(ParserBase.java:1003)
at com.fasterxml.jackson.core.base.ParserBase.convertNumberToLong(ParserBase.java:894)
at com.fasterxml.jackson.core.base.ParserBase.getLongValue(Parse …
```
=> JsonParser: Fix how to change Java type for mapping Json numbers

embulk-docs/src/release/release-0.7.8.rst
I found 2 typos in [0.7.8 release note](http://www.embulk.org/docs/release/release-0.7.8.html) so fixed them.
=> Fix typos in 0.7.8 release note

embulk-core/src/main/java/org/embulk/spi/json/JsonParser.java
It would be better that Embulk's Json parser could read and parse non-standard Json formatted files as much as possible. For example, `{"value": Infinity}` and `{"value": -Infinity}` are not Json standard but, they are often used. 
As first implementation, we could use Jackson's Feature.ALLOW_NON_NUMERIC_NUMBERS. If we will care of other cases more, we will need to improve it at that time. 
https://fasterxml.github.io/jackson-core/javadoc/2.5/com/fasterxml/jackson/core/JsonParser.Feature.html#ALLOW_NON_NUMERIC_NUMBERS
=> JsonParser: Enable to parse non numeric numbers as floating number values

embulk-core/build.gradle
Since Netty v5.0.0 development are not so active instead of v4.0.x, I think that it's better to downgrade netty-buffer version for Embulk.
https://github.com/netty/netty/releases
=> Use netty-buffer 4.x instead of 5.x

lib/embulk/guess_plugin.rb
guess_plugin.rb should not use last line because the last line is not always a line. It should remove it from sample_lines.
=> embulk/guess_plugin.rb: Fix and remove last line from sample_lines

embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java
CsvParserPlugin needs to refresh the number of skipped header lines for each file. The current CsvParserPlugin can skip header lines in first file but, it doesn't skip header lines in other files. It means that it reads and parses header lines as records.
=> CsvParserPlugin: Refresh the number of skipped header lines for each file

embulk-core/build.gradle
Due to Fix #574, Update SnakeYAML v1.14 to v1.18
Note.
I also tested SnakeYAML version v1.17.
This version does not solve this issue.
From SnkeYAML Changelog.
https://bitbucket.org/asomov/snakeyaml/wiki/Changes
1.18 (2017-02-22)
Fix issue [#323](https://bitbucket.org/asomov/snakeyaml/issues/323/is-there-any-reason-to-not-support): Support "Miscellaneous Symbols and Pictographs"(thanks to Pawel Skierczynski [Atlassian]). This fix introduces minor backwards-incompatible changes - some of the methods have been renamed.This fixes also long standing issue with [iOS emoji](https://code.google.com/archive/p/snakeyaml/issues/205)
=> Update snakeyaml to v1.18

embulk-core/src/main/java/org/embulk/exec/PreviewExecutor.java
This PR fixes https://github.com/embulk/embulk/issues/570. 
The cause of https://github.com/embulk/embulk/issues/570 is that SamplingPageOutput#finish method is called twice (unexpectedly). Null object is inserted into `pages` object by 1st call. 2nd call uses the null object. Then, we get NPE. 
I think that a plugin implementation causes this issue but, Embulk itself should have the way to avoid this situation. In this case, PreviewResult object should be reused.
=> PreviewExecutor: Fix and avoid to call SamplingPageOutput#finish twice

embulk-core/build.gradle
After the update the Liquid to 4.0.0, The #586 issue fixed.
It's a major upgrade.  I'm worried about the compatibility. 
It seems that there is no critical incompatibility change.
[Liquid Change Log](https://github.com/Shopify/liquid/blob/master/History.md)
```
./pkg/embulk-0.8.18.jar run /tmp/+embulk-error-sample/sample.yml.liquid
2017-03-31 13:06:05.821 +0900: Embulk v0.8.18
2017-03-31 13:06:08.125 +0900 [INFO] (0001:transaction): Listing local files at directory '.' filtering filename by prefix 'sample.json'
2017-03-31 13:06:08.130 +0900 [INFO] (0001:transaction): Loading files []
2017-03-31 13:06:08.150 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / tasks=0
2017-03-31 13:06:08.162 +0900 [INFO] (main): Committed.
2017-03-31 13:06:08.163 +0900 [INFO] …
```
=> For fix #586, update liquid 3.0.6 to 4.0.0

embulk-core/src/main/java/org/embulk/spi/TempFileSpace.java
Fix #580.  Just fix `createTempFiele` #423 not yet fiexed.
```yaml
in:
type: file
path_prefix: C:/path/to/embulk/hoge/csv/sample_
decoders:
- {type: gzip}
parser:
charset: UTF-8
newline: LF
type: csv
delimiter: ','
quote: '"'
escape: '"'
null_string: 'NULL'
trim_if_not_quoted: false
skip_header_lines: 1
allow_extra_columns: false
allow_optional_columns: false
columns:
- {name: account, type: long}
- {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
- {name: purchase, type: timestamp, format: '%Y%m%d'}
- {name: comment, type: string}
#out: {type: stdout}
out:
type: sftp
host: xxx.xxx.xxx.xxx
user: user
secret_key_file: ./test.key
path_prefix: /tmp/hoge
file_ext: .csv
formatter:
type: csv
```
* OS: Windows 10
* Embulk: v0.8.18
```
embulk run config.yml …
```
=> Fix #580: avoid using ':' in temporary file names to be valid in Windows.

build.gradle, embulk-core/build.gradle, embulk-core/src/main/java/org/embulk/EmbulkVersion.java, embulk.gemspec, lib/embulk/command/embulk_migrate_plugin.rb, lib/embulk/command/embulk_run.rb, lib/embulk/command/embulk_selfupdate.rb, lib/embulk/data/new/java/build.gradle.erb, lib/embulk/data/new/ruby/gemspec.erb, lib/embulk/version.rb
@muga Controlling the version number in one place from Gradle, and in Java world. What do you think?
=> Deprecate lib/embulk/version.rb `Embulk::VERSION`, and add `org.embulk.EmbulkVersion` with auto-generated embulk.properties.

README.md
I've forgotten usage `updateJRuby` task.
I update the README. 
Could you add it to README?
By the way, JRuby 9.1.8.0 released at 6/Mar/2017
http://jruby.org/2017/03/06/jruby-9-1-8-0.html
It fixed many issues.
=> Add updateJRuby task document

build.gradle, embulk-core/build.gradle, embulk-core/src/main/java/org/embulk/EmbulkVersion.java
@muga Per #596, removed `embulk.properties` and started to use `Implementation-Version` in the jar manifest. Can you PTAL?
(Will update other PRs depending on `embulk.properties`.)
=> Use the jar manifest (META-INF/MANIFEST.MF) to provide the Embulk version at runtime [#596]

embulk-docs/src/built-in.rst, embulk-docs/src/customization.rst, embulk-docs/src/recipe/scheduled-csv-load-to-elasticsearch-kibana5.rst, embulk-docs/src/release/release-0.4.0.rst, embulk-docs/src/release/release-0.5.0.rst, embulk-docs/src/release/release-0.6.0.rst, embulk-docs/src/release/release-0.6.20.rst
This PR remove the following warning. 
No contents change.
```
Creating account on RubyGems.org
~~~~~~~~~~~~~~~~~~
/path/to/change/embulk/embulk-docs/src/customization.rst:139: WARNING: Title underline too short.
```
The following WARNING can't solve yet. 
```
checking consistency... /path/to/embulk/embulk/embulk-docs/src/developers/index.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
/path/to/embulk/embulk/embulk-docs/src/built-in.rst:98: WARNING: Could not lex literal_block as "yaml". Highlighting skipped.
/path/to/embulk/embulk/embulk-docs/src/built-in.rst:325: WARNING: Could not lex literal_block as "json". Highlighting skipped.
```
=> [Doc] Remove `make html` build warning.

embulk-docs/src/built-in.rst
This PR adds 'guess_sample_buffer_bytes' option (on https://github.com/embulk/embulk/pull/609) in embulk-docs.
=> embulk-docs: Add 'guess_sample_buffer_bytes' option to GuessExecutor section

embulk-core/src/main/java/org/embulk/exec/PreviewExecutor.java
This PR fixes incompatible behavior of `PreviewExecutor` with previous version. That unexpectedly requires `exec:` config during `preview` command is executed. 0.8.18 or older version doesn't require `exec:` config.
The root cause of this issue is that it calls`config.getNested("exec")`. If `config` doesn't have `exec:` config, it gets the `ConfigException`. It should use `task.getExecConfig()` because it will receive default value `{}` if `config` doesn't have `exec:` config.
#618
=> PreviewExecutor: to fix incompatible behavior that it requires exec: config

lib/embulk/command/embulk_run.rb
To fix #625, using Ruby's Embulk::VERSION_INTERNAL in lib/command/embulk_run.rb for the time being.
Cc: @muga @hiroyuki-sato
=> Use Ruby's Embulk::VERSION_INTERNAL to fix #625.

embulk-core/build.gradle
This PR downgrades liquid 4.0.0 to 3.0.6. Liquid was upgraded on Embulk v0.8.19 but, the upgrading causes regression https://github.com/embulk/embulk/issues/627.
=> Downgrade liquid 4.0.0 to 3.0.6

test/mri/date/test_date_strptime.rb
This PR ports test/mri/date/test_date_strptime.rb from JRuby. Because we need to confirm #611 's  `RubyDateParser` behavior is correct or not after #611. It's better to add this test in advance. 
I skipped `test_sz` in the test_date_strptime.rb because the spec is unstable and doesn't pass with our JRuby 9.1.5.0.
=> Add test/mri/date/test_date_strptime.rb for #611

embulk-docs/src/built-in.rst
This PR fix the following WARNING. 
```
/path/to/embulk/embulk-docs/src/built-in.rst:952: WARNING: Title underline too short.
Preview executor
---------------
```
=> [Doc] Fix WARNING: Title underline too short.

embulk-core/src/main/java/org/embulk/spi/PageReader.java
This PR enables `PageReader#getString,Timestamp,Json` to return null object if the column value is null. It came from https://github.com/embulk/embulk-base-restclient/pull/86.
Plugins are responsible for null check because they only know how null object should be handled. In Embulk 0.8.22, if plugins don't do null check, they get `ArrayIndexOutOfBoundsException`. But, it's not easy to understand the exception and the message. This PR changes to call `#isNull` method and return null object if the column value is null, instead of the exception. I believe that this change doesn't have big impact of `PageReader` performance caused by `#isNull` method call.
=> embulk-core: PageReader#get{String,Timestamp,Json} calls #isNull to return null

lib/embulk/guess/json.rb
This PR changes `JsonGuessPlugin` to ignore `JsonParseException` if it can parse even one JSON data. 
`JsonGuessPlugin` guess sometimes fails because it gets `JsonParseException` when it cannot parse the last line of sampling buffer correctly. 
To fix this issue, I changes the guess plugin to ignore `JsonParseException` if even one JSON data can be parsed. I first wanted to use `LineGuessPlugin` but, `JsonGuessPlugin` cannot extend it because `JsonGuessPlugin` should guess multi-line JSON.
=> embulk/guess/json.rb: JsonGuessPlugin ignores JsonParseException

embulk-standards/src/main/java/org/embulk/standards/JsonParserPlugin.java
Similar to #659, it is required for JSON preview.
=> Ignore JsonParseException in JSON preview if at least one JSON is already parsed.

embulk-docs/src/built-in.rst
I tested #647  in my environment, and I got the following error.
I use `note` section instead of the writing URL on the table. 
I also write this note on the CSV parser section. 
@toru-takahashi @dmikurube Please take a look.
```
built-in.rst:492: ERROR: Malformed table.
+----------------------+---------+-------------------------------------------------------------------------------------------------------+-----------------------------------------+
| name                 | type    | description                                                                                           | required?                               |
+======================+=========+=======================================================================================================+============================ …
```
=> Add a note on the timestamp format in embulk-doc with a link to Ruby documents

embulk-core/src/main/java/org/embulk/exec/BulkLoader.java, embulk-core/src/main/java/org/embulk/spi/FileInputRunner.java, embulk-core/src/main/java/org/embulk/spi/FileOutputRunner.java
This PR allows `BulkLoader` to pass file input/output plugins' task source to plugins' `cleanup` method. 0.8.22's `BulkLoader` passes `File Input/Output Runner`s' task source that wrap file input/output plugins' task source defined by the plugins. The behavior doesn't make sense because file input/output plugins should not care of concerns about `Runner` classes directly. 
One concern about this PR is that it breaks backward compatibility of passed task source in `cleanup` method in file input/output plugins but, I think that the PR behavior is more reasonable for the plugins.
This PR fixes https://github.com/embulk/embulk/issues/658.
=> embulk-core: Fix BulkLoader to pass file input/output plugins' task source to plugins' cleanup

embulk-cli/src/main/bat/selfrun.bat
A fix for a problem found on Windows. Can you have a look? @muga
=> Fix "could not find or load main class org.jruby.Main" when run as just "embulk" on Windows.

embulk-standards/src/main/java/org/embulk/standards/ConfigInputPlugin.java, embulk-standards/src/main/java/org/embulk/standards/StandardPluginModule.java
When quick-testing in developing the core or plugins (later than input), it is often annoying to set up input. Prepare CSV on a filesystem, confirm the path, ...
An input which does not depend on external resources may help solving the situation. This is it. An input from the Embulk config itself. :)
```
in:
type:
name: config
columns:
- {name: name, type: string}
values:
- - [ 12, "foo" ]
- [ 24, "bar" ]
- - [ 98, "hoge" ]
- [ 21, "fuga" ]
out:
type: stdout
```
```
2017-06-16 17:34:41.041 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 2 * 2
2017-06-16 17:34:41.053 +0900 [INFO] (0001:transaction): {done:  0 / 2, running: 0}
98,hoge
12,foo
21,fuga
24,bar
2017-06-16 17:34:41.130 +0900 [INFO] …
```
=> Add ConfigInputPlugin for easier testing.

build.gradle
@muga To reduce future risks of dependency conflicts between the core and plugins like #640, this PR tries relocating embedded dependency packages. Can you have a look?
For example, `org.apache.maven*` is relocated to `org.embulk.third_party.org.apache.maven*` in embulk-0.8.XX.jar. All references to these classes are automatically relocated as well.
It's based on the relocation feature in the Gradle Shadow Plugin:
http://imperceptiblethoughts.com/shadow/#relocating_packages
=> Relocate recently-added dependency packages in shadowJar Embulk distribution.

build.gradle
@muga A small change in `build.gradle` only impacting tests.
It passes System Properties of Gradle (can be specified with `-D`) which start with "org.embulk" into testing JVM. It allows developers to test like:
```
./gradlew -Dorg.embulk.someTestingRuntimeParameter=foobar test
```
so that the test can switch its behavior at runtime. One typical usage is removing temporary files. Temporary files are to be removed in usual cases. But, we sometimes want to keep temporary files to analyze when we run tests locally.
https://github.com/embulk/embulk/pull/687/files#diff-de1fed31d83d9cbde4b42260d2e2a8f5R48 is an example.
=> Pass Gradle's System Properties (-D) starting with "org.embulk" to testing JVM.

embulk-docs/src/built-in.rst
Fix invalid JSON data in the built-in document. 
It's inconvenient to test the Embulk.
=> [Doc] Fix invalid json data

embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java
Fix #699 @dmikurube Please take a look when you can.
Un-JRuby embulk migrate replace files properly.
* Fix GRADLE_VERSION_IN_WRAPPER matching pattern.
* Remove trailing character '/'.
* The version strings is `gradle-2.12-bin.zip`
* Avoid `FileAlreadyExistsException`.
* Throw that exception if the file exists.
* Add files into modifiedFiles.
* For output the following message.
* `Done. Please check modifieid files.`
By the way, I found typo (not fixed yet this PR)
* modifieid -> modified
=> Fix the "migrate" subcommand to handle build.gradle correctly

build.gradle, embulk-docs/src/release.rst, embulk-docs/src/release/release-0.8.26.rst, lib/embulk/version.rb
@muga If you're fine with the spec of `MavenPluginSource` (incl. `classifier` and a consensus about plugin's artifact names), I'll be releasing v0.8.26 soon. What do you think?
I'll be merging #685, #702 and #703 as well.
=> Release v0.8.26

test/run-test.rb
This PR changes test/run-test.rb to use https://github.com/embulk/embulk/pull/611's StrptimeParser and RubyDateParser in ruby tests.
=> Test StrptimeParser and RubyDateParser

build.gradle, embulk-docs/src/release.rst, embulk-docs/src/release/release-0.8.27.rst, lib/embulk/version.rb
=> Release v0.8.27

embulk-jruby-strptime/src/main/java/org/embulk/spi/time/RubyDateParser.java, embulk-jruby-strptime/src/main/java/org/embulk/spi/time/StrptimeFormat.java, embulk-jruby-strptime/src/main/java/org/embulk/spi/time/StrptimeParser.java, embulk-jruby-strptime/src/main/java/org/embulk/spi/time/StrptimeToken.java, embulk-jruby-strptime/src/main/java/org/embulk/spi/time/TimeZoneConverter.java
This PR fixes Javadoc comments in embulk-jruby-strptime classes to avoid Javadoc errors as following. Since Embulk release task requires their Javadoc generation, we cannot release new version caused by Javadoc errors. To fix this, It's good to use href tags for external links in `@see` section. 
```
embulk/embulk-jruby-strptime/src/main/java/org/embulk/spi/time/RubyDateParser.java:33: error: unexpected text
* @see https://github.com/jruby/jruby/blob/036ce39f0476d4bd718e23e64caff36bb50b8dbc/lib/ruby/stdlib/date/format.rb
^
```
=> Fix Javadoc in embulk-jruby-strptime classes to avoid Javadoc errors

build.gradle, embulk-cli/src/main/bat/selfrun.bat.template, embulk-cli/src/main/sh/selfrun.sh.template, embulk-cli/src/test/java/org/embulk/cli/SelfrunTest.java
Selfrun scripts run JRuby to get its `ruby_version` since #604. Although the change was made successfully, it needed JRuby to run everytime within selfrun scripts. It made the bootstrap slower.
This PR tries solving the problem by getting `ruby_version` and filling the version in building the jar file.
=> Make selfrun scripts not to run JRuby to get ruby_version.

embulk-cli/src/main/java/org/embulk/cli/Main.java
@muga Can you have a look? Details are in #707.
Embulk is calling org.jruby.Main.main in org.embulk.cli.Main. It is not very good in terms of JRuby's suggestion and JRuby environment isolation -- which "JRuby instance" does `org.jruby.Main.main` use?
In the process of un-JRuby-ing, let's replace it with `ScriptingContainer` which is the standard way to call JRuby embedded from Java.
=> Use JRuby's ScriptingContainer for bootstrap instead of org.jruby.Main.main

.travis.yml
This PR changes .travis.yml to execute sub-projects' tests in parallel on Travis CI. Each matrix row settings will be executed on Travis multiple VMs.
- This PR assumes https://github.com/embulk/embulk/pull/714.
- reference: https://docs.travis-ci.com/user/speeding-up-the-build/
=> Travis tests in parallel to speed up Travis build

embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java
This PR fixes Javadoc comments in `PluginClassLoader` to avoid Javadoc error by Oracle Java8. Because Travis CI uses Oracle java8 so, it cannot generate Embulk's Javadoc documents by the following Javadoc error. I think, that might be why embulk.org is not updated.
https://github.com/embulk/embulk/compare/v0.8.25...v0.8.26
```
embulk/embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java:87: error: unexpected text
* @see https://docs.oracle.com/javase/7/docs/api/java/lang/ClassLoader.html#loadClass(java.lang.String,%20boolean)
^
embulk/embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java:88: error: unexpected text
* @see http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/file/jdk7u141-b02/src/share/classes/java/lang/ClassLoader.java
^
```
=> Fix Javadoc in PluginClassLoader to avoid Javadoc error by Oracle Java8

bin/embulk
@muga #543 was not working with `bin/embulk` when started directly from JRuby. Can you have a look?
=> Run bin/embulk started from JRuby with Java EmbulkRun.

bin/embulk, embulk-cli/src/main/java/org/embulk/cli/EmbulkBundle.java
@muga Embulk's version was not passed well to Java `EmbulkBundle` when started from `bin/embulk` (embulk.gem) through CRuby. Can you have a look?
=> Pass Embulk's version from JRuby (bin/embulk) for Java EmbulkBundle.

appveyor.yml
@muga The `Handle.zip` problem is still happening on AppVeyor. I'm trying to cache the unzipped `handle.exe` (downloaded directly from live.sysinternals.com) in AppVeyor. Can you have a look?
=> Cache handle.exe in AppVeyor.

embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java
This PR fix #715 issue. 
@dmikurube please take a look when you have a time.
=> Fix the `migrate` subcommand to replace build.gradle correctly.

embulk-cli/src/main/java/org/embulk/cli/EmbulkArguments.java, embulk-cli/src/main/java/org/embulk/cli/EmbulkBundle.java
@muga Sorry for the last-minute update for v0.8.28. This _will_ be required to delay initializing Bundler and to delay creating a JRuby instance.
=> Keep the "-b" or "--bundle" option in the argument list.

embulk-cli/src/main/java/org/embulk/cli/EmbulkRun.java
@muga Sorry, I had a stupid mistake. Can you have a look?
=> Fix the wrongly Ruby-style "#{ENV['GEM_HOME']}" in the general usage.

embulk-cli/src/main/java/org/embulk/cli/EmbulkCommandLine.java, embulk-cli/src/main/java/org/embulk/cli/EmbulkRun.java, embulk-core/src/main/java/org/embulk/EmbulkRunner.java, embulk-core/src/main/java/org/embulk/EmbulkSetup.java, lib/embulk/runner.rb
@muga Finally! We don't need `*.rb` files during the bootstrap now. (Several `runScriptlet` is still required, though.)
Can you have a look?
=> Replace Ruby Embulk::EmbulkRunner into Java org.embulk.EmbulkRunner.

build.gradle, embulk-docs/src/release.rst, embulk-docs/src/release/release-0.8.28.rst, lib/embulk/version.rb
@muga As mentioned in #731, v0.8.28 will be released after that. Can you have a look?
=> Release v0.8.28

embulk-cli/src/main/java/org/embulk/cli/EmbulkRun.java, embulk-core/src/main/java/org/embulk/EmbulkRunner.java, embulk-core/src/main/java/org/embulk/EmbulkSetup.java, lib/embulk/runner.rb
@muga As a part of avoiding JRuby instances in the bootstrap process, this PR tries reducing usage of the global (Singleton) JRuby instance. Can you have a look?
(It is not in a hurry. It would be a kind of continued efforts.)
=> Reduce usage of the global (Singleton) JRuby instance

embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatter.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java, embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnSetterFactory.java, embulk-core/src/main/java/org/embulk/spi/util/DynamicPageBuilder.java
@muga Deprecating them for the future. Can you have a look?
They have never been used actually although they're passed through constructors!
=> Deprecate Timestamp-related methods using JRuby ScriptingContainer.

embulk-core/src/main/java/org/embulk/EmbulkRunner.java
@dmikurube Please take a look when you can. 
Fix #758 
```
embulk-0.8.29.jar preview -L ./embulk-input-hoge test.yml
2017-08-11 08:24:06.011 +0900: Embulk v0.8.29
2017-08-11 08:24:08.139 +0900 [INFO] (0001:preview): Loaded plugin embulk/input/hoge from a load path
org.embulk.config.ConfigException: com.fasterxml.jackson.databind.JsonMappingException: Field 'option1' is required but not set
at [Source: N/A; line: -1, column: -1]
```
=> Fix -L option syntax error

embulk-core/src/main/java/org/embulk/EmbulkRunner.java
@muga Can you have a look? It fixes #757.
It was originally like https://github.com/embulk/embulk/blob/v0.8.26/lib/embulk/runner.rb#L128 in Ruby.
Cc: @hiroyuki-sato
=> Make Liquid's "include" work again: Fix #757

embulk-cli/src/main/java/org/embulk/cli/Main.java
@muga I'd include this fix in 0.8.31. Can you have a look?
=> Return non-zero exit status in case of errors: Fix #771

embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java
* This PR split #698 PR into three PRs.
* This PR is (1/3)
I want to add executable permission to `gradlew` file. 
That's why I add `setExecutable` method. 
I'll create another PRs later. Both depend on this PR.
* (2/3) https://github.com/hiroyuki-sato/embulk/tree/update_gradle_4_0
* (3/3) https://github.com/hiroyuki-sato/embulk/tree/task_left_shift_deprecated_caution
=> Add a method in EmbulkMigrate to set executable permissions into plugin's "gradlew"

embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java
After an execute `embulk migrate` in a plugin directory,
Migrator dropped an executable permission of the plugin's gradlew.
This PR add executable permission explicitly. 
Current behavior.
```
embulk migrate .
2017-09-05 13:06:00.997 +0900: Embulk v0.8.31
Detected Java plugin for Embulk 0.8.22...
Modified ./build.gradle
Modified ./embulk-output-db2/build.gradle
Modified ./embulk-output-mysql/build.gradle
Modified ./embulk-output-oracle/build.gradle
Modified ./embulk-output-sqlserver/build.gradle
Done. Please check modified files.
```
```
ls -l gradlew
-rw-r--r--  1 user  staff  5296 Sep  5 13:06 gradlew
```
=> Ensure plugin's "gradlew" to have executable permissions by "migrate" subcommand

embulk-core/build.gradle, embulk.gemspec
@dmikurube @muga 
Please take a look when you can.
* This PR fix #586 issue. 
* The #586 issue fixed by #587 once. but It occurred regression #627 (See detail #637)
* For fix #627, we needed update JRuby 9.1.11.0 and above.
* The #791 Updated JRuby to 9.1.13.0 (Embulk 0.8.34)
* After update JRuby 9.1.13.0, regression #627 has been fixed.
I checked the following.
1. Fix #586 
2. Does not regression #627 
This PR Fix #586.
```
git clone https://github.com/yynozk/embulk-error-sample +embulk-error-sample
cd +embulk-error-sample/
```
```
% embulk run sample.yml.liquid
2017-09-20 20:55:15.297 +0900: Embulk v0.8.34
org.embulk.config.ConfigException: com.fasterxml.jackson.databind.JsonMappingException: Field 'out' is required but not set
at [Source: N/A; line: -1, column: -1]
at …
```
=> Update liquid 4.0.0 again

embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java, embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderFactory.java, embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderModule.java, embulk-core/src/main/java/org/embulk/plugin/jar/JarPluginLoader.java, embulk-core/src/main/resources/embulk/parent_first_packages.properties
@muga @sakama It tries to load dependency JARs that are embedded in specified plugin JAR. Such nested JARs are built with https://github.com/embulk/embulk-plugins-gradle-plugin/pull/11. They are to be compliant with dependencies' licenses (such as "keep distribution's file structure as-is").
Can you have a look?
This change is trying to avoid impacts on existing behaviors (especially around Gem plugins).
JFYI: Nested JAR files and their `MANIFEST.MF` are structured like below:
```
Length     Date   Time    Name
--------    ----   ----    ----
0  09-25-17 19:39   META-INF/
284  09-25-17 19:39   META-INF/MANIFEST.MF
0  09-25-17 19:39   classpath/
514875  09-21-17 13:46   classpath/threetenbp-1.3.6.jar
57264  09-21-17 18:53   classpath/json-20170516.jar
0  09-21-17 14:28   org/
0  09-21-17 …
```
=> Load dependency JAR files embedded in plugin JAR

embulk-core/src/main/java/org/embulk/EmbulkRunner.java
`embulk guess` command with `-o` option makes invalid config file if the
output file is longer than the contents existent in the file before.
How to reproduce:
$ dd if=/dev/zero of=out.yml count=10
$ embulk guess seed.yml -o out.yml
=> Overwriting output file should truncate its contents first

embulk-cli/src/main/java/org/embulk/cli/EmbulkExample.java
@dmikurube Please take a look when you have a time.
Fix #804
Windows use `\` character in a path.
(ex: C:\Users\admin...)
It treats as an escape character when quoted by a double quote.
For avoiding it use a single quote instead.
Ref: YAML specification [7.3.2. Single-Quoted Style](http://yaml.org/spec/1.2/spec.html#id2788097)
=> Use single-quotes to quote path strings in YAML for Windows.

lib/embulk/guess/schema_guess.rb, test/guess/test_schema_guess.rb
`N` is doubly defined. It should be `F`.
=> Fix typo in FALSE_STRINGS and add their test

embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java
@muga Sorry, it had another typo...
=> Fix typo of a parameter name in Javadoc in PluginClassLoader

embulk-docs/build.gradle
Uploading embulk-docs/ to embulk.org is still failing because of that old lasagna.org problem... https://travis-ci.org/embulk/embulk/jobs/288866021#L1137
=> Workaround against the rubygems.lasagna.io problem in embulk-docs/

embulk-core/src/main/java/org/embulk/spi/util/dynamic/AbstractDynamicColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/SkipColumnSetter.java, lib/embulk/page_builder.rb
@muga As a part of un-JRuby-ing, deprecating `AbstractDynamicColumnSetter#setRubyObject`. Can you have a look?
(I think this is used almost only from Ruby's `page_builder`. As its `set` is re-implemented in Ruby, I believe it should be fine...)
=> Deprecate org.embulk.spi.util.dynamic.AbstractDynamicColumnSetter#setRubyObject

embulk-core/src/main/java/org/embulk/spi/json/RubyValueApi.java, lib/embulk/schema.rb
@muga Next to #800, deprecating `RubyValueApi` which is static methods to convert MessagePack `Value`s and Ruby objects.
I couldn't find OSS plugins calling these static methods at least by Google.
It expects #800 as `org.embulk.spi.util.dynamic.AbstractDynamicColumnSetter#setRubyObject` is calling `RubyValueApi`.
=> Deprecate org.embulk.spi.json.RubyValueApi

embulk-core/src/main/java/org/embulk/spi/time/TimestampFormat.java
`TimestampFormat`'s `newFormatter` and `newParser` have been implemented with `TimestampFormatter.FormatterTask` and `TimestampParser.ParserTask` which have been deprecated for a long time.
=> Deprecate newFormatter with TimestampFormatter.FormatterTask and newParser with TimestampParser.ParserTask in TimestampFormat

embulk-core/src/main/java/org/embulk/spi/util/PagePrinter.java, embulk-standards/src/main/java/org/embulk/standards/StdoutOutputPlugin.java
`org.embulk.spi.util.PagePrinter` has been implemented with deprecated `TimestampFormatter.FormatterTask`... The constructor is also to be deprecated.
=> Deprecate constructor of org.embulk.spi.util.PagePrinter with TimestampFormatter.FormatterTask

embulk-core/src/main/java/org/embulk/spi/time/JRubyTimeParserHelper.java, embulk-core/src/main/java/org/embulk/spi/time/JRubyTimeParserHelperFactory.java, lib/embulk/java/bootstrap.rb, lib/embulk/java/time_helper.rb
@muga Let me revert this for the time being.
I found that we got errors like below after merging #813 :
```
org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `parse' for Time:Class
```
```
org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `strptime' for Time:Class
```
It looks like that just replacing `require 'embulk/java/time_helper'` to `require 'time'` would fix the problem. The replacement fixed my cases at least. But, let me postpone this to the next next release (expected v0.8.37).
v0.8.36 already has many changes, then I don't want to include suspicious changes in v0.8.36.
=> Revert "Merge pull request #813 from embulk/remove-dead-code-in-old-datetime-parser"

embulk-core/src/main/java/org/embulk/spi/time/Timestamp.java, lib/embulk/schema.rb
@muga I guess it'd be the final deprecation around `org.jruby`. Can you have a look?
=> Deprecate org.embulk.spi.time.Timestamp's getRubyTime and fromRubyTime

embulk-core/src/test/java/org/embulk/spi/time/TestTimestampParser.java
@muga Can you have a look? It adds tests for `TimestampParser` in the Java world.
Some test cases are disabled because of #834 -- `%j` is not considered in `TimestampParser`.
=> Add TestTimestampParser, direct tests for org.embulk.spi.time.TimestampParser

test/vanilla/time/test_timestamp_parser.rb
@muga Adding tests for `TimestampParser`, not just our Ruby-compatible time parser (jruby-strptime), by comparing the result epoch time with Ruby's `strptime`.
It's now ready. Can you have a look?
Jfyi, the test has commented-out cases where `TimestampParser` cannot parse `sec` == 60 (leap second) correctly. We may want to fix it later, but I think it should be acceptable for the time being.
=> Add Ruby tests with TimestampParser to compare with Ruby's strptime

embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampParser.java
@muga Fixing #834 ... supporting yday (`%j`) in `TimestampParser`. Can you have a look?
=> Process yday (day of the year) in TimestampParser as well: Fix #834

embulk-jruby-strptime/src/main/java/org/embulk/spi/time/StrptimeFormat.java, embulk-jruby-strptime/src/main/java/org/embulk/spi/time/StrptimeParser.java, embulk-jruby-strptime/src/main/java/org/embulk/spi/time/StrptimeToken.java
@muga Not affecting any behavior, though.
`%Q` looks actually "milliseconds" in Ruby's documents, and even in our implementation behavior. But, the constant name and the comments are written it's "microseconds"...
https://docs.ruby-lang.org/en/2.4.0/DateTime.html#method-i-strftime
It might come from JRuby's long-lived code:
https://github.com/jruby/jruby/blame/a41e22b8f44114fc2783798cd22c76c47876bc51/core/src/main/java/org/jruby/util/RubyDateFormatter.java#L144-L146
=> Name and comment StrptimeParser's %Q as milliseconds, not microseconds

embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampParser.java
@muga Can you have a look? I guess it's the last fix on `TimestampParser`.
=> Fix nanoseconds set by StrptimeParser's %Q

embulk-docs/src/built-in.rst
A required option is not "parsers" but "parser".
=> Replaced "parsers" option in configuration documentation to "parser"

README.md
http://www.embulk.org/docs/recipe/scheduled-csv-load-to-elasticsearch-kibana4.html is 404.
=> Update use cases link

build.gradle, lib/embulk/version.rb
@muga @sakama Considering to go into v0.9 series development after v0.8.38 is released (#851). Can you have a look?
=> Bump master to 0.9.0-SNAPSHOT

build.gradle, embulk-core/build.gradle, test/monkey_strptime/run-test.rb, test/vanilla/run-test.rb
Embedded dependency gems (`msgpack-java`, `liquid`, and `bundler` for the time being) are located under `gems/` and `specifications/` in the embulk-core jar file.
```
META-INF/
...
org/
embulk/
*.class
...
gems/
bundler-1.10.6/
...
liquid-4.0.0/
...
msgpack-java-1.1.0/
...
specifications/
bundler-1.10.6.gemspec
msgpack-java-1.1.0.gemspec
liquid-4.0.0.gemspec
```
With the location, developers and users can load embulk "like gem" in JRuby by
```
require `./embulk-core-....jar`
require `msgpack`
```
Eventually, Embulk's Ruby code would be located like this as well.
@sakama Can you have a look? (Cc: @muga)
=> Locate embedded dependency gems under gems/ in Embulk .jar file

embulk-cli/src/main/resources/new_bundle_templates/Gemfile
We will no longer release `embulk.gem` from the v0.9 series. Embulk's `-b` option however needed to install `embulk.gem` as its dependency.
`embulk.jar`, the only distribution of Embulk v0.9+, will contain gem's structure in itself. `Gemfile` of bundle directories won't need Embulk versions to refer the embedded embulk gem.
@sakama (Cc: @muga) Can you have a look?
----
Bundler (for -b) can find required gems in embulk.jar by the 3 preceding fixes.
Gemfile in "bundle directories" would refer embulk's gem embedded in jar.
Its version should be automatically resolved, not specified in Gemfile.
The preceding fixes:
1. Embulk's Ruby code is now embedded as a gem in embulk.jar by #856.
Standalone embulk.gem is no longer released.
2. Other dependency gems are also embedded in embulk.jar as gems …
=> Unspecify embulk gem's version in Gemfile template of bundle directories

build.gradle, embulk-core/src/main/ruby/embulk/version.rb
We'd like to have a version declaration just in one place! This PR automatically generates Ruby version string (`lib/embulk/verison.rb`) from Java version strting (`org.embulk.EmbulkVersion.VERSION`).
@sakama (Cc: @muga) Can you have a look?
=> Make Ruby Embulk::VERSION based on Java org.embulk.EmbulkVersion.VERSION

embulk-core/build.gradle, embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java
@muga @sakama Upgrading the embedded bundler to the latest.
`Bundler.load.setup_environment` was removed in 1.12.0, so calling `Bundler::SharedHelpers.set_bundle_environment` instead.
=> Upgrade embedded Bundler to 1.16.0

embulk-core/src/main/java/org/embulk/spi/time/TimestampFormat.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampParser.java, embulk-core/src/test/ruby/vanilla/time/test_timestamp_parser.rb
It was a mistake in #840. I thought there were no duplications between Ruby's and Joda-Time's, but duplicated actually.
https://gist.github.com/dmikurube/c62ea8ebfbb5c41c0dc21584350bb274
If the given time zone is one of "CET", "EET", "Egypt", "Iran", "MET", or "WET", Joda-Time takes care of summer time, but Ruby's does not. It means that Joda-Time considers "CET" to be in summer time (+2) if the date is in a summer time period. Ruby's just always considers "CET" as a fixed offset of an hour (+1).
I'll backport this into v0.8 series, and release v0.8.39.
=> Parse time zones in Ruby-style in lower priority than Joda-Time

embulk-core/src/main/java/org/embulk/EmbulkSetup.java, embulk-core/src/test/ruby/helper.rb
The JRuby instance for plugins is now operated only in `JRubyScriptingModule`. We can use non-global JRuby instance.
=> Stop using the global JRuby runtime when executed through CLI

embulk-cli/src/main/java/org/embulk/cli/EmbulkRun.java
@muga @sakama Small change. Let's use `java.time` more, and Joda-Time less. Can you have a look?
=> Use java.time classes instead of Joda-Time in embulk-cli

embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java
Refactoring in addition to #869. (Sorry for a kind of duplicated work.)
It refactors Gem and Bundler variable settings with more log messages added. It is also preparation for #871, which starts to use embulk.jar's location to find plugin gems.
=> Refactor setting Gem and Bundler variables in JRubyScriptingModule

embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java
I'm thinking to move the install directory of gem plugins to `~/.embulk/lib/gem` from `~/.embulk/jruby/<ruby-version>` (e.g. `~/.embulk/jruby/2.3.0` for JRuby 9.1.13.0). AFAIU, the directory with Ruby version has made more confusions than benefits on users when we upgrade JRuby. When JRuby of Embulk is upgraded, users need to re-install their plugins.
The v0.9 jump is a good chance to remove this for the future.
@muga @sakama Can I have your opinions? I might have overlooked kinds of problems or dependencies on the Ruby version.
=> Move the default install directory of gem plugins to ~/.embulk/lib/gem without Ruby versions

embulk-core/src/main/java/org/embulk/plugin/BuiltinPluginSourceModule.java
I've just found a problem around guess (#876), and this PR workarounds the problem.
----
I'm actually not 100% sure whether `BuiltinPluginSourceModule` is the right place to add this workaround. But I thought adding a new Guice Module was too much, and `BuiltinPluginSourceModule` could fit the purpose as it's binding a kind of dummy as a default builtin.
=> Allow no guess plugins registered in embulk-core: Fix #876

embulk-core/src/main/java/org/embulk/jruby/JRubyInvokeFailedException.java, embulk-core/src/main/java/org/embulk/jruby/JRubyNotLoadedException.java, embulk-core/src/main/java/org/embulk/jruby/JRubyPluginSource.java, embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java, embulk-core/src/main/java/org/embulk/jruby/ScriptingContainerDelegate.java
It comes after #872.
As in its Javadoc, this trick enables Embulk:
* To load a JRuby runtime (jruby-complete-...jar) specified at runtime out of embulk-...jar.
* To switch versions of JRuby without releasing or repackaging.
* To distribute Embulk without JRuby runtimes embedded.
Releasing without JRuby runtimes would not be done very soon. But, specifying other JRuby runtimes would sometimes help users.
=> Indirect JRuby calls not to require JRuby classes directly

embulk-core/src/main/java/org/embulk/EmbulkRunner.java, embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java, embulk-standards/src/main/java/org/embulk/standards/JsonParserPlugin.java
After merging embulk-cli to embulk-core (#883), stopping to use JRuby directly from CLI, and embulk-standards.
=> Eliminate "import org.jruby..." from CLI and embulk-standards

embulk-core/src/main/java/org/embulk/spi/time/Timestamp.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampSerDe.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestamp.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampParser.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampSerDe.java
Just refactoring. Using `java.time.Instant` in `Timestamp`, instead of pairs of epoch seconds and milliseconds. Their interface is almost the same.
At the same time, moving `Timestamp.fromString` into `TimestampSerDe`, which was package-private, and used only from `TimestampSerDe`.
@sakama @muga Can you take a look?
=> Use java.time.Instant in org.embulk.spi.time.Timestamp

embulk-core/src/main/java/org/embulk/config/TaskInvocationHandler.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatter.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java, embulk-core/src/main/java/org/embulk/spi/util/DynamicPageBuilder.java, embulk-core/src/main/java/org/embulk/spi/util/Inputs.java, embulk-core/src/main/ruby/embulk/schema.rb
Users of TimestampFormatter, TimestampParser, and DynamicPageBuidler had to use `org.joda.time.DateTimeZone` since their `Task` subclasses had `DateTimeZone`.
This change enables to intercept its `String` representation, and to interpret the time zone ID representation by themselves.
It introduces a hack in `TaskInvocationHandler` to call default implementations in `Task` interfaces.
=> Indirect org.joda.time.DateTimeZone in config Tasks

embulk-core/src/main/java/org/embulk/spi/time/TimeZoneIds.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampFormat.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimeZoneIds.java
Moving `TimestampFormat.parseDateTimeZone` to a new class `TimeZoneIds`, and adding a new method to parse a time zone ID string into `java.time.ZoneId`.
@sakama @muga Can you PTAL?
=> Implement a time zone parser for java.time.ZoneId

embulk-core/src/main/java/org/embulk/spi/time/RubyTimeParsed.java, embulk-core/src/main/java/org/embulk/spi/time/RubyTimeParser.java
Some more refactoring in `RubyTimeParsed` so that it can use `RubyTimeParsed`'s fields directly in `toTimestamp` and `asMapLikeRubyHash` without converting getters.
=> Refactor fields of RubyTimeParsed

embulk-core/src/main/java/org/embulk/spi/time/RubyTimeParsed.java, embulk-core/src/main/java/org/embulk/spi/time/TimeParsed.java, embulk-core/src/main/java/org/embulk/spi/time/TimeZoneIds.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampFormat.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimeZoneIds.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampParser.java
This comes after #893 and #894. It deprecates and reduces the usage of `org.joda.time.DateTimeZone`.
=> Reimplement TimestampParser, TimeParsed, and RubyTimeParsed with java.time.ZoneId

embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java
Simply cleaning up. Can you have a look, @muga @sakama?
=> Cleanup TimestampParser orders and styles with reimplementing defaultDate with java.time

embulk-core/src/main/java/org/embulk/spi/time/RubyTimeParsed.java, embulk-core/src/main/java/org/embulk/spi/time/TimeParsed.java
They don't need to be `public`...
=> Make TimeParsed and RubyTimeParsed package-private

embulk-core/src/main/java/org/embulk/spi/time/DateTimeZoneSerDe.java, embulk-core/src/main/java/org/embulk/spi/time/TimeZoneIds.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatter.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java, embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnSetterFactory.java, embulk-core/src/main/java/org/embulk/spi/util/DynamicPageBuilder.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/SkipColumnSetter.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampParser.java, embulk-standards/src/test/java/org/embulk/standards/TestCsvParserPlugin.java
Cleanups, comments, renames, and annotations around `TimestampParser` and `org.joda.time.DateTimeZone`. Can you have a look?
=> Cleanup various parts around TimestampParser and org.joda.time.DateTimeZone

.github/CONTRIBUTING.md
@muga @sakama Before Embulk v0.9, we'd like to have a contribution guideline. Can you have a look?
=> Add an initial contribution guideline (CONTRIBUTING.md)

embulk-core/src/main/java/org/embulk/spi/time/TimestampFormat.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatter.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java, embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnSetterFactory.java, embulk-core/src/main/java/org/embulk/spi/util/DynamicPageBuilder.java
`org.embulk.spi.time.TimestampFormat` is essentially just a `String`. We don't need it eventually.
=> Deprecate org.embulk.spi.time.TimestampFormat

embulk-core/src/main/java/org/embulk/spi/time/LegacyRubyTimeParsed.java, embulk-core/src/main/java/org/embulk/spi/time/RubyTimeParsed.java, embulk-core/src/main/java/org/embulk/spi/time/RubyTimeParser.java, embulk-core/src/main/java/org/embulk/spi/time/TimeParsed.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampParserLegacy.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampFormatterParser.java
It's preparation for adding `"java:"` and `"ruby:"` timestamp formats. Can you have a look? @muga @sakama
=> Split TimestampParser into TimestampParserLegacy

embulk-core/src/main/java/org/embulk/spi/unit/LocalFileSerDe.java
`org.embulk.spi.unit.LocalFileSerDe$LocalFileDeserializer` refers a Java property `java.io.tmpdir`, but that is never used. Let's remove that.
@sakama Can you have a look? (Cc: @muga)
=> Remove unnecessary reference of a Java property "java.io.tmpdir"

embulk-core/src/main/java/org/embulk/spi/time/TimeZoneIds.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampParseException.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampParserJava.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampParser.java
It additionally accepts new-style timestamp formats prefixed by `"java:"` and composed from `java.time.DateTimeFormatter`'s format style, such as `"java:EEE, dd MMM uuuu HH:mm:ss ZZZ"`. Some cases could not be supported in the Java-version parser, though.
The spec is at:
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#patterns
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatterBuilder.html#appendPattern-java.lang.String-
@muga @sakama What do you think?
=> Add Java-style ("java:") timestamp format to parse timestamps

embulk-core/src/main/java/org/embulk/spi/time/RubyTimeParsed.java, embulk-core/src/main/java/org/embulk/spi/time/TimeZoneIds.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampParserRuby.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampParser.java
The legacy `TimestampParser` has parsed into components by `DateTime._strptime`, partially followed by `DateTime.strptime`'s manner to resolve it as a `DateTime` object, partially with Joda-Time's `DateTimeZone`, and so on... It was confusing. (See #860.)
This, the new Ruby-style timestamp parser, follows `Time.strptime` of `Time`, which is Ruby's more accepted standard-ish time class. `Time.strptime` has simple and reasonable time zone handling only with numeric time zones, and a few fixed-offset short IDs used in some RFCs.
We can refer Ruby's `Time.strptime` documentation straightforward to describe the parser's behavior.
@muga @sakama What do you think?
=> Add Ruby-style ("ruby:") timestamp format to parse timestamps in the compatible way with Time.strptime

embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatter.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatterRuby.java, embulk-core/src/main/java/org/embulk/spi/util/Timestamps.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampFormatter.java
Accepting "ruby:" timestamp formats in `TimestampFormatter` in addition to `TimestampParser` at #905, simply for consistency.
There are not so many differences in formatter, not like parser.
@muga @sakama Can you have a look? More test cases would be added sooner in other PRs.
=> Add Ruby-style ("ruby:") timestamp format to format timestamps in the compatible way with Time.strptime

embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatter.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatterJava.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampFormatter.java
After #906, adding Java-style "`java:`" timestamp formatter with `java.time`.
@muga @sakama Can you have a look? More test cases would be added sooner in other PRs.
=> Add Java-style ("java:") timestamp format to format timestamps with java.time

docs/design/README.md, docs/design/external_variables.md
Adding internal design documents in the repository. It is nicer to be in the repos so that their revisions are synchronized with the code changes. They'll be separate from `embulk-docs` since they're more Embulk-internal documents, not for embulk.org/docs.
@sakama @muga What do you think?
=> Add Embulk design docs in Markdown under docs/design

build.gradle
The `setVersion` task is not needed. Let's remove this. @muga @sakama
=> Remove the "setVersion" task in build.gradle

build.gradle
Forgot this... Let's upgrade the embedded JRuby in Embulk 0.9.0 to the latest 9.1.15.0. Can you have a look? @sakama @muga
=> Upgrade the embedded JRuby to 9.1.15.0

build.gradle
Once JRuby was upgraded to 9.1.15.0, it turned out that the Gradle `shadowJar` task failed. Found that upgrading the `shadow` Gradle plugin fixes the issue.
=> Upgrade shadow Gradle plugin to 2.0.2

embulk-docs/src/release.rst, embulk-docs/src/release/release-0.8.39.rst
Salvaging the release document of branched hotfix v0.8.39: https://github.com/embulk/embulk/releases/tag/v0.8.39
=> Pick up release document of hotfix v0.8.39

embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnSetterFactory.java, embulk-core/src/main/java/org/embulk/spi/util/PagePrinter.java, embulk-core/src/main/java/org/embulk/spi/util/Timestamps.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampFormatterParser.java, embulk-standards/src/main/java/org/embulk/standards/StdoutOutputPlugin.java
The use of `TimestampFormatter.of` and `TimestampParser.of` was not thorough. This PR replaces almost all the constructor calls to `.of`.
=> Use TimestampFormatter.of and TimestampParser.of instead of their constructors

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java
This tries to address #882 -- logging Embulk's version when executing some methods of `EmbulkEmbed`. Can you have a look? @muga @sakama
The execution log would be like below:
```
2018-01-25 16:07:53.768 +0900 [INFO] (main): BUNDLE_GEMFILE is being set: "/.../Gemfile"
2018-01-25 16:07:53.771 +0900 [INFO] (main): Gem's home and path are being cleared.
2018-01-25 16:07:56.048 +0900 [INFO] (main): Started Embulk v0.9.0-SNAPSHOT
2018-01-25 16:07:56.139 +0900 [INFO] (0001:transaction): Loaded plugin embulk-input-inline (0.1.0)
```
=> Log Embulk core's version when executing EmbulkEmbed: Fix #882

build.gradle, embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/EmbulkService.java, embulk-core/src/main/java/org/embulk/config/CommitReport.java, embulk-core/src/main/java/org/embulk/config/ConfigLoader.java, embulk-core/src/main/java/org/embulk/config/DataSourceImpl.java, embulk-core/src/main/java/org/embulk/config/DataSourceSerDe.java, embulk-core/src/main/java/org/embulk/exec/ResumeState.java, embulk-core/src/main/java/org/embulk/plugin/compat/InputPluginWrapper.java, embulk-core/src/main/java/org/embulk/plugin/compat/TransactionalFileInputWrapper.java, embulk-core/src/main/java/org/embulk/plugin/compat/TransactionalFileOutputWrapper.java, embulk-core/src/main/java/org/embulk/plugin/compat/TransactionalPageOutputWrapper.java, embulk-core/src/main/java/org/embulk/spi/ColumnConfig.java, embulk-core/src/main/java/org/embulk/spi/Exec.java, embulk-core/src/main/java/org/embulk/spi/ExecSession.java, embulk-core/src/main/java/org/embulk/spi/TaskState.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatterRuby.java, embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnSetterFactory.java, embulk-core/src/main/java/org/embulk/spi/util/PagePrinter.java, embulk-standards/src/test/java/org/embulk/standards/TestCsvFormatterPlugin.java
@sakama @muga We're going to deprecate old unused things explicitly by the chance of v0.9. Do you have any other candidates to deprecate?
This PR enables the `-Xlint:deprecation` check, and annotates `@SuppressWarnings("deprecation")` explicitly, and comments with GitHub Issues, as well.
=> Deprecate new things to be deprecated, and suppress uses of deprecated things

docs/design/deprecations.md
Adding another internal document to summarize `@Deprecated` in the Embulk core.
Can you have a look? @muga @sakama (Not in a hurry.)
=> Add an internal design document on deprecations

embulk-core/src/main/java/org/embulk/exec/GuessExecutor.java, embulk-docs/src/release/release-0.9.0.rst
This PR enables customizing byte size of sample buffer that `GuessParserPlugin` can tries to read. In #609, `guess_sample_buffer_bytes` option was introduced to custom byte size of sample buffer but, in the case of #788, the option could not work expectedly. #609 enables configuring sample buffer bytes for `GuessExecutor` but, `GuessParserPlugin` still tries to read default bytes 32KB that is not configurable by #609. This PR could configure for the sample buffer bytes. 
In this PR, to pass the custom value of `guess_sample_buffer_bytes` option in `GuessExecutor` to `GuessParserPlugin`, `parser_sample_buffer_bytes` option is introduced. Basically `parser_sample_buffer_bytes` value should be same as `guess_sample_buffer_bytes`. 
It fixes https://github.com/embulk/embulk/issues/788.
=> Customize byte size of sample buffer that GuessParserPlugin tries to read

build.gradle
v0.9.0 has been released!
Then, we're bumping up the master version to 0.9.1-SNAPSHOT. @muga @sakama
=> Bump master to 0.9.1-SNAPSHOT

embulk-core/src/main/java/org/embulk/jruby/ScriptingContainerDelegate.java
It was the cause of #943. JRuby's `InvokeFailedException` can be thrown inside `InvocationTargetException`.
Can you have a look? @muga @sakama 
The class `ScriptingContainerDelegate` intentionally has some code clones so that Exceptions are explicitly created at the error points, not in utility methods.
=> Figure out org.jruby.embed.InvokeFailedException from InvocationTargetException: Fix #943

config/checkstyle/README.md, config/checkstyle/checkstyle.xml, embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnSetterFactory.java
Unused imports have not been checked by checkstyle. Let's check it -- can you have a look, @sakama?
=> Add checkstyle rule: UnusedImports

embulk-core/src/main/java/org/embulk/config/TaskInvocationHandler.java, embulk-core/src/main/java/org/embulk/config/TaskSerDe.java, embulk-core/src/test/java/org/embulk/config/TestConfigSource.java
This PR is a trial to fix #949, but it changes the behavior of `@Config`. It allows to have duplicated configuration names of `@Config("name")`.
Can I have your thoughts, @muga, @sakama?
=> Allow the same @Config configuration names: Fix #949

build.gradle, embulk-core/build.gradle, embulk-docs/build.gradle, embulk-standards/build.gradle
Using "from components.java" instead "artifact jar" is required in "publications" as well.
@sakama @muga I found that #953 was really tricky due to jruby-gradle-jar-plugin. This PR is a kind of revert of #776, and it is not the "right" fix, but at least we can release "correct" embulk-core jar with "correct" `pom.xml` with this workaround. We need to tackle the root cause of this later at #954.
What do you think?
=> Workaround empty dependencies in Maven artifacts' pom.xml: Fix #953

embulk-docs/src/release/release-0.9.1.rst, embulk-standards/src/main/java/org/embulk/standards/StdoutOutputPlugin.java
The default implementation has been introduced at: #931, and it's to be a kind of reverted as well in addition to #956.
=> Fix StdoutOutputPlugin broken by stopping @Config indirection by default implementation at: #956

embulk-core/src/main/java/org/embulk/config/TaskInvocationHandler.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatter.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java, embulk-core/src/main/java/org/embulk/spi/util/DynamicPageBuilder.java, embulk-standards/src/main/java/org/embulk/standards/StdoutOutputPlugin.java
The removal in v0.9.1 did not work perfectly as reported in #964... Reverting the removal would fix the issue.
=> Revert "Remove @Config indirection by default implemantations": Fix #964

embulk-core/src/main/java/org/embulk/jruby/JRubyPluginSource.java, embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java, embulk-core/src/main/java/org/embulk/plugin/PluginManager.java
Finally! It makes Embulk's startup really fast when JRuby-based plugins are not used.
It stops using Guice for `JRubyPluginSource`. Much controversy may exist over using DI (Guice), but  I think we may want to use Guice less in Embulk...
=> Load non-JRuby plugins without JRuby by deprioritizing JRuby-based plugins

embulk-docs/src/release.rst, embulk-docs/src/release/release-0.9.3.rst
@sakama @muga v0.9.3 will be #962 and #963 after #967 on v0.9.2. Can you have a look?
=> Prepare for v0.9.3

embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java
The banner has been printed for months since v0.8.*. I think it's time to remove the banner. What do you think? (Cc: @muga)
=> Remove notification banner of Embulk-announce mailing list

embulk-core/src/main/java/org/embulk/cli/EmbulkArguments.java
A small fix. Until v0.9.4, `embulk bundle --version` has been considered the same as `embulk --version`. We has had no way to show Bundler's versions. This PR fixes it.
Can you have a look?
=> Accept "embulk bundle --version" to run "bundle --version"

build.gradle
To see test outputs not only in report html pages, but also in standard output/error in real time.
=> Show test logs in standard streams

build.gradle
v0.9.5 has been released. Bumping up to v0.9.6-SNAPSHOT.
=> Bump to v0.9.6-SNAPSHOT

embulk-standards/src/main/java/org/embulk/standards/StdoutOutputPlugin.java
No any "important" feature, but I wanted this when checking a column-renaming feature...
Can you have a look? @sakama
=> Print column names in "stdout" output plugin

embulk-core/src/main/ruby/embulk/schema.rb
@sakama Can you have a look? Fixing #999.
=> Fix creating RubyTime from Java Timestamp in nanoseconds: Fix #999

embulk-core/build.gradle, embulk-core/src/main/java/org/embulk/config/TaskSerDe.java, embulk-core/src/main/java/org/embulk/exec/ExecModule.java, embulk-core/src/main/java/org/embulk/spi/ExecSession.java, embulk-core/src/main/java/org/embulk/spi/unit/ToString.java, embulk-core/src/test/java/org/embulk/config/TestConfigSource.java
Trying to start using `java.util.Optional` of Java 8, in addition to / instead of Guava's `Optional`.
Can you have a look, @sakama, and @muga as it's related to the basement portions?
In plugins' `Task` interfaces: both `java.util.Optional` and Guava's can be used like https://github.com/embulk/embulk/pull/997/commits/3e24e20dca5b57b441cd81bccb82f2df4eef8aab#diff-828bcc9d321473fc4a546d301ede851bR42 thanks to `Jdk8Module`.
In `TaskSerDe`: `TaskDeserializer` and `ConfigTaskDeserializer` should not be extended from plugins. The `protected` methods `getJsonKey` and `getDefaultJsonString` can be modified to return `java.util.Optional`.
In `ExecSession`: The only method using `Optional` is a `private` constructor, and only `ExecSession.Builder#build` is calling the constructor internally. It …
=> Use java.util.Optional more than com.google.common.base.Optional #1: Config and internal use

embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java, embulk-core/src/main/java/org/embulk/jruby/LazyScriptingContainerDelegate.java, embulk-core/src/main/java/org/embulk/jruby/ScriptingContainerDelegate.java, embulk-core/src/main/java/org/embulk/jruby/ScriptingContainerDelegateImpl.java
`org.jruby.embed.ScriptingContainer` could not be injected since v0.9.0 as `ScriptingContainer` was indirected by `ScriptingContainerDelegate`. But, found that some plugins are injecting it, especially in constructing instances. We at least need to keep this injectable for a while.
https://github.com/embulk/embulk-executor-mapreduce/blob/v0.4.0/embulk-executor-mapreduce/src/main/java/org/embulk/executor/mapreduce/MapReduceExecutor.java#L71
It will be dropped after a while -- maybe in the next major version.
=> Get org.jruby.embed.ScriptingContainer injectable again

build.gradle
v0.9.7 has been released. We're on v0.9.8-SNAPSHOT.
=> Bump to v0.9.8-SNAPSHOT

build.gradle, embulk-core/build.gradle, embulk-standards/build.gradle, embulk-test/build.gradle
Now, guice-bootstrap has been released in Maven Central: https://github.com/embulk/guice-bootstrap/pull/6 It's cleaner to use only `mavenCentral()` not depending on `jcenter()`.
=> Bump guice-bootstrap to v0.3.0 released in Maven Central

embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java, embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderFactory.java, embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderModule.java, embulk-core/src/main/java/org/embulk/plugin/jar/JarPluginLoader.java, embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginSource.java, embulk-core/src/test/java/org/embulk/plugin/jar/ExampleDependencyJar.java, embulk-core/src/test/java/org/embulk/plugin/jar/ExampleJarSpiV0.java, embulk-core/src/test/java/org/embulk/plugin/jar/TestJarPluginLoader.java
After finding "direct" dependencies in #1012, this PR actually loads the out-of-plugin-JAR dependencies. Can you have a look when you have time? @sakama (Cc: @muga) It's not in a hurry.
We may want better tests to load JARs, but that'd be out of `embulk-core`. We'd need much work for such tests.
I've at least confirmed that it successfully loads and runs specially-built `embulk-decoder-commons_compress` with external `org.apache.commons:commons-compress:1.13`.
=> Load a Maven-based plugin JAR with its "direct" dependencies

embulk-standards/src/test/java/org/embulk/standards/TestLocalFileInputPlugin.java
~~4692a47f32aa1c2d0c87258f29928fcdd0725320 is expected to fail on Windows.~~
@sakama @kamatama41 Can you take a look at these tests? It is to check the behavior before and after #1022 (from issue #1021). The behavior would change after #1022 is merged.
=> Add TestLocalFileInputPlugin

embulk-core/src/main/resources/org/embulk/plugin/template/java/build.gradle.vm
For the problem of could not push to RubyGems via embulk-plugins in below issues.
- upgrading com.github.jruby-gradle.base 0.1.5 to 1.5.0
```
bash-3.2$ ./gradlew gemPush
:compileJava UP-TO-DATE
:compileScala UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:classpath UP-TO-DATE
:gemspec UP-TO-DATE
:gem
Successfully built RubyGem
Name: embulk-parser-firebase_avro
Version: 0.1.3
File: embulk-parser-firebase_avro-0.1.3.gem
:gemPush
ERROR:  While executing gem ... (RuntimeError)
Can't find 'rubygems-update' in any repo. Check `gem source list`.
BUILD SUCCESSFUL
```
=> upgrade jruby-gradle plugin for embulk-plugin build.gradle template

embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java, embulk-standards/src/test/java/org/embulk/standards/TestLocalFileInputPlugin.java
For example, on MS Windows, the path_prefix is matched case-insensitively.
This PR has been already discussed on the issue #1021.
But you can drop this PR because of some reason.
Thanks.
=> Match with path_prefix in the proper way of the file system in LocalFileInputPlugin

embulk-core/src/main/java/org/embulk/spi/time/RubyTimeParsed.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampParser.java
Details are discussed in #1033.
Can you have a look? @sakama @kamatama41 Cc: @hiroyuki-sato
=> Add "sec_fraction" (fraction part) to "seconds" (epoch second) in parsing timestamps: Fix #1033

embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java, embulk-standards/src/test/java/org/embulk/standards/TestLocalFileInputPlugin.java
Follow-up to #1022.
As discussed in https://github.com/embulk/embulk/pull/1022#discussion_r198352790, the fix in #1022 was not perfect on Mac OS X, but we had no right ways to do that at that time.
After some investigation and experiments, I found that it is possible to be consistent with `PathMatcher`.
I wonder if we could apply this before releasing the next version 0.9.8. Can you have a look when you have time? @kamatama41 @sakama?
* This file has some more points that should be refactored, but they're left intentionally to focus on this change. I'll have another refactoring change later.
* This should be successful on TravisCI (Linux) and Appveyor (Windows), but the existing tests would fail on Mac OS X. I will have another commit in this PR to fix the tests.
=> Match local files in a consistent case-sensitivity manner even on Mac OSX: LocalFileInputPlugin

build.gradle
v0.9.8 is out. Next: v0.9.9-SNAPSHOT.
=> Bump to v0.9.9-SNAPSHOT

embulk-core/build.gradle, embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/EmbulkService.java
This is just refactoring. Can you have a look, @sakama @kamatama41 ?
* Move `EmbulkService.standardModuleList` to `EmbulkEmbed`
* Reduce usage of Guava
* Use Java 8 `java.util.function.Function` instead of Guava `Function`
----
This will use https://github.com/embulk/guice-bootstrap/pull/12.
=> Clean up EmbulkEmbed and EmbulkService

embulk-core/src/main/bat/selfrun.bat, embulk-core/src/main/sh/selfrun.sh, embulk-core/src/test/java/org/embulk/cli/SelfrunTest.java
Trying to run Embulk CLI with Java 9/10/11. Although the Embulk core (Java code) is not guaranteed to run with Java 9+, the selfrun scripts may help users to just try.
@sakama @kamatama41 Can you have a look? (Cc: @hiroyuki-sato)
=> Check Java versions from selfrun scripts: Fix #1020

embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampParser.java
We observed that CSV parser's `stop_on_invalid_record: false` was not working as intended when a parsed timestamp was invalid (non-existing) date/time, such as 2018-02-31.
It was because `DateTimeException` in creating a `*DateTime` instance was not caught and wrapped with `TimestampParseException` although `DateTimeParseException` was caught.
@sakama @kamatama41 Can you have a look?
=> Make stop_on_invalid_record effective for invalid dates such as 2018-02-31

embulk-core/src/main/bat/selfrun.bat, embulk-core/src/main/sh/selfrun.sh
This PR tries to fix #1056. Can you have a look, @sakama @kamatama41 @hiroyuki-sato ?
I assume that the names (`java` or `openjdk`) are lower-case alphabets. When we see other cases, we'll have another fix.
=> Check Java versions also for non-Oracle Java: Fix #1056

embulk-core/src/main/java/org/embulk/cli/EmbulkMigrate.java, embulk-core/src/main/java/org/embulk/cli/EmbulkNew.java, embulk-core/src/main/java/org/embulk/cli/EmbulkSelfUpdate.java
It fixes #1031. `PosixFilePermission` does not work for NTFS. File systems that can handle `PosixFilePermission` should return a `Set` including `"posix"` from `FileSystem#supportedFileAttributeViews`.
Can you have a look? @sakama @kamatama41
=> Do not use PosixFilePermission if unavailable: Fix #1031

README.md
Lately, Bintray (embulk binary hosted site) must use TLS 1.2 protocol.
And PowerShell doesn't use it by default. (use TLS1.1)
Fix #1029, #1028 issues.
=> PowerShell needs set TLS1.2 explicitly for connecting to Bintray

embulk-core/src/main/resources/org/embulk/plugin/template/java/build.gradle.vm
For #1061 
Open-ended dependency by using `>=` is not recommended by recent `gem` command.
So I made it narrower, only support rake v12.x.
What do you think about this? @sakama  @dmikurube
=> Support only rake 12.x on Java plugin's gemspec

embulk-core/src/main/java/org/embulk/spi/time/RubyTimeParsed.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampParser.java
Although we've merged #1052, it turned out that excess dates like `2018-02-31` were successfully parsed in Embulk v0.8 series and Ruby with overrunning into the next month. For example,
* `2018-02-31` is parsed into `2018-03-03`.
* `2016-02-31` is parsed into `2018-03-02`. (2016 is a leap year.)
* `2018-11-31` is parsed into `2018-12-01`.
For compatibility, we're going to follow this.
=> Parse excess dates like 2018-02-31 to overrun into the next month, in legacy and "ruby:" timestamp parsers

embulk-core/src/main/java/org/embulk/spi/time/RubyTimeParsed.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampParser.java
@sakama @kamatama41 As discussed directly,
* We once implement Ruby-compatible behavior with 2018-02-31 (to be 2018-03-03) in v0.9.10.
* Then, we will reject 2018-02-31 in later versions.
Toward this goal, I finally thought that we need this Ruby-compatible behavior only in the "legacy" timestamp parser. I'm reverting a change in #1067 on the "ruby:" timestamp parser.
Can you have a look?
----
JFYI: Embulk has three types of timestamp parsers since v0.9.0.
* Legacy: specified by `format: %Y-%m-...`. It aims to be compatible with Embulk v0.8.
* We have compatible behavior about 2018-02-31 in v0.9.10.
* We'll give up compatibility in later versions.
* Ruby: specified like `format: "ruby:%Y-%m-..."`. It aims to be more compliant with original Ruby's `Time.strptime`.
* We'll have different …
=> Parse exceeding dates like 2018-02-31 only in the legacy timestamp parser, not in the "ruby:" timestamp parser

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java
I think about removing the LifeCycle support from Embulk. That feature is never used as far is I know.
Before removing that feature, trying to message it to users to expect users report to us when they're using it.
@kamatama41 @sakama Can you have a look?
=> Warn if LifeCycleManager is in use

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-test/src/main/java/org/embulk/test/TestingEmbulk.java
After #1075, warning for `EmbulkEmbed#destroy` as well. The method is effective only for  `@PreDestroy` methods, but as mentioned in #1075, we don't observe actual usages of `@PreDestroy` around Embulk.
Can you have a look? @sakama @kamatama41
=> Warn for EmbulkEmbed#destroy

embulk-docs/push-gh-pages.sh
We'll update the repository to provide the https://www.embulk.org website.
@sakama @kamatama41 Can you have a look?
=> Update the repository for www.embulk.org site

embulk-docs/src/index.rst
Forgot that https://www.embulk.org/docs has been updated through CircleCI by compiling the `embulk-docs` files... https://github.com/embulk/www.embulk.org/pull/2 and https://github.com/embulk/www.embulk.org/pull/3 were overwritten.
Updating this `embulk-docs` here would update the document. Can you have a look? @sakama @kamatama41
=> Update links in docs to the list of plugins and the Input Plugin Development Guide

embulk-core/build.gradle, embulk-core/src/main/java/org/embulk/EmbulkEmbed.java
It actually removes guice-bootstrap's lifecycle annotation support as warned in #1075 and #1077. This is to be merged sometime after v0.9.12 is released with #1075 and #1077. If we have reports from users about #1075 or #1077, it will be reconsidered.
It is porting guice-bootstrap's [`Bootstrap`](https://github.com/embulk/guice-bootstrap/blob/v0.3.0/src/main/java/org/embulk/guice/Bootstrap.java) into `EmbulkEmbed.Bootstrap` with removing lifecycle annotation support.
@sakama @kamatama41 Can you have a look?
=> Use Guice directly without guice-bootstrap's lifecycle annotation support

embulk-core/src/main/java/org/embulk/cli/EmbulkSelfUpdate.java
see #806.
I fix selfupdate subcommand raises an exception on a Windows platform.
1. I changed "creating Path" process
`EmbulkSelfUpdate.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath()` to `EmbulkSelfUpdate.class.getProtectionDomain().getCodeSource().getLocation().toURI()`
(Using `Paths#get(URI)`)
2. I added "checking POSIX support" process for source jar file
Need support POSIX, in source and destination.
3. I added "create temp jar file, when selfupdate" process
Windows can not delete running jar file, So used temp jar file, when selfupdate.
=> Fix path extraction and POSIX permission handling in Selfupdate.

build.gradle, docs/design/README.md, docs/design/slf4j.md, embulk-core/build.gradle, embulk-core/src/main/java/org/embulk/cli/CliLogbackConfigurator.java, embulk-core/src/main/java/org/embulk/cli/EmbulkCommandLine.java, embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java, embulk-core/src/main/java/org/embulk/cli/Main.java, embulk-core/src/main/java/org/embulk/exec/BulkLoader.java, embulk-core/src/main/java/org/embulk/exec/LocalExecutorPlugin.java, embulk-core/src/main/java/org/embulk/exec/LoggerProvider.java, embulk-core/src/main/java/org/embulk/exec/PreviewExecutor.java, embulk-core/src/main/java/org/embulk/exec/SamplingParserPlugin.java, embulk-core/src/main/java/org/embulk/spi/Exec.java, embulk-core/src/main/java/org/embulk/spi/ExecSession.java, embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java, embulk-standards/src/main/java/org/embulk/standards/JsonParserPlugin.java, embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java, embulk-standards/src/main/java/org/embulk/standards/LocalFileOutputPlugin.java, embulk-standards/src/main/java/org/embulk/standards/RemoveColumnsFilterPlugin.java, embulk-standards/src/main/java/org/embulk/standards/RenameFilterPlugin.java, embulk-standards/src/test/java/org/embulk/standards/TestLocalFileInputPlugin.java
The details are described in `docs/design/slf4j.md`.
It won't be merged very soon for v0.9.12. It targets later versions such as v0.9.14 or v0.9.15 so that we can confirm the impact of this change before merging.
Can you have a look? @sakama @kamatama41
=> Silence LoggerProvider, and configure Logback only when Embulk is executed from CLI

build.gradle
After #1091, we have had no checks when releasing. This PR checks the Git `HEAD` is in a correct status before running `./gradlew release`.
@sakama @kamatama41 Can you have a look?
=> Check Git tag status to release

embulk-standards/src/main/java/org/embulk/standards/JsonParserPlugin.java, embulk-standards/src/test/java/org/embulk/standards/TestJsonParserPlugin.java
This is a refactoring to reduce Guava's dependencies, doesn't change any behavior.
In addition, This change might improve performance.
On my laptop (MBP 15 inch), parsing 10,000,000 records becomes 15 seconds faster than previous version.
```json
{"id": 1, "name": "user1", "sex": "male"}
{"id": 2, "name": "user2", "sex": "male"}
{"id": 3, "name": "user3", "sex": "male"}
{"id": 4, "name": "user4", "sex": "male"}
{"id": 5, "name": "user5", "sex": "male"}
...
{"id": 9999996, "name": "user9999996", "sex": "male"}
{"id": 9999997, "name": "user9999997", "sex": "male"}
{"id": 9999998, "name": "user9999998", "sex": "male"}
{"id": 9999999, "name": "user9999999", "sex": "male"}
{"id": 10000000, "name": "user10000000", "sex": "male"}
```
```yaml
in:
type: file
path_prefix: sample_jsonl10000000.json …
```
=> Use Java 8's stream and functional interfaces instead of Guava for JSON Parser plugin.

embulk-standards/src/main/java/org/embulk/standards/JsonParserPlugin.java, embulk-standards/src/test/java/org/embulk/standards/TestJsonParserPlugin.java
As we can parse only a specific JSON object within a JSON document by JsonParser since #1096, this option uses it.
Sample JSON
```json
{"a": {"b": 1}}
```
Config YAML
```yaml
in:
type: ...
parser:
type: json
__experimental__json_pointer_to_root: "/a"
```
Result
```
+-------------+
| record:json |
+-------------+
|     {"b":1} |
+-------------+
```
=> [Experimental] Add an option to point a specific value within a JSON document via Json Pointer expression.

embulk-core/src/main/java/org/embulk/spi/util/Timestamps.java, embulk-standards/src/main/java/org/embulk/standards/JsonParserPlugin.java, embulk-standards/src/test/java/org/embulk/standards/TestJsonParserPlugin.java
For #1102 
Sample JSON
```json
{"id": 1, "name": "Alice", "active": true, "created_at": "2019-01-12 01:23:45"}
```
Config YAML
```yaml
in:
type: ...
parser:
type: json
__experimental__columns:
- {name: name, type: string}   
- {name: active, type: boolean}   
- {name: created_at, type: timestamp, format: "%Y-%m-%d %H:%M:%S"}   
```
Result 
```
+---------+-------------+----------------+-------------------------+
| id:long | name:string | active:boolean |    created_at:timestamp |
+---------+-------------+----------------+-------------------------+
|       1 |       Alice |           true | 2019-01-12 01:23:45 UTC |
+---------+-------------+----------------+-------------------------+
```
=> [Experimental] Add an option to select a specific value in a record as an Embulk's column for JSON Parser plugin.

embulk-core/src/main/java/org/embulk/deps/EmbulkDependencyClassLoaders.java
One follow-up to #1085. #1085 unintentionally showed a warning `Dependencies for Maven are uninitialized. Expected to use classes loaded by the parent ClassLoader.` when using the self-contained JARs == in case of the all-in-one CLI package.
This PR fixes that.
@kamatama41 @sakama Can you have a look?
=> Do not warn Maven libraries uninitialized when using self-contained JARs

embulk-standards/src/main/java/org/embulk/standards/JsonParserPlugin.java, embulk-standards/src/test/java/org/embulk/standards/TestJsonParserPlugin.java
For #1102 and changes #1099's behavior.
Currently the parser can not detect invalid records that don't have the root pointer. 
For example, `embulk run` will be successful with the following inputs even if `stop_on_invalid_record: true`.  
```yaml
{"a": {"id": 1, "name": "Alice"}}
{"b": {"id": 2, "name": "Bob"}}
```
```yaml
in:
type: ...
parser:
type: json
__experimental__json_pointer_to_root: /a
stop_on_invalid_record: true
```
An error is raised caused by the invalid record `{"b": {"id": 2, "name": "Bob"}}`, but the record is skipped.
```
+-------------------------+
|             record:json |
+-------------------------+
| {"id":1,"name":"Alice"} |
+-------------------------+
```
Not directly applying JSON pointer to whole input JSON objects, then applying the pointer to each JSON …
=> Stop on invalid JSON which doesn't have given "JSON pointer to root"

embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java
The command line option `-R` no longer has general meanings. Replacing it to a description of only `-R--dev`.
=> Remove general help of `-R` options to have only `-R--dev`

embulk-standards/src/main/java/org/embulk/standards/JsonParserPlugin.java, embulk-standards/src/test/java/org/embulk/standards/TestJsonParserPlugin.java
For #1102 
After an internal discussion with @dmikurube and @sakama, we decided option names as following:
-  `__experimental__json_pointer_to_root` -> `root`
- `__experimental__flatten_json_array` -> `flatten_json_array`
- `__experimental__columns` -> `columns`
- `relative_json_pointer_from_root` -> `pointer`
=> Fix option names for JSON parser plugin's new features.

embulk-standards/src/main/java/org/embulk/standards/JsonParserPlugin.java, embulk-standards/src/test/java/org/embulk/standards/TestJsonParserPlugin.java
For #1102 
Currently the JSON parser plugin creates empty schema if the `columns` option is specified as empty array. This PR prevents it and use default schema with such a case.
=> [JSON Parser plugin] Use default schema if "columns" option is specified as empty array.

embulk-docs/src/built-in.rst, embulk-standards/src/main/java/org/embulk/standards/JsonParserPlugin.java, embulk-standards/src/test/java/org/embulk/standards/TestJsonParserPlugin.java
The configuration name `pointer` was the last remaining consideration when we discussed the names. What do you think: `element_at` instead?
```
columns:
- {name: name, type: string}
- {name: first_tag, type: string, element_at: "/tags/0"}
```
The noun "element" came from https://json.org/. It is enough explicit that it extracts a JSON element from that position. We can naturally extend it later like `element_at: "jsonpath:tags[0]"`.
What do you think, @kamatama41 @sakama ?
=> Use "element_at" instead of "pointer" in the built-in JSON parser plugin

embulk-core/build.gradle, embulk-core/src/main/java/org/embulk/cli/EmbulkNew.java, embulk-core/src/main/java/org/embulk/deps/cli/VelocityEngineDelegate.java, embulk-deps/cli/build.gradle, embulk-deps/cli/src/main/java/org/embulk/deps/cli/VelocityEngineDelegateImpl.java
Follow-up to #1123 to isolate Apache Velocity in addition. Velocity will be loaded by the same ClassLoader instance with Apache Commons CLI.
What do you think, @sakama ?
=> Load Apache Velocity in the sub ClassLoader

embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java, embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderFactory.java, embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderModule.java, embulk-core/src/main/java/org/embulk/plugin/jar/JarPluginLoader.java, embulk-core/src/test/java/org/embulk/plugin/jar/TestJarPluginLoader.java, test-helpers/build.gradle
For #1110 
All codes that relate to`embeddedJarPathsInNestedJar` in `PluginClassLoader` are removed.
=> Unsupport nested-JAR style JAR plugins.

embulk-core/build.gradle, embulk-standards/build.gradle
SLF4J logs have not been displayed during tests. It adds Logback to `testCompile` to make them displayed.
=> Test with Logback so that logs can be checked

embulk-standards/src/main/java/org/embulk/standards/StandardPluginExtension.java, embulk-standards/src/main/java/org/embulk/standards/StandardPluginModule.java
For example, consider we run :
```
embulk run -X standards.output.stdout.disabled=true test.yml
```
If `test.yml` contains `out: type: stdout`, it fails with an error :
```
org.embulk.config.ConfigException: OutputPlugin 'stdout' is not found.
```
=> Provide system config options to disable selected standard plugins

embulk-core/src/main/java/org/embulk/jruby/JRubyInitializer.java, embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java, embulk-core/src/main/java/org/embulk/jruby/LazyScriptingContainerDelegate.java, embulk-core/src/main/java/org/embulk/jruby/ScriptingContainerDelegate.java, embulk-core/src/main/java/org/embulk/jruby/ScriptingContainerDelegateImpl.java, embulk-core/src/test/java/org/embulk/jruby/TestJRubyInitializer.java
Allowing Embulk to configure `GEM_PATH`, in addition to `GEM_HOME`, through system configs.
https://stackoverflow.com/questions/11277227/whats-the-difference-between-gem-home-and-gem-path
By configuring `GEM_PATH`, users can look for Embulk plugins from multiple Gem directories.
@sakama Can you have a look when you have time?
=> Process a new system config "gem_path", to work the same way as GEM_PATH

build.gradle
`v0.9.17` is out. Next `v0.9.18`!
=> Bump up to v0.9.18

build.gradle, embulk-core/build.gradle, embulk-core/src/main/java/org/embulk/spi/Buffer.java, embulk-core/src/main/java/org/embulk/spi/type/AbstractType.java, embulk-core/src/main/resources/embulk/parent_first_packages.properties, embulk-core/src/main/resources/embulk/parent_first_resources.properties
FindBugs is no longer maintained.
https://mailman.cs.umd.edu/pipermail/findbugs-discuss/2016-November/004321.html
And we have had unnecessary dependency on `com.google.code.findbugs:annotations:3.0.0` for FindBugs.
We're not effectively using FindBugs. It's time to abandon FindBugs. We may enable SpotBugs instead in the future.
=> Abandon FindBugs

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/EmbulkService.java, embulk-core/src/main/java/org/embulk/EmbulkSetup.java
Retry of #1038 in a bit different manner. We don't need to upgrade Guice after #1078. We can do this kind of refactoring more safely.
* Reorder methods and fields.
* Set system config through JSON-formatted `String` in `Bootstrap`. No use of "System config loader" outside.
* Move `EmbulkService.standardModuleList` to `EmbulkEmbed`
* Reduce usage of Guava
* Use Java 8 `java.util.function.Function` instead of Guava `Function`
* Use statically-initialized `Logger`
=> Cleanup EmbulkEmbed and EmbulkService

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/exec/ExecModule.java, embulk-core/src/main/java/org/embulk/exec/PooledBufferAllocator.java, embulk-core/src/main/java/org/embulk/spi/unit/ByteSize.java, embulk-core/src/test/java/org/embulk/EmbulkTestRuntime.java, embulk-core/src/test/java/org/embulk/spi/unit/TestByteSize.java
Cleaning up `Buffer`, `BufferAllocator`, and `PooledBufferAllocator`. Along with it,
* Reorder methods and fields.
* `PooledBufferAllocator` to be instantiated without Guice and system config.
* Deprecate `ByteSize`, which has been used only in `PooledBufferAllocator`. No plugins using this class are found.
* Use `BigDecimal` to parse byte size strings, instead of `double`.
* Reduce usage of Guava.
@sakama Can you have a look when you have time? (Not in a hurry)
=> Cleanup Buffer, BufferAllocator, and PooledBufferAllocator, and deprecate ByteSize

embulk-core/src/main/java/org/embulk/exec/PooledBufferAllocator.java
Follow-up to #1141. `PooledBufferAllocator` does not need to be public.
=> Make PooledBufferAllocator package-private

embulk-deps/maven/build.gradle
Upgrading Apache Maven (as Java library) to the latest 3.6.1.
Note that Eclipse Aether is now migrated to Apache and named as Apache Maven Resolver.
http://maven.40175.n5.nabble.com/Formerly-Aether-now-Maven-Artifact-Resolver-documentation-td5900927.html
=> Upgrade Apache Maven and maven-resolver-provider to 3.6.1 in embulk-deps-maven

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java
Was a bug. `EmbulkEmbed.Bootstrap.setSystemConfig(ConfigSource)` was totally not working. (But it was not used in `embulk-core`. `embulk-core` uses `setSystemConfigFromJson` instead.)
Fixing the bug, and letting `setSystemConfigFromJson` to call `setSystemConfig` internally.
=> Fix EmbulkEmbed.Bootstrap.setSystemConfig, which was not working

embulk-deps/maven/src/main/java/org/embulk/deps/maven/MavenArtifactFinderImpl.java
By #1015, Maven-based plugins are loaded only with its "direct" dependency libraries, without its "transitive" dependencies ( == dependencies of dependencies).
This PR restricts the load only to `compile` and `runtime` scope. It will work with Embulk plugins built with the updated Gradle plugin: https://github.com/embulk/gradle-embulk-plugins/pull/24
----
@sakama Can you have a look? (No hurry.)
I plan to release v0.9.18 after this PR. The date may be a bit later, though.
=> Load Maven dependencies only of "compile" and "runtime" scopes

.travis.yml
I got a CI failure on Travis CI
https://travis-ci.org/embulk/embulk/builds/569220317
```bash
Installing oraclejdk8
$ export JAVA_HOME=~/oraclejdk8
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2019-07-17
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
Your build has been stopped.
```
It seems install process is asking us to agree with a license agreement or something.
Why don't you use OpenJDK8 instead …
=> Use OpenJDK8 for a CI environment to Travis CI failure

embulk-standards/src/main/java/org/embulk/standards/JsonParserPlugin.java, embulk-standards/src/test/java/org/embulk/standards/TestJsonParserPlugin.java
I found that bundled JsonParser plugin always throws TimestampParseException when JSON data contains invalid timestamp value.
The problem happens with both of `stop_on_invalid_record: true/false`
This PR fixes the problem.
* when `stop_on_invalid_record: true`
`DataException` is thrown
* when `stop_on_invalid_record: false`
Warn log is shown in cmdout but no exception is thrown 
Below Exception is always thrown regardless of `stop_on_invalid_record` value
```bash
org.embulk.exec.PartialExecutionException: org.embulk.spi.time.TimestampParseException: text is null or empty string.
at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:566)
at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
at …
```
=> Bundled JsonParser plugin throws TimestampParseException when JSON data contains invalid timestamp value

embulk-docs/push-gh-pages.sh
@shroman Can you have a look?
We had had maintained the entire www.embulk.org website in the repo "www.embulk.org".
But, the repo is now renamed to "docs". This commit is to catch up with the latest status.
https://www.embulk.org/docs/ has been the main website, and it has been updated from
the "embulk-docs" directory of this "embulk" repository.
Later on, we plan to manage the website like:
* https://www.embulk.org/* (except for docs): https://github.com/embulk/embulk.github.io
* https://www.embulk.org/docs/: in https://github.com/embulk/docs
=> Update the repo for https://www.embulk.org/docs from "www.embulk.org" to "docs"

embulk-core/src/main/java/org/embulk/spi/TempFileSpace.java
Errors are sometimes observed that temporary files are not found.
* https://github.com/embulk/embulk/issues/1142
* https://github.com/embulk/embulk/issues/1151
To investigate this issue, adding a log message per TempFileSpace#cleanup.
=> Log stacktrace at TempFileSpace#cleanup

embulk-core/src/main/java/org/embulk/exec/SimpleTempFileSpaceAllocator.java, embulk-core/src/main/java/org/embulk/spi/TempFileSpace.java, embulk-core/src/test/java/org/embulk/spi/TestTempFileSpace.java
A `TempFileSpace` has been created in a directory with a timestamp, such as `"/tmp/2019-05-15 11:35:48.617 UTC"`.
But, when multiple Embulk processes (or tasks) are running, they can easily conflict.
To avoid such conflicts, this change starts to use `Files#createTempDirectory` to create a `TempFileSpace`.
Java VM guarantees that the directory created is unique.
https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createTempDirectory-java.nio.file.Path-java.lang.String-java.nio.file.attribute.FileAttribute...-
The old constructor `TempFileSpace(File)` keeps the original behavior for compatibility,
but it is now deprecated. It should not be called from plugins, though.
=> Guarantee TempFileSpace to be unique

embulk-core/src/main/java/org/embulk/spi/ExecSession.java, embulk-core/src/test/java/org/embulk/exec/TestSimpleTempFileSpaceAllocator.java
`TempFileSpace`'s directory names have been like `"2019-05-15 11:35:48.617 UTC"`,
but whitespaces and colons could make everything weird.
This change makes it in ISO 8601's basic format, such as `"20190515T113548Z"`.
=> Create a TempFileSpace with ISO 8601's basic format

embulk-core/src/main/java/org/embulk/exec/SimpleTempFileSpaceAllocator.java
From the discussion in #1189, adding a warning message for non-ISO 8601 format.
=> Warn if TempFileSpaceAllocator#newSpace is called with non-ISO 8601 basic format

build.gradle
It's not a functional change, but a change to upload the built artifacts to GitHub Package Registry. To be used in #1196.
=> Prepare a Gradle task to upload onto GitHub Package Registry

.github/workflows/upload.yml
WIth the GitHub Action, artifacts are uploaded to GitHub Package Registery every build. 
For this Pull Request at `2d44f83bf15952360013b6d2d1d445201a835c00`,
Action :
* https://github.com/embulk/embulk/commit/2d44f83bf15952360013b6d2d1d445201a835c00/checks
Artifacts :
* https://github.com/embulk/embulk/packages/54702?version=0.9.21-SNAPSHOT-2d44f83bf15952360013b6d2d1d445201a835c00
* https://github.com/embulk/embulk/packages/54714?version=0.9.21-SNAPSHOT-2d44f83bf15952360013b6d2d1d445201a835c00
* https://github.com/embulk/embulk/packages/54715?version=0.9.21-SNAPSHOT-2d44f83bf15952360013b6d2d1d445201a835c00
* https://github.com/embulk/embulk/packages/54716?version=0.9.21-SNAPSHOT-2d44f83bf15952360013b6d2d1d445201a835c00
* https://github.com/embulk/embulk/packages/54717?version=0.9.21-SNAPSH …
=> Build with GitHub Actions to upload onto GitHub Package Registry every build

embulk-core/src/main/java/org/embulk/spi/time/RubyTimeFormat.java, embulk-core/src/main/java/org/embulk/spi/time/RubyTimeFormatToken.java, embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java
adding missing hashCode() for classes overriding equals().
=> hashCode() for classes overriding equals(). fixes #1185

embulk-core/src/main/java/org/embulk/spi/TempFileSpace.java, embulk-core/src/test/java/org/embulk/spi/TestTempFileSpace.java
It throws a more readable Exception against illegal prefix/suffix for a temp file (#1193).
@shroman Can you have a look?
=> Throw a readable Exception against illegal prefix/suffix for a temp file (Fixes #1193)

embulk-core/src/main/java/org/embulk/deps/DependencyCategory.java, embulk-core/src/main/java/org/embulk/deps/DependencyClassLoader.java, embulk-core/src/main/java/org/embulk/deps/EmbulkDependencyClassLoaders.java, embulk-core/src/main/java/org/embulk/deps/EmbulkSelfContainedJarFiles.java, embulk-core/src/main/java/org/embulk/deps/cli/CliParser.java, embulk-core/src/main/java/org/embulk/deps/cli/HelpMessageLineDefinition.java, embulk-core/src/main/java/org/embulk/deps/cli/OptionDefinition.java, embulk-core/src/main/java/org/embulk/deps/cli/VelocityEngineDelegate.java, embulk-core/src/main/java/org/embulk/deps/maven/ComparableVersion.java, embulk-core/src/main/java/org/embulk/deps/maven/MavenArtifactFinder.java, embulk-core/src/test/java/org/embulk/deps/TestDependencyCategory.java
We plan to load more dependency libraries to be loaded through `DependencyClassLoader`. But now, we need annoying messy steps to extend them.
This pull request refactors `EmbulkDependencyClassLoaders` and `EmbulkSelfContainedJarFiles` to be parameterized so that it can be extended more easily.
The pull request consists of two steps:
* 1d2a6aca582315e45e78875815ac7d82da04ef74: focuses on `EmbulkDependencyClassLoaders`
* 3f2ed2f34d570322402964bc21a61fad87a59e42: focuses on `EmbulkSelfContainedJarFiles`
---
They are expected to be used like below. It is for the case of Embulk as the all-in-one executable package from CLI.
https://github.com/embulk/embulk/blob/v0.9.20/embulk-core/src/main/java/org/embulk/cli/Main.java#L60-L61
Users with `EmbulkEmbed` will need to call them by themselves. …
=> Refactor dependency class loaders to be extensible easier

embulk-core/src/main/java/org/embulk/deps/EmbulkDependencyClassLoaders.java
The "double initialization" check for JARs out of self-contained JAR was wrong in: 1d2a6aca582315e45e78875815ac7d82da04ef74
It was working for self-contained executable JAR, but it was not working for the EmbulkEmbed case, or other testing cases.
=> Fix refactored EmbulkDependencyClassLoaders to process JARs out of executable-JAR

.travis.yml, build.gradle, embulk-core/build.gradle, embulk-core/src/main/java/org/embulk/deps/DependencyCategory.java, embulk-core/src/main/java/org/embulk/deps/buffer/PooledBufferAllocator.java, embulk-core/src/main/java/org/embulk/exec/ExecModule.java, embulk-core/src/test/java/org/embulk/deps/TestDependencyCategory.java, embulk-core/src/test/ruby/vanilla/run-test.rb, embulk-deps/buffer/build.gradle, embulk-deps/buffer/config/checkstyle/suppressions.xml, embulk-deps/buffer/src/main/java/org/embulk/deps/buffer/PooledBufferAllocatorImpl.java, embulk-deps/buffer/src/test/java/org/embulk/deps/buffer/TestPooledBufferAllocatorImpl.java, embulk-standards/build.gradle, embulk-standards/src/test/ruby/vanilla/run-test.rb, settings.gradle
After refactoring at #1197 and #1203, as the first effort of isolating existing dependency libraries, we are moving this Netty Buffer to a separate `DependencyClassLoader`.
Because the caller of Netty Buffer was only `PooledBufferAllocator`, made it an entry point to the `DependencyClassLoader` part.
=> Load Netty Buffer library in a separate DependencyClassLoader

embulk-core/build.gradle, embulk-core/src/main/java/org/embulk/deps/buffer/Slice.java, embulk-core/src/main/java/org/embulk/spi/PageBuilder.java, embulk-core/src/main/java/org/embulk/spi/PageReader.java, embulk-deps/buffer/build.gradle, embulk-deps/buffer/src/main/java/org/embulk/deps/buffer/SliceImpl.java
After refactoring at #1201, we are moving this Airlift's Slice to the separate DependencyClassLoader for `Buffer`, the same as Netty Buffer.
Airlift's Slice is called from `PageBuilder` and `PageReader`. The entry point is `io.airlift.slice.Slice` here.
=> Load Airlift Slice library in a separate DependencyClassLoader

build.gradle
GitHub's vulnerability alert does not support Gradle unfortunately, but we'd want some checks for vulnerability. As the very first step, introducing a dependency checker Gradle plugin in our build.gradle.
=> Check dependency vulnerability semi-automatically with org.owasp:dependency-check-gradle

.travis.yml, build.gradle, embulk-core/build.gradle, embulk-core/src/main/java/org/embulk/deps/DependencyCategory.java, embulk-core/src/main/java/org/embulk/deps/guess/CharsetDetector.java, embulk-core/src/main/java/org/embulk/deps/guess/CharsetMatch.java, embulk-core/src/main/ruby/embulk/guess/charset.rb, embulk-core/src/test/java/org/embulk/deps/TestDependencyCategory.java, embulk-core/src/test/ruby/vanilla/run-test.rb, embulk-deps/guess/build.gradle, embulk-deps/guess/config/checkstyle/suppressions.xml, embulk-deps/guess/src/main/java/org/embulk/deps/guess/CharsetDetectorImpl.java, embulk-deps/guess/src/main/java/org/embulk/deps/guess/CharsetMatchImpl.java, embulk-deps/guess/src/test/java/org/embulk/deps/guess/TestCharsetDetectorImpl.java, embulk-standards/build.gradle, embulk-standards/src/test/ruby/vanilla/run-test.rb, settings.gradle
Next to #1201 (Netty Buffer) and #1204 (Airlift Slice), we're moving ICU4J that has been used for charset detection in Embulk's guess.
The entry point is just `CharsetDetector`. But as `CharsetDetector#detect` returns `CharsetMatch`, we have `CharsetMatch`, too.
=> Load ICU4J library in a separate DependencyClassLoader

build.gradle, embulk-core/build.gradle, embulk-deps/buffer/build.gradle, embulk-deps/config/build.gradle, embulk-deps/guess/build.gradle, embulk-docs/build.gradle, embulk-standards/build.gradle
Unfortunately, `rubygems-proxy.torquebox.org` stopped working as well as `rubygems.lasagna.io`.
* https://twitter.com/ysb33r/status/1207616778320465927
* https://twitter.com/ysb33r/status/1207617136069361664
* https://twitter.com/ysb33r/status/1207617434569641984
`rubygems-proxy.torquebox.org` has been an alternative workaround against JRuby/Gradle plugin's originally expected `rubygems.lasagna.io`. But neither is working now.
* https://github.com/jruby-gradle/jruby-gradle-plugin/issues/384
They are expected to take a long time to recover. It's time to drop the JRuby/Gradle plugin, and download those gems by ourselves in `build.gradle`.
----
This PR :
* Drops the use of JRuby/Gradle plugin
* Removes the references to the RubyGems/Maven proxy repository
* Downloads the dependency and test …
=> Download dependency gems without JRuby/Gradle plugin

build.gradle
Sorry that I was not aware of this at #1211. The separated `embulk-deps-config` was not included in the finally-generated executable JAR files.
This PR would add them.
=> Embed embulk-deps-config with SnakeYaml in executable JARs

build.gradle, embulk-core/build.gradle, embulk-core/gradle/dependency-locks/compileClasspath.lockfile, embulk-core/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-deps/buffer/build.gradle, embulk-deps/buffer/gradle/dependency-locks/compileClasspath.lockfile, embulk-deps/buffer/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-deps/cli/build.gradle, embulk-deps/cli/gradle/dependency-locks/compileClasspath.lockfile, embulk-deps/cli/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-deps/config/build.gradle, embulk-deps/config/gradle/dependency-locks/compileClasspath.lockfile, embulk-deps/config/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-deps/guess/build.gradle, embulk-deps/guess/gradle/dependency-locks/compileClasspath.lockfile, embulk-deps/guess/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-deps/maven/build.gradle, embulk-deps/maven/gradle/dependency-locks/compileClasspath.lockfile, embulk-deps/maven/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-standards/build.gradle, embulk-standards/gradle/dependency-locks/compileClasspath.lockfile, embulk-standards/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-test/build.gradle, embulk-test/gradle/dependency-locks/compileClasspath.lockfile, embulk-test/gradle/dependency-locks/runtimeClasspath.lockfile, gradle/wrapper/gradle-wrapper.properties, test-helpers/build.gradle
Through v0.10, we don't take too much care about compatibility. Then, we try updating things to the latest!
It enables dependency locks along with that.
=> Upgrade to Gradle 6.2.2

build.gradle
Embulk's executable JAR no longer needs package relocation. The Gradle Shadow plugin is no longer needed. Dependency JARs can be unzipped in build.gradle.
The Gradle Shadow plugin is too complicated inside, and has some potential problems as commented in `build.gradle`. It's reasonable to stop using it if we need just a simple thing. It was still reasonable to use it when we needed package relocation, though.
=> Build an executable JAR file without the Gradle Shadow plugin

build.gradle
Embulk's executable binaries were uploaded to Bintray, and `selfupdate` was choosing the "latest" version by Bintray's automated redirect from: `https://bintray.com/embulk/maven/embulk/_latestVersion`. The URL was hard-coded in Embulk.
It was a lock-in. Too bad. We removed the hard-code, and started to download from `https://dl.embulk.org/...` in #1132 (v0.9.17). But, Embulk executables older than v0.9.17 were still trying to access Bintray. We needed to keep releasing executable binaries to Bintray.
(At the same time, we started to release executable binaries to GitHub Releases, and https://dl.embulk.org/...` is redirected to GitHub Releases.)
Now, we want older Embulk users to stop getting auto-updated to v0.10 series. We have to stop uploading executable binaries to Bintray, then.
On …
=> Stop uploading the executable JAR to Bintray, and with declaring about Bintray more explicitly

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/EmbulkSystemProperties.java, embulk-core/src/main/java/org/embulk/exec/ExecModule.java, embulk-core/src/main/java/org/embulk/exec/ExtensionServiceLoaderModule.java, embulk-core/src/main/java/org/embulk/exec/ForSystemConfig.java, embulk-core/src/main/java/org/embulk/exec/GuessExecutor.java, embulk-core/src/main/java/org/embulk/exec/LocalExecutorPlugin.java, embulk-core/src/main/java/org/embulk/exec/SystemConfigModule.java, embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java, embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginSource.java, embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginSourceModule.java, embulk-core/src/main/java/org/embulk/spi/Extension.java, embulk-core/src/test/java/org/embulk/EmbulkTestRuntime.java, embulk-core/src/test/java/org/embulk/TestEmbulkSystemProperties.java, embulk-standards/src/main/java/org/embulk/standards/StandardPluginExtension.java, embulk-standards/src/main/java/org/embulk/standards/StandardPluginModule.java
`EmbulkSystemProperties` was introduced in #1160 (v0.9.22) to replace the system config represented by `ConfigSource`.
After it is added in v0.9.22, starting to use it in embulk-core v0.10.
=> Use EmbulkSystemProperties in embulk-core and its Guice Modules

embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java, embulk-core/src/main/java/org/embulk/jruby/LazyScriptingContainerDelegate.java, embulk-core/src/main/java/org/embulk/jruby/ScriptingContainerDelegate.java, embulk-core/src/main/java/org/embulk/jruby/ScriptingContainerDelegateImpl.java
`org.jruby.embed.ScriptingContainer` has still been injected for some plugins still getting `ScriptingContainer`, but we are going to unsupport it in v0.10. The JRuby runtime will be loaded just optionally at all, under a sub ClassLoader.
=> Remove direct injection of org.jruby.embed.ScriptingContainer (Fix #1007)

build.gradle, embulk-core/build.gradle, embulk-core/src/main/java/org/embulk/deps/DependencyCategory.java, embulk-core/src/main/java/org/embulk/deps/timestamp/RubyDateTimeFormatter.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatter.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatterRuby.java, embulk-core/src/test/java/org/embulk/deps/TestDependencyCategory.java, embulk-core/src/test/java/org/embulk/spi/time/TestTimestampFormatter.java, embulk-deps/timestamp/build.gradle, embulk-deps/timestamp/config/checkstyle/suppressions.xml, embulk-deps/timestamp/gradle/dependency-locks/compileClasspath.lockfile, embulk-deps/timestamp/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-deps/timestamp/src/main/java/org/embulk/deps/timestamp/RubyDateTimeFormatterImpl.java, embulk-standards/build.gradle, settings.gradle
See #830 for the details. In short, this use of `org.jruby.util.RubyDataFormat` is the blocker to make JRuby optional.
=> Stop using org.jruby.util.RubyDateFormat, and replace with embulk-util-rubytime under a sub ClassLoader (Fix #830)

embulk-api/src/main/java/org/embulk/config/ConfigSource.java, embulk-api/src/main/java/org/embulk/config/DataSource.java, embulk-api/src/main/java/org/embulk/config/TaskSource.java, embulk-core/src/main/java/org/embulk/config/DataSourceImpl.java, embulk-core/src/main/java/org/embulk/config/DataSourceSerDe.java, embulk-core/src/test/java/org/embulk/config/TestConfigSource.java
We're going to separate the config processing part (mapping `ConfigSource`/`TaskSource` into `(Plugin)Task` interface) into another utility artifact `embulk-util-config` to process configs on plugin's side.
To realize that, we have to have a method to retrieve `DataSource`'s internal structure without leaking Jackson instances, but as of now, we only have `getAttributes` and `getObjectNode` to return Jackson instances.
To retrieve `DataSource`'s internal structure, this PR is to add a new `toJson` method to stringify `DataSource`'s internal JSON structure so that `embulk-util-config` can rebuild its own JSON structure.
=> Add a new `toJson` method in `org.embulk.config.DataSource`

embulk-api/src/main/java/org/embulk/config/DataSource.java
The `toJson` method is newly added in DataSource. Nice to have a default implementation
for it so that an unexpected combination of newer DataSource and older DataSourceImpl
won't cause ununderstandable errors.
=> Implement a default implementation for org.embulk.config.DataSource#toJson

embulk-core/src/main/java/org/embulk/config/DataSourceSerDe.java
`JsonSerializer` is basically expected to throw `JsonGenerationException`, not `ConfigException` (which is `RuntimeException`).
(It was added in https://github.com/embulk/embulk/pull/1246/files#diff-a6bb4457efbba2979dc038a940f2f6e0.)
=> Not to throw ConfigException directly from SerDe

build.gradle, embulk-api/build.gradle, embulk-core/build.gradle, embulk-deps/buffer/gradle/dependency-locks/compileClasspath.lockfile, embulk-deps/cli/gradle/dependency-locks/compileClasspath.lockfile, embulk-deps/config/gradle/dependency-locks/compileClasspath.lockfile, embulk-deps/guess/gradle/dependency-locks/compileClasspath.lockfile, embulk-deps/maven/gradle/dependency-locks/compileClasspath.lockfile, embulk-deps/timestamp/gradle/dependency-locks/compileClasspath.lockfile, embulk-junit4/build.gradle, embulk-junit4/gradle/dependency-locks/compileClasspath.lockfile, embulk-standards/gradle/dependency-locks/compileClasspath.lockfile
Since v0.10.0 after Embulk started using "implementation" to declare dependencies instead of "compile", embulk-core's dependencies are defined as "runtime" instead of "compile" in their pom.xml.
https://bintray.com/embulk/maven/embulk/0.9.23#files/org%2Fembulk%2Fembulk-core%2F0.9.23
https://bintray.com/embulk/maven/embulk/0.10.0#files/org%2Fembulk%2Fembulk-core%2F0.10.0
Embulk plugins have expected that embulk-core's dependencies are declared as "compile" in pom.xml. So, plugins didn't declare such dependencies of embulk-core as their own dependencies.
As of now, keeping them as "compile" would be better because:
* This change was unexpected.
* We plan to remove many finally from direct dependencies of embulk-core.
Plugins are expected to follow when the removal happens, not by this …
=> Use "api" in "java-library" to build embulk-core

build.gradle
`./gradlew executable` from scratch was not working due to lack of dependencies.
=> Build Gradle ":executable" depending on other "...:jar" tasks

embulk-core/src/main/java/org/embulk/exec/BulkLoader.java, embulk-core/src/main/java/org/embulk/spi/Exec.java, embulk-core/src/main/java/org/embulk/spi/ExecSession.java, embulk-core/src/test/java/org/embulk/spi/TestExecSession.java
The `transaction_time` feature has been using Guava Optional and Joda-Time-based `Timestamp`, but they can be replaced to `java.util.Optional<java.util.Instant>`.
We are keeping `Timestamp`-based APIs for now, but they may be removed later.
=> Stop Timestamp-based transaction_time

embulk-core/src/main/java/org/embulk/exec/ExecModule.java, embulk-core/src/main/java/org/embulk/jruby/JRubyInitializer.java, embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java, embulk-core/src/main/java/org/embulk/spi/ExecSession.java
`Exec.getLogger` is going to be replaced with SLF4J's direct `LoggerFactory.getLogger`, and its background `ILoggerFactory` Guice binding would be removed.
This is the last step of the replacement inside `embulk-core`.
=> Call LoggerFactory.getLogger more directly to prepare for removing logger binding from Guice

embulk-core/src/main/java/org/embulk/exec/ExecModule.java, embulk-core/src/main/java/org/embulk/spi/time/DateTimeZoneJacksonModule.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampJacksonModule.java, embulk-core/src/main/java/org/embulk/spi/unit/LocalFileJacksonModule.java, embulk-core/src/main/java/org/embulk/spi/util/CharsetJacksonModule.java
For unknown reasons, some Jackson Serializers and Deserializers (`*SerDe`) have been implemented to register only into `ObjectMapperModule` (Guice `Module`) only for `ModelManager`, not as common Jackson `Module`s. (Note that: Guice `Module` and Jackson `Module` are totally different concepts.)
But, they can be implemented as Jackson `Module`s, and that would be more general-purpose. As we want to use them for general `ObjectMapper` (in next #1263), they would be implemented as Jackson `Module`s.
=> Replace some SerDe classes to independent Jackson Modules

embulk-core/src/main/java/org/embulk/EmbulkRunner.java, embulk-core/src/main/java/org/embulk/command/PreviewPrinter.java, embulk-core/src/main/java/org/embulk/command/TablePreviewPrinter.java, embulk-core/src/main/java/org/embulk/command/VerticalPreviewPrinter.java
To reduce dependency onto `ModelManager`, stopping to use `ModelManager` in `PreviewPrinter`.
`PreviewPrinter` is used only in the `embulk preview` command -- especially only when called via CLI. Not used from an embedded program using `EmbulkEmbed`.
=> Stop using ModelManager in PreviewPrinter

embulk-api/src/main/java/org/embulk/spi/Buffer.java
The package-private constructor of `abstract org.embulk.spi.Buffer` was implemented in #1232 when it was moved to `embulk-api`, but I don't remember why I made it package-private... It blocked me from implementing another implementation of `Buffer` out of `org.embulk.spi`.
I don't think it needs to be package-private. Let me know if you see any concern.
(I thought removing the explicitly-defined constructor was another option to have just an implicit default constructor. I thought it should be okay, but kept it declared just because I didn't remember the original reason to have an explicit constructor, and I saw no practical difference there as it's an `abstract` class.)
=> Get the constructor of org.embulk.spi.Buffer protected

embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java
The log message introduced in #1271 is shown like:
```
2020-08-13 08:22:41.828 +0000 [INFO] (0001:transaction): Class javax.annotation.PostConstruct is loaded by the parent ClassLoader, which is removed by JEP 320. The plugin needs to include it on the plugin side. See https://github.com/embulk/embulk/issues/1270 for more details.
java.lang.Exception: null
at org.embulk.plugin.PluginClassLoader.logInfoIfJep320Class(PluginClassLoader.java:281) [embulk-core-0.10.8.jar:0.10.8]
```
`java.lang.Exception: null` is much confusing. We'll want the stack trace to be shown as `DUMMY` explicitly.
=> Explicitly show the dump of an Exception for JEP 320 is a dummy Exception

build.gradle
Planning to release v0.10.11 with #1277, #1285, #1286, and #1287.
I already have #1289 and #1290 in the queue, but they can be impactful changes. So, I'm going to cut the version before them.
=> Bump up to v0.10.12-SNAPSHOT

embulk-core/src/main/java/org/embulk/command/PreviewPrinter.java, embulk-core/src/main/java/org/embulk/exec/ExecModule.java, embulk-core/src/main/java/org/embulk/spi/type/Type.java, embulk-core/src/main/java/org/embulk/spi/type/TypeJacksonModule.java, embulk-core/src/test/java/org/embulk/spi/type/TestTypeSerDe.java
Replacing Jackson annotation on `org.embulk.spi.type.Type` to Jackson `Module`-based SerDe implementation.
This is needed to move `Type` to `embulk-api` that is Jackson-independent. As its side effect, `Type` will not be able to get converted out of `org.embulk.config.*` (including `ModelManager`), but we accept it.
We'll need another update for `embulk-util-config` once the new `embulk-api` including `Type` is released.
=> Replace Jackson annotations in Type to Jackson Module

embulk-core/src/main/java/org/embulk/command/PreviewPrinter.java, embulk-core/src/main/java/org/embulk/exec/ExecModule.java, embulk-core/src/main/java/org/embulk/spi/Column.java, embulk-core/src/main/java/org/embulk/spi/ColumnJacksonModule.java, embulk-core/src/test/java/org/embulk/spi/TestColumnMapping.java
Replacing Jackson annotation on `org.embulk.spi.Column` to Jackson `Module`-based SerDe implementation.
This is needed to move `Column` to `embulk-api` that is Jackson-independent. As its side effect, `Column` will not be able to get converted out of `org.embulk.config.*` (including `ModelManager`), but we accept it.
We'll need another update for `embulk-util-config` once the new `embulk-api` including `Column` is released.
----
This PR consists of two commits:
* c16ffeb6ef8d65b8890faf05c4332dfa93de0073: Just add a test of mapping JSON to `Column`.
* 9470d2553891be2ae3b37f5cdf381af47e26d257: Actual replacement.
It is confirmed that c16ffeb6ef8d65b8890faf05c4332dfa93de0073 succeeds, and 9470d2553891be2ae3b37f5cdf381af47e26d257 still succeeds with the replacement.
=> Replace Jackson annotations in Column to Jackson Module

embulk-core/src/main/java/org/embulk/command/PreviewPrinter.java, embulk-core/src/main/java/org/embulk/exec/ExecModule.java, embulk-core/src/main/java/org/embulk/spi/ColumnJacksonModule.java, embulk-core/src/main/java/org/embulk/spi/Schema.java, embulk-core/src/main/java/org/embulk/spi/SchemaJacksonModule.java, embulk-core/src/test/java/org/embulk/spi/TestSchema.java
Similar to #1290, replacing Jackson annotation on `org.embulk.spi.Schema` to Jackson `Module`-based SerDe implementation.
This is needed to move `Schema` to `embulk-api` that is Jackson-independent. As its side effect, `Schema` will not be able to get converted out of `org.embulk.config.*` (including `ModelManager`), but we accept it.
We'll need another update for `embulk-util-config` once the new `embulk-api` including `Schema` is released.
----
This PR consists of two commits:
* eafe1cc41e48d918acee5a717209e74d81db856b: Just add a test of mapping JSON to `Schema`.
* 0eb374f02822a48a8ae3f613ad01f84506267cb4: Actual replacement.
It is confirmed that eafe1cc41e48d918acee5a717209e74d81db856b succeeds, and 0eb374f02822a48a8ae3f613ad01f84506267cb4 still succeeds with the replacement.
=> Replace Jackson annotations in Schema to Jackson Module

embulk-core/src/main/java/org/embulk/command/PreviewPrinter.java, embulk-core/src/main/java/org/embulk/spi/PageBuilder.java, embulk-core/src/main/java/org/embulk/spi/PageReader.java, embulk-core/src/main/java/org/embulk/spi/time/Timestamp.java, embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/Pages.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/AbstractDynamicColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/BooleanColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/DoubleColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/JsonColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/LongColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/SkipColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/StringColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/TimestampColumnSetter.java, embulk-core/src/test/java/org/embulk/spi/MockFormatterPlugin.java, embulk-core/src/test/java/org/embulk/spi/MockParserPlugin.java, embulk-core/src/test/java/org/embulk/spi/PageTestUtils.java, embulk-core/src/test/java/org/embulk/spi/TestFileInputRunner.java, embulk-core/src/test/java/org/embulk/spi/TestFileOutputRunner.java, embulk-core/src/test/java/org/embulk/spi/TestPageBuilderReader.java
This deprecation does not mean immediate removal of `Timestamp`, but as javadoc'ed for `Timestamp`, `java.time.Instant` can be a perfect alternative of `org.embulk.spi.time.Timestamp`, and we are going to use `Instant` instead of `Timestamp` almost everywhere.
=> Deprecate org.embulk.spi.time.Timestamp

embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnSetterFactory.java, embulk-core/src/main/java/org/embulk/spi/util/PagePrinter.java, embulk-core/src/main/java/org/embulk/spi/util/Timestamps.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/JsonColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/StringColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/TimestampColumnSetter.java
We have had a lot of deprecation warnings when building `embulk-core` since #1273. They have been deprecated for plugins, but the core still uses them for a while.
To avoid so noisy warnings, adding `@SuppressWarnings` there.
=> Suppress internal deprecation warnings for TimestampFormatter and TimestampParser

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/config/DataSourceImpl.java, embulk-core/src/main/java/org/embulk/exec/BulkLoader.java, embulk-core/src/main/java/org/embulk/exec/GuessExecutor.java, embulk-core/src/main/java/org/embulk/exec/PreviewExecutor.java, embulk-core/src/main/java/org/embulk/exec/SamplingParserPlugin.java, embulk-core/src/main/java/org/embulk/spi/FileInputRunner.java, embulk-core/src/main/java/org/embulk/spi/FileOutputRunner.java, embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnSetterFactory.java
We have had a lot of deprecation warnings when building `embulk-core` since #1273. They have been deprecated for plugins, but the core still uses them for a while.
To avoid so noisy warnings, adding `@SuppressWarnings` there.
=> Suppress internal deprecation warnings for ConfigSource#loadConfig and TaskSource#loadTask

embulk-core/src/main/java/org/embulk/command/PreviewPrinter.java
We have had a lot of deprecation warnings when building `embulk-core` since #1273. They have been deprecated for plugins, but the core still uses them for a while.
To avoid so noisy warnings, adding `@SuppressWarnings` there.
=> Suppress internal deprecation warnings for org.embulk.spi.util.Pages

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/EmbulkRunner.java, embulk-core/src/main/java/org/embulk/config/ConfigLoader.java, embulk-core/src/main/java/org/embulk/config/DataSourceImpl.java, embulk-core/src/main/java/org/embulk/config/DataSourceSerDe.java, embulk-core/src/main/java/org/embulk/config/ModelManager.java, embulk-core/src/main/java/org/embulk/config/TaskInvocationHandler.java, embulk-core/src/main/java/org/embulk/config/TaskSerDe.java, embulk-core/src/main/java/org/embulk/exec/ExecModule.java, embulk-core/src/main/java/org/embulk/jruby/JRubyInitializer.java, embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java, embulk-core/src/main/java/org/embulk/spi/Exec.java, embulk-core/src/main/java/org/embulk/spi/ExecSession.java
`ModelManager` is one of the biggest source of complicated dependencies in `embulk-core`. Once plugins start using `embulk-util-config` instead of `ConfigSource#loadConfig` and `TaskSource#loadTask`, it will finally be unnecessary.
To show it will be finally away, marking it `@Deprecated`. Plugins should not use it!
=> Deprecate ModelManager

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/EmbulkRunner.java, embulk-core/src/main/java/org/embulk/exec/BulkLoader.java, embulk-core/src/main/java/org/embulk/exec/GuessExecutor.java, embulk-core/src/main/java/org/embulk/exec/LocalExecutorPlugin.java, embulk-core/src/main/java/org/embulk/exec/PreviewExecutor.java, embulk-core/src/main/java/org/embulk/spi/Exec.java, embulk-core/src/main/java/org/embulk/spi/ExecInternal.java, embulk-core/src/main/java/org/embulk/spi/ExecSession.java, embulk-core/src/main/java/org/embulk/spi/ExecSessionInternal.java, embulk-core/src/main/java/org/embulk/spi/FileInputRunner.java, embulk-core/src/main/java/org/embulk/spi/FileOutputRunner.java, embulk-core/src/main/java/org/embulk/spi/ProcessTask.java, embulk-core/src/main/java/org/embulk/spi/util/Decoders.java, embulk-core/src/main/java/org/embulk/spi/util/DecodersInternal.java, embulk-core/src/main/java/org/embulk/spi/util/Encoders.java, embulk-core/src/main/java/org/embulk/spi/util/EncodersInternal.java, embulk-core/src/main/java/org/embulk/spi/util/Executors.java, embulk-core/src/main/java/org/embulk/spi/util/ExecutorsInternal.java, embulk-core/src/main/java/org/embulk/spi/util/Filters.java, embulk-core/src/main/java/org/embulk/spi/util/FiltersInternal.java, embulk-core/src/test/java/org/embulk/EmbulkTestRuntime.java, embulk-junit4/src/main/java/org/embulk/test/TestingBulkLoader.java
It is planned to move `org.embulk.spi.Exec` to `embulk-api`, but some methods should be removed before that because :
* `getInjector`: `Injector` would be hidden from plugins.
* `getModelManager`: `ModelManager` is deprecated.
* `newPlugin`: not for plugins, and its argument `PluginType` blocks from hiding Jackson from plugins.
But, they are still needed in `embulk-core`, and some (hacky) plugins are using `newPlugin`.
Then, this commit introduces `ExecInternal` for `embulk-core` inside, and hacky plugins so that they can technically call it (although calling it is discouraged -- no guarantee in compatibility).
=> Prepare org.embulk.spi.ExecInternal to contain Exec methods not for plugins

embulk-spi/src/main/java/org/embulk/spi/DecoderPlugin.java, embulk-spi/src/main/java/org/embulk/spi/EncoderPlugin.java, embulk-spi/src/main/java/org/embulk/spi/FileInputPlugin.java, embulk-spi/src/main/java/org/embulk/spi/FileOutputPlugin.java, embulk-spi/src/main/java/org/embulk/spi/GuessPlugin.java
SPI Javadocs, that are introduced in #1254 and #1274, have not been accurate, especially about input/output directions of `FileOutput` and `PageOutput`. This PR is fixing the problems, and some English representations.
=> Fix Javadocs of DecoderPlugin, EncoderPlugin, FileInputPlugin, FileOutputPlugin, and GuessPlugin

embulk-api/src/main/java/org/embulk/spi/Schema.java, embulk-api/src/main/java/org/embulk/spi/type/Type.java
`Type#getJavaType` and `Type#getFixedStorageSize` are mostly unused, but causing unnecessary tight coupling. They would be finally removed in Embulk v0.10 or v0.11.
=> Deprecate Type#getJavaType and Type#getFixedStorageSize

embulk-api/build.gradle, embulk-api/gradle/dependency-locks/compileClasspath.lockfile, embulk-api/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-core/gradle/dependency-locks/compileClasspath.lockfile, embulk-core/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-deps/gradle/dependency-locks/compileClasspath.lockfile, embulk-junit4/gradle/dependency-locks/compileClasspath.lockfile, embulk-junit4/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-spi/gradle/dependency-locks/compileClasspath.lockfile, embulk-spi/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-standards/gradle/dependency-locks/compileClasspath.lockfile
Upgrading `slf4j-api` to the latest `1.7`. It is required to use `SubstituteLogger` in next PRs #1333 and #1334.
We don't use `slf4j-api` `1.8.*` nor `2.0.*` because :
* SLF4J 1.8 will never be "released".
* http://mailman.qos.ch/pipermail/slf4j-user/2020-August/001748.html
* SLF4J 2.0 has a different mechanism to find a logging driver. It can cause severe incompatibility problems with plugins.
=> Upgrade depended slf4j-api to 1.7.30

embulk-core/src/main/java/org/embulk/cli/CliManifest.java, embulk-core/src/main/java/org/embulk/cli/Main.java, embulk-core/src/main/java/org/embulk/deps/EmbulkDependencyClassLoaders.java, embulk-core/src/main/java/org/embulk/deps/EmbulkSelfContainedJarFiles.java, embulk-core/src/main/java/org/embulk/deps/Resource.java, embulk-core/src/main/java/org/embulk/deps/SelfContainedJarFile.java
Before upcoming changes to refactor command line processing, and Embulk system properties, changing the loader of JAR resources (in the command-line Embulk executable binary) to log just with `System.err`, not with SLF4J.
It is because :
* They are loaded (initialized) in the very beginning of Embulk CLI, when SLF4J and Logback are not initialized.
* We can use `SubstituteLogger` of SLF4J for delayed logging, but their all "logs" are about critical cases. When they are logged, Embulk is failing.
* For critical error messages, not SLF4J logging, but `System.err` would fit well.
=> Initialize embedded JAR resources in the very beginning, without SLF4J

build.gradle, embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java, embulk-core/src/main/java/org/embulk/cli/EmbulkSystemPropertiesBuilder.java, embulk-core/src/main/java/org/embulk/cli/Main.java, embulk-core/src/main/java/org/embulk/jruby/JRubyInitializer.java, embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java, embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginSource.java, embulk-core/src/test/java/org/embulk/jruby/TestJRubyInitializer.java
It is to set Embulk System Properties not only from the command line, but also from environment variables and a config file (`embulk.properties`). It also finds a kind of "home" directories from the file system, and the Embulk System Properties.
JFYI: it basically does not affect `EmbulkEmbed` use-case. It's only about CLI use-case. The callers of `EmbulkEmbed` needs to configure Embulk System Properties `gem_home`, `gem_path`, and `m2_repo` explicitly.
Before:
* Embulk had no concept of "Embulk home".
* Embulk was looking for "Gem home", "Gem path", and "local Maven repository" by an ad-hoc rule.
* Env `GEM_HOME` and `GEM_PATH`
* Fixed directories under `~/.embulk/lib`
After:
* Embulk will have a concept of "Embulk home".
* If Embulk System Property `embulk_home` is set from the command …
=> Find Embulk's home-like directories: embulk_home, m2_repo, gem_home, and gem_path

build.gradle
As the JRuby removal is a big change, I'm going to split versions released.
* #1332, #1337, #1333, #1334: v0.10.20
* #1336, #1338: v0.10.21
=> Bump up to v0.10.21-SNAPSHOT

embulk-deps/src/main/java/org/embulk/deps/cli/CommandLineImpl.java
Fixing #1343. The `-o` option for `guess` didn't accept an argument unintentionally.
=> Fix the CLI option "-o" for guess (#1343)

build.gradle, embulk-core/build.gradle, embulk-core/src/test/ruby/vanilla/run-test.rb, embulk-standards/build.gradle, embulk-standards/src/test/ruby/vanilla/run-test.rb
After removing JRuby from Embulk executable binary, it also removes embedded RubyGem libraries: `msgpack`, `bundler`, and `liquid`.
* `msgpack` is mandatory for Ruby-based Embulk plugins. Users would have to install it with `embulk gem install msgpack` by themselves.
* `bundler` has not been mandatory, but some CLI users have used it for maintaining plugin installation. Actually `bundler` is preinstalled in some JRuby versions, so it depends on users which JRuby to use.
* `liquid` has not been mandatory, but some CLI users have used it for templating Embulk configs. JFYI: its's not available for `EmbulkEmbed` users. Users would have to install it with `embulk gem install liquid` by themselves.
=> Remove embedded gems: msgpack, bundler, liquid

embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java, embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderFactory.java, embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderFactoryImpl.java, embulk-core/src/main/java/org/embulk/plugin/jar/JarPluginLoader.java
`PluginClassLoader` had had a mechanism to load a JARs-in-JAR-style nested JAR plugin, but it has been removed since v0.9.17 by: #1111
This commit is to remove some remaining code for nested JAR plugins.
=> Cleanup and refactor PluginClassLoader and its Factory

embulk-core/src/main/ruby/embulk/page_builder.rb
`java.time.Timestamp` does not exist. It was a mistake in:
https://github.com/embulk/embulk/pull/1336/files#diff-2bf34f7ba0b21cdb2a58e98bae5967a04e5c0673b83ae17d7d0b8104cd48754aR17-R18
=> Fix "missing class name (`java.time.Timestamp')"

embulk-core/src/main/java/org/embulk/jruby/JRubyInitializer.java, embulk-ruby/build.gradle, embulk-ruby/gem_version.rb.template, embulk-ruby/lib/embulk/logger.rb, embulk-ruby/lib/embulk/version.rb
It turned out that existing v0.9.* users with Bundler (`mkbundle`) may fall into a weird situation that `embulk.gem` 0.10.24 is installed by Bundler, caused by releasing `embulk.gem` 0.10.24 in rubygems.org. 
Most Bundler users should have had the following declaration in their `Gemfile` (by our recommendation when we started v0.9):
```
gem 'embulk'
```
It installs the latest `embulk.gem`, then `embulk.gem` 0.10.24 is installed.
However, we cannot get back. Then, we're going to introduce a version check in `embulk.gem` v0.10.25+ between the Embulk core (Java) and `embulk.gem` (Ruby). The check fails if the running Embulk version does not match the loaded `embulk.gem` version, and suggests how the user should do based on their use-case.
In case the user uses v0.9.* with Bundler, it …
=> Fail explicitly with embulk.gem mismatching with the running Embulk

embulk-core/src/main/java/org/embulk/plugin/MavenPluginType.java, embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginSource.java, embulk-core/src/test/java/org/embulk/plugin/TestPluginType.java
It is to look for a Maven-based plugin even when only a simple plugin type is specified like `type: ftp` in user configuration, if a corresponding Embulk system property is configured.
For example, assume a user configuration is like below:
```
in:
type: ftp
host: ...
...
```
Embulk has looked only for a RubyGem-based plugin so far in this case.
By this pull request, Embulk looks for a Maven-based plugin if an Embulk system property `plugins.input.ftp` is set like `maven:org.embulk:ftp:0.3.0`.
=> Load a Maven-based plugin from a simple plugin type with Embulk system properties

embulk-ruby/test/vanilla/test_version.rb
It tests "embulk.gem's version check" mechanism introduced in #1370 in `embulk-ruby`'s Ruby test code.
=> Test embulk.gem's version check

embulk-core/src/main/java/org/embulk/deps/DependencyClassLoader.java, embulk-core/src/main/java/org/embulk/deps/EmbulkSelfContainedJarFiles.java
Types of self-contained JAR resource files have been once disabled in #1279, but now we have to reenable it for a different purpose.
Embulk executable binary is going to self-contain `embulk-standards` plugin JARs in upcoming changes. Types of self-contained JAR files need to be reenabled so that the self-contained plugin JARs are loaded through `PluginClassLoader`s, not `DependencyClassLoader`.
This is needed for #1360.
=> Reenable multiple types of self-contained JAR resource files

embulk-core/src/main/java/org/embulk/deps/DependencyClassLoader.java, embulk-core/src/main/java/org/embulk/deps/SelfContainedJarAwareURLClassLoader.java
It prepares for `PluginClassLoader` to be able to load from JAR resources self-contained in the Embulk JAR file. `PluginClassLoader` is going to extend `SelfContainedJarAwareURLClassLoader`, too.
This is needed for #1360.
=> Refactor DependencyClassLoader to separate to SelfContainedJarAwareURLClassLoader

build.gradle, embulk-core/src/main/java/org/embulk/deps/EmbulkSelfContainedJarFiles.java, embulk-core/src/main/java/org/embulk/exec/ExecModule.java, embulk-core/src/main/java/org/embulk/exec/LocalExecutorPlugin.java, embulk-core/src/main/java/org/embulk/exec/SamplingParserPlugin.java, embulk-core/src/main/java/org/embulk/plugin/InjectedPluginSource.java, embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java, embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderFactory.java, embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderFactoryImpl.java, embulk-core/src/main/java/org/embulk/plugin/PluginManager.java, embulk-core/src/main/java/org/embulk/plugin/PluginSource.java, embulk-core/src/main/java/org/embulk/plugin/SelfContainedPluginSource.java, embulk-core/src/main/java/org/embulk/plugin/jar/JarPluginLoader.java, embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginSource.java, embulk-core/src/main/java/org/embulk/spi/ExecSessionInternal.java, embulk-standards/src/main/java/org/embulk/standards/StandardPluginModule.java, embulk-standards/src/test/java/org/embulk/standards/StandardPluginTestExtension.java, embulk-standards/src/test/java/org/embulk/standards/StandardPluginTestModule.java, embulk-standards/src/test/resources/META-INF/services/org.embulk.spi.Extension
After #1358 and #1359, this PR starts loading (non-guess) `embulk-standards` plugins as self-contained JAR files through `PluginClassLoader`.
They have been loaded on the top-level class loader so far, registered through `StandardPluginModule` and `StandardPluginExtension`.
=> Embed standard non-guess plugins as self-contained JARs, and load them through PluginClassLoader

embulk-api/src/main/java/org/embulk/spi/Buffer.java
#1409 needs a fix in `embulk-util-file` to construct its `EmptyBuffer`.
`embulk-util-file:0.1.1`'s `EmptyBuffer` expects a constructor `Buffer()` without arguments.
* https://github.com/embulk/embulk-util-file/blob/v0.1.1/src/main/java/org/embulk/util/file/EmptyBuffer.java
But it's only in Embulk v0.10's `Buffer`.
* https://github.com/embulk/embulk/blob/v0.10.27/embulk-api/src/main/java/org/embulk/spi/Buffer.java
Embulk v0.9.23 did not have `Buffer()`, but `Buffer(byte[], int, int)`.
* https://github.com/embulk/embulk/blob/v0.9.23/embulk-core/src/main/java/org/embulk/spi/Buffer.java
It's the reason why `embulk-util-file` cannot initialize `EmptyBuffer` with Embulk v0.9.23 in #1409. This is one of the fixes for the problem. The other fix will be in `embulk-util-file`.
=> Declare Buffer's constructor compatible with v0.9's

embulk-core/src/main/java/org/embulk/deps/SelfContainedJarFile.java
This is a fix for #1408.
#1408 seems starting when loading the same resource in a self-contained JAR from mulitiple class loaders. It started happening when Embulk started to load self-contained plugin JARs in v0.10.26 by #1360.
It looks to be caused by the same `ByteBuffer` used multiple times. This PR fixes it by duplicating the `ByteBuffer` with `ByteBuffer#asReadOnlyBuffer`.
* https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html#asReadOnlyBuffer--
=> Duplicate ByteBuffer before loading an inner class/resource from self-contained JARs

build.gradle
It adds the `org.embulk.embulk-plugins` Gradle plugin without applying at the top-level.
Then, it moves the Gradle subproject list `subprojectNamesOfStandardPlugins` to a new list `subprojectNamesOfLegacyStandardPlugins` so that a new `subprojectNamesOfStandardPlugins` can include modernized standard plugins.
Finally, it sets subprojects in the new `subprojectNamesOfStandardPlugins` to be released to Maven Central through `publishMavenPublicationToMavenCentralRepository` to de defined in their own sub build.gradle.
=> Prepare in the top-level build.gradle for modernizing standard plugins

README.md, build.gradle
JFrog will be sunsetting Bintray and JCenter. New package versions submittion will close on March 31st, 2021. Serving packages from JCenter will terminate on February 1st, 2022.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
Embulk has been migrating its distribution repository to Maven Central gradually, but it has not completed yet. `embulk-api` and `embulk-spi` have been released into Maven Central from their beginning, v0.10.2 and v0.10.7, respectively.
Along with standard plugins, which start to be released into Maven Central from this version v0.10.28, it's time to drop JCenter/Bintray, adn start releasing `embulk-core`, `embulk-deps`, and `embulk-junit4` into Maven Central!
=> Release everything into Maven Central, instead of JCenter/Bintray

build.gradle, embulk-core/build.gradle, embulk-deps/build.gradle, embulk-guess-csv/build.gradle, embulk-guess-csv_all_strings/build.gradle, embulk-junit4/build.gradle, embulk-parser-csv/build.gradle, embulk-parser-json/build.gradle, embulk-ruby/build.gradle, test-helpers/build.gradle
The build scripts (`build.gradle`) in the repository have been chaotic. It was partially because of the `bintray` Gradle plugin, but we now dropped JCenter/Bintray (#1401). It's time to cleanup `build.gradle` in the repository!
To be easier to review/trace, and not to make mistakes, this pull request consists of several Git commits for step-by-step changes.
=> Cleanup build.gradle

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/EmbulkSystemProperties.java, embulk-core/src/main/java/org/embulk/exec/GuessExecutor.java, embulk-core/src/main/java/org/embulk/exec/PreviewExecutor.java, embulk-core/src/main/java/org/embulk/plugin/BuiltinPluginSource.java, embulk-core/src/main/java/org/embulk/plugin/SelfContainedPluginSource.java, embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginSource.java, embulk-core/src/main/java/org/embulk/spi/ExecSessionInternal.java, embulk-core/src/main/java/org/embulk/spi/FileInputRunner.java, embulk-core/src/test/java/org/embulk/spi/TestFileInputRunner.java
`guess_sample_buffer_bytes` and `preview_sample_buffer_bytes` are 32KB by default, and they could be too small as of the age of 2020s.
But, a decision to increase the default values is not easy. For instance, if users are reading just a local file, incrasing the default value does ot have any serious impact. But for another example, some users read files from S3. AWS charges for a size of S3 read. Updating the default value can affect such users silently.
As a better workaround than setting `exec: guess_sample_buffer_bytes: 32768` in every Embulk configuration, this change is to make it available to set their default values from Embulk System Properties, which could be configured from auto-loaded `.embulk/embulk.properties` (since v0.10.21).
=> Set guess_sample_buffer_bytes and preview_sample_buffer_bytes from Embulk System Properties

embulk-guess-csv_verify/build.gradle, embulk-guess-csv_verify/lib/embulk/guess/csv_verify.rb
`embulk-guess-csv-verify` (#1415) originally dumped only different key names, without actual diffs, in order to avoid logging confidential information (e.g. AWS access token) unintentionally.
But, actual diffs are really helpful to investigate. This PR is to dump actual diffs of `decoders` and `parser` sections because those sections should not have any confidential information.
=> Dump actual diffs in "decoders" and "parser" in embulk-guess-csv_verify

embulk-guess-csv_verify/build.gradle, embulk-guess-csv_verify/gradle/dependency-locks/embulkPluginRuntime.lockfile, embulk-guess-csv_verify/lib/embulk/guess/csv_verify.rb, embulk-guess-csv_verify/src/main/java/org/embulk/standards/CsvParserPlugin.java, embulk-guess-csv_verify/src/main/java/org/embulk/standards/CsvTokenizer.java
`embulk-guess-csv_verify` has used the modern `embulk-parser-csv` internally, but it could be different from the original if the modern parser was not 100% compatible. To have a compliant comparison, using the legacy `CsvParserPlugin` copied from legacy `embulk-standards`.
=> Let embulk-guess-csv_verify to use the legacy CsvParserPlugin in the legacy embulk-standards

embulk-deps/src/main/java/org/embulk/deps/cli/CommandLineImpl.java, embulk-deps/src/test/java/org/embulk/deps/cli/TestCommandLineParserImpl.java
We have had a bug in command line parsing -- `-L` and `-I` have been mixed up. (#1413)
=> Fix the mix-up of command line options -L and -I (Fix #1413)

embulk-guess-csv_verify/gradle/dependency-locks/embulkPluginRuntime.lockfile
Due to the commits and merge order of #1406 and #1420, `embulk-guess-csv_verify`'s dependency lock still contained dependencies to Joda-Time on `master`.
=> Update the dependency lock of embulk-guess-csv_verify against Joda-Time removal

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/EmbulkSystemProperties.java, embulk-core/src/main/java/org/embulk/exec/GuessExecutor.java, embulk-core/src/main/java/org/embulk/exec/PreviewExecutor.java, embulk-core/src/main/java/org/embulk/plugin/BuiltinPluginSource.java, embulk-core/src/main/java/org/embulk/plugin/SelfContainedPluginSource.java, embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginSource.java, embulk-core/src/main/java/org/embulk/spi/ExecSessionInternal.java, embulk-core/src/main/java/org/embulk/spi/FileInputRunner.java, embulk-core/src/test/java/org/embulk/spi/TestFileInputRunner.java
Reverting #1414 since it caused an error in loading a File Input Plugin in a Ruby gem format.
It changed the arguments of Java `FileInputRunner`'s constructor, but the Ruby side did not catch up. It caused the error below.
Unfortunately, it is not trivial to pass the second argument, `EmbulkSystemProperties`, from Ruby as of now -- it would be easier with a planned change when Guice is removed. This change #1414 was not necessary as of now. Let's revert it now, and think about it later.
```
Caused by: org.jruby.embed.InvokeFailedException: (ArgumentError) wrong number of arguments (1 for 2)
at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.call(EmbedRubyObjectAdapterImpl.java:320)
at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.callMethod(EmbedRubyObjectAdapterImpl.java:159) …
```
=> Revert "Set guess_sample_buffer_bytes and preview_sample_buffer_bytes from Embulk System Properties"

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/EmbulkRunner.java, embulk-core/src/main/java/org/embulk/config/ConfigLoader.java, embulk-core/src/main/java/org/embulk/exec/ExecModule.java, embulk-core/src/main/java/org/embulk/jruby/JRubyInitializer.java, embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java, embulk-core/src/main/java/org/embulk/spi/ExecSessionInternal.java, embulk-core/src/test/java/org/embulk/EmbulkTestRuntime.java
This is one of the steps to hide Jackson from plugins behind `embulk-deps`.
`ModelManager` is a wrapper of Jackson `ObjectMapper` for `org.embulk.config.*`, and it has been strongly coupled with Guice and many contents included in the Guice Injector. The first step of `ModelManager` is to separate it from Guice.
=> Manage ModelManager out of Guice

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/config/ConfigInject.java, embulk-core/src/main/java/org/embulk/config/ModelManager.java, embulk-core/src/main/java/org/embulk/config/TaskInvocationHandler.java, embulk-core/src/main/java/org/embulk/config/TaskSerDe.java, embulk-core/src/main/java/org/embulk/spi/util/LineEncoder.java, embulk-core/src/test/java/org/embulk/EmbulkTestRuntime.java, embulk-core/src/test/java/org/embulk/config/TestConfigLoader.java, embulk-junit4/src/main/java/org/embulk/test/EmbulkTests.java
`@ConfigInject` has been like `@Config` in plugin `Task`, but assigned a value from the Guice injector, not from the config. As explained in https://dev.embulk.org/topics/catchup-with-v0.10.html, it is removed.
Typical use-cases were `BufferAllocator` and `ScriptingContainer` (JRuby) like below.
```
interface PluginTask extends Task {
@Config("someConfig")
String getSomeConfig();
@ConfigInject
BufferAllocator getBufferAllocator();
@ConfigInject
ScriptingContainer getJRuby();
}
```
`BufferAllocator` can be now retrieved by `Exec.getBufferAllocator()`. JRuby `ScriptingContainer` is no longer available for plugins.
=> Stop handling @ConfigInject

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/config/ModelManager.java, embulk-core/src/main/java/org/embulk/exec/ExecModule.java, embulk-core/src/test/java/org/embulk/EmbulkTestRuntime.java, embulk-core/src/test/java/org/embulk/config/TestConfigLoader.java, embulk-junit4/src/main/java/org/embulk/test/EmbulkTests.java
As a preparation to move all Jackson Modules to `embulk-deps`, registering all Jackson Modules inside `org.embulk.config.ModelManager` to have references in a closed loop.
=> Register Jackson Modules inside ModelManager

embulk-core/src/main/java/org/embulk/config/ModelManager.java, embulk-core/src/main/java/org/embulk/config/PluginTypeJacksonModule.java, embulk-core/src/main/java/org/embulk/plugin/DefaultPluginType.java, embulk-core/src/main/java/org/embulk/plugin/MavenPluginType.java, embulk-core/src/main/java/org/embulk/plugin/PluginType.java, embulk-core/src/test/java/org/embulk/config/TestPluginType.java, embulk-core/src/test/java/org/embulk/config/TestPluginTypeSerDe.java, embulk-core/src/test/java/org/embulk/plugin/TestPluginTypeSerDe.java
It is a replacement from annotations to a SerDe Module for `org.embulk.plugin.PluginType`.
=> SerDe org.embulk.plugin.PluginType with a Jackson Module

embulk-core/src/main/java/org/embulk/config/ColumnConfigJacksonModule.java, embulk-core/src/main/java/org/embulk/config/ModelManager.java, embulk-core/src/main/java/org/embulk/config/SchemaConfigJacksonModule.java, embulk-core/src/main/java/org/embulk/spi/ColumnConfig.java, embulk-core/src/main/java/org/embulk/spi/SchemaConfig.java, embulk-core/src/test/java/org/embulk/spi/TestSchemaConfig.java
It is a replacement from annotations to a SerDe Module for `org.embulk.spi.ColumnConfig/SchemaConfig`.
=> SerDe org.embulk.spi.ColumnConfig and org.embulk.spi.SchemaConfig with Jackson Modules

embulk-core/src/main/java/org/embulk/config/ModelManager.java, embulk-core/src/main/java/org/embulk/config/TimestampFormatJacksonModule.java, embulk-core/src/main/java/org/embulk/spi/time/TimestampFormat.java
It is a replacement from annotations to a SerDe Module for `org.embulk.spi.time.TimestampFormat`.
=> SerDe TimestampFormat with a Jackson Module

embulk-core/src/main/java/org/embulk/config/ByteSizeJacksonModule.java, embulk-core/src/main/java/org/embulk/config/ModelManager.java, embulk-core/src/main/java/org/embulk/spi/unit/ByteSize.java
It is a replacement from annotations to a SerDe Module for `org.embulk.spi.unit.ByteSize`.
=> SerDe org.embulk.spi.unit.ByteSize with a Jackson Module

embulk-core/src/main/java/org/embulk/config/ModelManager.java, embulk-core/src/main/java/org/embulk/config/ResumeStateJacksonModule.java, embulk-core/src/main/java/org/embulk/exec/ResumeState.java
It is a replacement from annotations to a SerDe Module for `org.embulk.exec.ResumeState`.
=> SerDe org.embulk.exec.ResumeState with a Jackson Module

embulk-core/src/main/java/org/embulk/config/ModelManager.java, embulk-core/src/main/java/org/embulk/config/ProcessTaskJacksonModule.java, embulk-core/src/main/java/org/embulk/spi/ProcessTask.java
It is a replacement from annotations to a SerDe Module for `org.embulk.spi.ProcessTask`.
=> SerDe org.embulk.spi.ProcessTask with a Jackson Module

embulk-core/src/main/java/org/embulk/config/ConfigLoader.java, embulk-core/src/main/java/org/embulk/deps/config/ConfigLoaderDelegate.java, embulk-deps/src/main/java/org/embulk/deps/config/ConfigLoaderDelegateImpl.java
`ConfigLoader`, a big direct user of Jackson, is to load JSON/YAML into `ConfigSource`. It moves the main implementation to `embulk-deps` behind a sub class loader to hide Jackson from plugins.
=> Move ConfigLoader behind the embulk-deps DependencyClassLoader

embulk-deps/build.gradle, embulk-deps/gradle/dependency-locks/runtimeClasspath.lockfile
Guava (18.0) is already in the top-level class loader (`embulk-core`), then `embulk-deps` should not have Guava (also, it's 15.0!).
In fact, 0.10.32's `embulk-deps` should not have included Guice, too. (It's anyway removed in 0.10.32 at: https://github.com/embulk/embulk/pull/1444/files#diff-a0a01b2cd5bc9398f71f2c5e71d140d35a353e0a5b72605152be03718f78d971L35)
=> Remove Guava from embulk-deps

embulk-core/src/main/java/org/embulk/deps/SelfContainedJarAwareURLClassLoader.java
`DependencyClassLoader#findResources` (not `findResource`) could fail when `embulk-deps` was deployed directly on the file system, not embedded as self-contained JARs in Embulk's executable JAR.
* This problem does not affect normal OSS Embulk users. It could affect only for users who deploy JARs by themselves.
* This problem does not affect before v0.10.32 because `embulk-deps` did not include libraries calling `findResources`. It affected only v0.10.32.
This PR is to fix the problem by catching its related Exception(s).
=> Fix SelfContainedJarAwareURLClassLoader against "findResources" for non-self-contained embulk-deps

embulk-junit4/src/main/java/org/embulk/test/TestingEmbulk.java
`TestingEmbulk#runOutput` requires a CSV file as an input data source and the CSV file must have the header like `columnName:columnType,columnName:columnType,...`, but the csv parser setting does not include `skip_header_lines=1`, so I added.
=> Fix the TestingEmbulk#runOutput problem of not skipping the header even though the column name:type needs to be defined in the header.

build.gradle, embulk-core/src/main/resources/embulk/parent_first_packages.properties
`embulk-core` has not have `com.fasterxml.jackson.datatype.jdk8` in `parent_first_packages.properties` while :
* `parent_first_packages.properties` has had other `com.fasterxml.jackson.???`.
* `embulk-core` has had `jackson-datatype-jdk8` in dependencies until v0.10.31.
It has caused no problems when all "v0.10-ready" plugins are using only Jackson 2.6.7. But, `embulk-output-td` needed to use Jackson 2.8 and 2.9.
`embulk-output-td` has caught up with Embulk v0.10 API/SPI in its `0.8.0`, and it needed to have `jackson-datatype-jdk8` in addition.
* https://github.com/treasure-data/embulk-output-td/pull/111
----
By this addition, Embulk v0.9 - v0.10.31 loads `jackson-databind:2.6.7` from `embulk-core` while `embulk-output-td` tries to use its embedded `jackson-datatype-jdk8:2.9.10`. We …
=> Add com.fasterxml.jackson.datatype.jdk8 in parent first packages v0.10.31

embulk-core/src/main/java/org/embulk/spi/PageBuilderImpl.java
We observed a case that `PageBuilder(Impl)` threw `IllegalStateException("Not reach here")`.
* https://github.com/embulk/embulk/blob/v0.10.29.1/embulk-core/src/main/java/org/embulk/spi/PageBuilderImpl.java#L356-L378
To debug such a case more easily, this pull-request makes the Exception messages more descriptive.
=> Throw more descritive Exceptions from PageBuilder in case of type mismatch

embulk-core/src/main/java/org/embulk/deps/maven/MavenArtifactFinder.java, embulk-core/src/main/java/org/embulk/deps/maven/MavenPluginPaths.java, embulk-core/src/main/java/org/embulk/plugin/MavenPluginType.java, embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginRegistry.java, embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginSource.java, embulk-deps/src/main/java/org/embulk/deps/maven/MavenArtifactFinderImpl.java, embulk-deps/src/test/java/org/embulk/deps/config/TestPluginType.java, embulk-deps/src/test/java/org/embulk/deps/maven/TestMavenArtifactFinder.java
Users (especially ourselves) sometimes want to set a "default" plugin version from Embulk System Properties, while sometimes wanted to override the default version with another version.
Users can just override the default Properties, of course, but it often happens that their deployment tests things only with the "default" version, while the "overridden" version is not tested very well.
Even if they fail to load the overridden version, they often want to fallback to the default version, which is well tested.
----
This pull-request is realize such a want. For example, a user may set `plugins.default.input.s3=maven:org.embulk:0.5.2` and `plugins.input.s3=maven:org.embulk:0.6.0`.
Then, `0.6.0` is loaded if `maven:org.embulk:embulk-input-s3:0.6.0` exists in the deployment.
Otherwise if …
=> Fallback to "plugins.default.<category>.<type>" if no plugin is found from "plugins.<category>.<type>"

embulk-core/src/main/java/org/embulk/plugin/MavenPluginType.java, embulk-core/src/main/java/org/embulk/plugin/maven/MavenExcludeDependency.java, embulk-core/src/main/java/org/embulk/plugin/maven/MavenIncludeDependency.java, embulk-deps/src/main/java/org/embulk/deps/config/PluginTypeJacksonModule.java, embulk-deps/src/main/java/org/embulk/deps/maven/MavenArtifactFinderImpl.java, embulk-deps/src/test/java/org/embulk/deps/config/TestPluginType.java
This is an alternative to JDBC plugins' `driver_path` configuration built in Embulk's core.
Users sometimes want to switch plugin's dependencies at runtime, without hacking the plugin. This configuration allows users to switch with Maven artifact names.
For example,
```
type:
source: maven
group: org.embulk
name: mysql
version: 0.10.2
override_dependencies:
- mysql:mysql-connector-java:8.0.11
```
```
type:
source: maven
group: org.embulk
name: sqlserver
version: 0.10.2
exclude_dependencies:
- com.microsoft.sqlserver:mssql-jdbc
override_dependencies:
- net.sourceforge.jtds:jtds:1.3.1
```
=> Support `override_dependencies` and `exclude_dependencies` in Maven-based `type`

build.gradle, embulk-core/src/main/java/org/embulk/plugin/DefaultPluginType.java, embulk-core/src/main/java/org/embulk/plugin/MavenPluginType.java, embulk-core/src/main/java/org/embulk/plugin/SelfContainedPluginRegistry.java, embulk-core/src/main/java/org/embulk/plugin/SelfContainedPluginSource.java, embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginRegistry.java, embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginSource.java
The same as v0.10.29.1 and v0.10.31.1, we need to backport #1484 and #1486 for v0.10.32.
* https://github.com/embulk/embulk/releases/tag/v0.10.29.1
* https://github.com/embulk/embulk/releases/tag/v0.10.31.1
On the other hand, another backport such as v0.10.31.2 is not needed. 
* https://github.com/embulk/embulk/releases/tag/v0.10.31.2
It is because Jackson has already been cleaned up in v0.10.32.
* https://github.com/embulk/embulk/releases/tag/v0.10.32
=> Backport v0.10.32.1

build.gradle
Similar to https://github.com/embulk/embulk-input-gcs/pull/52. We basically trust Maven `.pom` files. Having two types of dependency declarations would cause confusions.
See: https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html#sub:disabling-gmm-publication
=> Disable publishing a Gradle Module Metadata

build.gradle, embulk-core/src/main/java/org/embulk/deps/SelfContainedJarAwareURLClassLoader.java
It backports #1467 to v0.10.32.
The issue was considered to be unrelated in v0.10.32 (as described in #1467), but actually, it affects when Embulk is called via `EmbulkEmbed`, not from a command-line.
=> Backport v0.10.32.2

embulk-ruby/build.gradle
This environment variable is necessary to avoid `gem install` error
on a Windows in GitHub Actions.
See also:
https://github.com/jruby/jruby/issues/7182
=> Add the environment variable to avoid gem install error in GitHub Actions.

build.gradle, embulk-core/src/main/java/org/embulk/deps/SelfContainedJarAwareURLClassLoader.java
It backports #1507 to v0.10.32 to reduce the noisy log in v0.10.32.
=> Backport v0.10.32.3

embulk-ruby/lib/embulk/java/imports.rb
This PR fixes #1501.
JRuby 9.3.0.0 `require 'jruby'` statement for plugin initialization.
This change doesn't change the current behavior.
```
embulk_test=# select * from inc_test;
id | name
----+-------
1 | apple
(1 row)
```
```yaml
in:
type: postgresql
host: localhost
user: user
password: password
database: embulk_test
table: inc_test
out:
type: stdout
```
```
% ./exe/multi-embulk -j 9.1.15.0 -e 0.10.36-SNAPSHOT run /tmp/test.yml
#####################################################
#
#
#####################################################
2022-04-22 21:14:23.514 +0900 [INFO] (main): embulk_home is set from command-line: /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.1.15.0
2022-04-22 21:14:23.518 +0900 [INFO] (main): m2_repo is set as a sub directory of embulk_home: …
```
=> Load/require 'jruby' explicitly in JRuby 9.3+ (Fix #1501)

embulk-core/src/main/java/org/embulk/deps/DependencyClassLoader.java, embulk-core/src/main/java/org/embulk/deps/EmbulkDependencyClassLoaders.java
This PR is not to look for self-contained JAR files (labelled `$embulk-deps$`) when dependencies are specified separately from `StaticInitializer.addDependency` or `StaticInitializer.addDependencies`.
=> Do not look for self-contained JAR files when dependencies are specified separately

build.gradle, embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/spi/ExecSessionInternal.java
This is an ad-hoc hotfix only for v0.10.31.3 to provide an option `EmbulkEmbed.Builder#keepMavenPluginSource()` so that Maven-based plugin classes are cached through multiple `EmbulkEmbed#guess,run,preview` calls.
=> Hotfix v0.10.31.3: Add an option for EmbulkEmbed to keep MavenPluginSource through EmbulkEmbed's lifetime

embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginRegistry.java
We found that #1481 (v0.10.35) broke the plugin class cache by #1484 (v0.10.34).
I believe that the plugin lookup mechanism should be totally refactored as filed in #1485, so that we can avoid this kind of bugs in the future. But as of now, let me fix just this before #1448, the planned next big removal.
=> Fix caching in MavenPluginRegistry

embulk-deps/build.gradle, embulk-deps/src/test/java/org/embulk/deps/config/TestConfigSource.java
Those test cases will no longer work because Guava was removed, then they should have been removed.
It was not detected in https://github.com/embulk/embulk/pull/1448 because EmbulkTestRuntime was not working well at the base of the pull request.
EmbulkTestRuntime got fixed in https://github.com/embulk/embulk/pull/1518 for v0.10.37, then the issue was revealed after merging the pull request.
=> Remove ConfigSource tests for jackson-datatype-guava

build.gradle, embulk-core/build.gradle, embulk-junit4/build.gradle
* Removing "exclude guava" in a dependency to "embulk-deps" for the executable binary.
* Commenting to remove Guava from "embulk-core" test dependencies.
* Re-adding Guava in "embulk-junit4" dependencies, which was just "compileOnly" because "embulk-core" had Guava.
=> Clean up and comment on Guava dependencies

embulk-ruby/lib/embulk/error.rb
Hello, @dmikurube 
1. This PR relates to #1505. Could you tell me how to create this PR?
2. Does this comment is sufficient explanation?
As of JRuby 9.3, subclassing a Java classes are full java classes, which introduces some restrictions:
See details:
https://github.com/jruby/jruby/wiki/CallingJavaFromJRuby#subclassing-a-java-class
https://github.com/jruby/jruby/issues/7221
=> Use single super statement (Fix #1513)

embulk-core/src/main/java/org/embulk/jruby/LazyScriptingContainerDelegate.java
This PR outputs log the JRuby version Fix #1521
embulk run
```
2022-12-09 11:22:10.411 +0900 [INFO] (0001:transaction): Loaded JRuby 9.4.0.0 Compatible MRI: 3.1.0
```
embulk gem
```
2022-12-09 11:24:36.747 +0900 [INFO] (main): Loaded JRuby 9.4.0.0 Compatible MRI: 3.1.0
```
=> Log the version of the loaded JRuby instance. (Fix #1521)

embulk-junit4/build.gradle, embulk-junit4/gradle/dependency-locks/compileClasspath.lockfile, embulk-junit4/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-junit4/src/main/java/org/embulk/test/EmbulkTests.java, embulk-junit4/src/main/java/org/embulk/test/PreviewResultInputPlugin.java, embulk-junit4/src/main/java/org/embulk/test/TestingEmbulk.java
Follow-up to #1448 in v0.10.39 to clean up remaining Guava in `embulk-junit4` in a following veresion.
=> Remove Guava from embulk-junit4

embulk-core/build.gradle, embulk-core/src/test/java/org/embulk/spi/TestFileInputRunner.java, embulk-core/src/test/java/org/embulk/spi/TestFileOutputRunner.java, embulk-core/src/test/java/org/embulk/spi/TestInputStreamFileInput.java, embulk-core/src/test/java/org/embulk/spi/TestUtils.java, embulk-core/src/test/java/org/embulk/spi/util/TestLineDecoder.java
Follow-up to #1448 in v0.10.39 to clean up remaining Guava in `embulk-core:tests` in a following veresion.
=> Remove Guava from embulk-core tests

embulk-api/src/main/java/org/embulk/config/DataSource.java, embulk-deps/src/main/java/org/embulk/deps/config/DataSourceImpl.java, embulk-deps/src/test/java/org/embulk/deps/config/TestConfigSource.java
Since v0.10.32, we have split the core Jackson, and plugin's Jackson. It had caused some compatibility issues even if the plugin has "caught up".
For example, if a plugin calls `ConfigDiff#get()` like below, it stopped working.
```
configDiff.get(JsonNode.class, "attributes");
```
The `configDiff` object is based on the core Jackson, and `JsonNode.class` in the first parameter is plugin's Jackson. The core Jackson does not recognize plugin's Jackson.
Plugin developers sometimes had to do like this because the `org.embulk.config.DataSource` interface was poor. There were no way to retrieve an arbitrary tree node from `DataSource`. Then, we had to get the background `JsonNode` from `DataSource` (`ConfigDiff`).
----
This pull request tries to mitigate this problem by making `DataSource` more …
=> Add methods in org.embulk.config.DataSource to handle Lists and Maps (nested attributes) better

embulk-api/build.gradle, embulk-api/gradle/dependency-locks/compileClasspath.lockfile, embulk-api/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-core/gradle/dependency-locks/compileClasspath.lockfile, embulk-core/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-deps/gradle/dependency-locks/compileClasspath.lockfile, embulk-junit4/gradle/dependency-locks/compileClasspath.lockfile, embulk-junit4/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-spi/gradle/dependency-locks/compileClasspath.lockfile, embulk-spi/gradle/dependency-locks/runtimeClasspath.lockfile
Embulk's "JSON"-type values have been represented by msgpack-java's `org.msgpack.value.(Immutable)Value` since Embulk v0.7. The msgpack-java has set its roots deep inside Embulk, including its plugin SPI method signatures.
It has brought a heavy dependency hell between Embulk and msgpack-java. We have hesitated even just upgrading `msgpack-core` which can potentially cause a compatibility issue. As a result, a couple of plugins that use `msgpack-core` (such as `embulk-parser-msgpack`) had to stay with older `msgpack-core`. Keeping it old is definitely bad. 
The Embulk v0.10 "development" series is a good chance to catch-up. Let's upgrade `msgpack-core` to 0.8.24, which is the latest v0.8 -- said to be still "compatible" expectedly.
However, msgpack-java v0.9 added a support for a new …
=> Upgrade msgpack-core to 0.8.24

embulk-api/build.gradle, embulk-api/src/main/java/org/embulk/spi/json/JsonArray.java, embulk-api/src/main/java/org/embulk/spi/json/JsonBoolean.java, embulk-api/src/main/java/org/embulk/spi/json/JsonDecimal.java, embulk-api/src/main/java/org/embulk/spi/json/JsonInteger.java, embulk-api/src/main/java/org/embulk/spi/json/JsonNull.java, embulk-api/src/main/java/org/embulk/spi/json/JsonObject.java, embulk-api/src/main/java/org/embulk/spi/json/JsonString.java, embulk-api/src/main/java/org/embulk/spi/json/JsonValue.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonArray.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonBoolean.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonDecimal.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonInteger.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonNull.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonObject.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonString.java
Embulk's "JSON"-type values have been represented by msgpack-java's `org.msgpack.value.(Immutable)Value` since Embulk v0.7. The msgpack-java has set its roots deep inside Embulk, including its plugin SPI method signatures.
It has brought a heavy dependency hell between Embulk and msgpack-java. We have hesitated even just upgrading `msgpack-core` which can potentially cause a compatibility issue. As a result, a couple of plugins that use `msgpack-core` (such as `embulk-parser-msgpack`) had to stay with older `msgpack-core`.
We upgraded `msgpack-core` to 0.8.24 in #1459, in the Embulk v0.10 "development" series.
However, indeed, the Embulk core has never used `MessagePacker` nor `MessageUnpacker` from `msgpack-core`. Embulk has used only `org.msgpack.value.(Immutable)Value` just as a …
=> Add org.embulk.spi.json.JsonValue to deprecate use of msgpack-core in embulk-api

embulk-api/src/main/java/org/embulk/spi/json/JsonArray.java, embulk-api/src/main/java/org/embulk/spi/json/JsonBoolean.java, embulk-api/src/main/java/org/embulk/spi/json/JsonDecimal.java, embulk-api/src/main/java/org/embulk/spi/json/JsonInteger.java, embulk-api/src/main/java/org/embulk/spi/json/JsonNull.java, embulk-api/src/main/java/org/embulk/spi/json/JsonObject.java, embulk-api/src/main/java/org/embulk/spi/json/JsonString.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonArray.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonBoolean.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonDecimal.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonInteger.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonNull.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonObject.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonString.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonArray.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonBoolean.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonDecimal.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonInteger.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonNull.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonObject.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonString.java
It is a follow-up to: #1462
#1462 was not very clear about equality (`#equals(Object)`). If a developer defines their own `JsonValue` subclass, the new class may behave inconsistent with the "standard" `JsonValue` classes. Some are `true`, some are `false`, and some throw an Exception. The second commit 1f248a9c59e8bceb7b78c3e4b79459399968bc0d tests it, and confirms it fails.
This pull request clarifies the behavior of `#equals(Object)`. The standard `JsonValue` classes should not be "equal" to any non-standard `JsonValue` subclass. The third commit bb3f497bf155ae788c8a4f4a3a43490617a96d70 fixes `#equals(Object)`, and confirms it passes.
Its corresponding EEP is draft at https://github.com/embulk/embulk/pull/1538.
=> Clarify the equality of JsonValue implementations

embulk-api/src/main/java/org/embulk/spi/json/JsonArray.java, embulk-api/src/main/java/org/embulk/spi/json/JsonBoolean.java, embulk-api/src/main/java/org/embulk/spi/json/JsonDouble.java, embulk-api/src/main/java/org/embulk/spi/json/JsonLong.java, embulk-api/src/main/java/org/embulk/spi/json/JsonNull.java, embulk-api/src/main/java/org/embulk/spi/json/JsonObject.java, embulk-api/src/main/java/org/embulk/spi/json/JsonString.java, embulk-api/src/main/java/org/embulk/spi/json/JsonValue.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonArray.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonBoolean.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonDouble.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonLong.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonNull.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonObject.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonString.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonArray.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonBoolean.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonDouble.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonLong.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonNull.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonObject.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonString.java
It is a follow-up to: #1462
`PageBuilder` has had a mechanism to estimate size of each record in order to make decisions when to "flush" the `PageBuilder` to `Page`. But, it has been just assumed as `256` for JSON columns.
https://github.com/embulk/embulk/blob/v0.10.41/embulk-core/src/main/java/org/embulk/spi/PageBuilderImpl.java#L181
Introducing the new `JsonValue` is a good chance to make it better. `JsonValue#presumeReferenceSizeInBytes` is the mechanism to presume the approximate size.
=> Add JsonValue#presumeReferenceSizeInBytes to presume an approximate size to be occupied in Page

embulk-api/src/main/java/org/embulk/spi/json/JsonValue.java
It is a follow-up to: #1462
It's simple. As `Object#equals` exists already, we don't need `JsonValue#equals`. It came from `equals` in msgpack-java's `Value`.
=> Remove JsonValue#equals because it's in java.lang.Object

embulk-api/src/main/java/org/embulk/spi/json/JsonNull.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonNull.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonNull.java
It is a follow-up to: #1462 
It is just to make `JsonNull` consistent with `JsonBoolean` which has `FALSE` and `TRUE` as constants.
=> Define a public constant NULL in JsonNull

embulk-api/src/main/java/org/embulk/spi/json/JsonString.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonString.java
Follow-up to: #1462 
I at first used `String#intern()` forcibly when creating `JsonString` to save memory, but at the same time, it needs time to `String#intern()`.
It should be plugin developer's choice. Going to remove the `intern()`.
=> Stop String#intern when instantiating JsonString

embulk-api/src/main/java/org/embulk/spi/json/JsonObject.java, embulk-api/src/main/java/org/embulk/spi/json/JsonString.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonObject.java
`JsonObject` started from a single array containing both keys and values because it started from a clone of msgpack-java's [`ImmutableMapValueImpl`](https://github.com/msgpack/msgpack-java/blob/v0.8.24/msgpack-core/src/main/java/org/msgpack/value/impl/ImmutableMapValueImpl.java).
But, unlike msgpack-java's `MapValue` taking any `Value` as a key, `JsonObject` takes only strings as a key. It would be more reasonable and straightforward to have `JsonObject`'s keys as plain `String`s.
It does not change any behavior observed from outside. No changes in tests, then.
=> Represent JsonObject's internal keys by String, not JsonString

embulk-api/src/main/java/org/embulk/spi/json/JsonString.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonString.java
`JsonString` should not be created with `null`.
=> Check null specified for JsonString

embulk-api/src/main/java/org/embulk/spi/json/JsonArray.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonArray.java
`JsonArray` should not be created with `null`.
=> Check null specified for JsonArray

embulk-api/src/main/java/org/embulk/spi/json/JsonObject.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonObject.java
It just adds a lot of convenient creator methods `JsonObject.of(String, JsonValue, ...)` that are similar to `Map` in Java 9+.
https://docs.oracle.com/javase/9/docs/api/java/util/Map.html
=> Add JsonObject#of(...) methods

embulk-api/src/main/java/org/embulk/spi/json/JsonObject.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonObject.java
`JsonObject` should not be created with `null`.
=> Check null specified for JsonObject

embulk-api/src/main/java/org/embulk/spi/json/JsonDouble.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonDouble.java
First, `JsonDouble` had a bug that it checked in `*ValueExact()` in an opposite way. Changed them to use `is*Value()` to check. Added tests for it and more first, then fixed it.
Second, `JsonDouble` accepted NaN and the infinity although the original JSON format does not have definitions of NaN or the infinity. `BigInteger` and `BigDecimal` do not support NaN nor the infinity on the other hand, then `#bigIntegerValue(Exact)` and `#bigDecimalValue` would have needed some special handling. After some thoughts, we concluded that `JsonDouble` should not accept NaN nor the infinity.
Embulk's `DOUBLE` column type accepts NaN and the infinity, indeed. They would not be interoperable at that point, but introducing NaN or the infinity in JSON would be more confusing. We may …
=> Fix cases of JsonDouble, and reject NaN and the infinity

embulk-api/src/main/java/org/embulk/spi/json/JsonArray.java, embulk-api/src/main/java/org/embulk/spi/json/JsonBoolean.java, embulk-api/src/main/java/org/embulk/spi/json/JsonDouble.java, embulk-api/src/main/java/org/embulk/spi/json/JsonLong.java, embulk-api/src/main/java/org/embulk/spi/json/JsonNull.java, embulk-api/src/main/java/org/embulk/spi/json/JsonObject.java, embulk-api/src/main/java/org/embulk/spi/json/JsonString.java, embulk-api/src/main/java/org/embulk/spi/json/JsonValue.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonArray.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonBoolean.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonDouble.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonLong.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonNull.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonObject.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonString.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonArray.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonBoolean.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonDouble.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonLong.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonNull.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonObject.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonString.java
This is the step 3 in the draft EEP: JSON Column Type: #1538 
> "Modify the new JSON classes to represent their inner values by msgpack-java"
`#toMsgpack()` is used only for running with the existing methods in `Page`, `PageBuilder`, `PageReader`. It will be reverted when we finally remove msgpack-java from the Embulk SPI after v1.0.
=> Change JsonValue classes to back with msgpack-java classes

embulk-api/src/main/java/org/embulk/spi/json/JsonArray.java, embulk-api/src/main/java/org/embulk/spi/json/JsonDouble.java, embulk-api/src/main/java/org/embulk/spi/json/JsonLong.java, embulk-api/src/main/java/org/embulk/spi/json/JsonObject.java, embulk-api/src/main/java/org/embulk/spi/json/JsonString.java, embulk-api/src/main/java/org/embulk/spi/json/JsonValue.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonArray.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonBoolean.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonDouble.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonLong.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonNull.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonObject.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonString.java
This is the step 3, and preparation for the step 4, in the draft EEP: JSON Column Type: #1538
> 3. "Modify the new JSON classes to represent their inner values by msgpack-java"
> 4. Add new Embulk plugin SPI methods with the new JSON classes in parallel to the existing methods
`JsonValue#fromMsgpack()` is used only for creating `JsonValue` when received a msgpack-java `Value` from plugins. It will be reverted when we finally remove msgpack-java from the Embulk SPI after v1.0.
=> Implement JsonValue#fromMsgpack

embulk-api/src/main/java/org/embulk/spi/json/JsonDouble.java, embulk-api/src/main/java/org/embulk/spi/json/JsonLong.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonDouble.java, embulk-api/src/test/java/org/embulk/spi/json/FakeJsonLong.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonDouble.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonLong.java
In terms of the `JSON` context, `JsonLong.of(12345L)` should be "equal" to `JsonDouble.of(12345.0)` because both are "JSON numbers".
=> Let JsonLong and JsonDouble can be "equal" when JsonDouble is integral

embulk-api/src/main/java/org/embulk/spi/json/JsonDouble.java, embulk-api/src/main/java/org/embulk/spi/json/JsonLong.java, embulk-api/src/main/java/org/embulk/spi/json/JsonString.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonDouble.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonLong.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonObject.java, embulk-api/src/test/java/org/embulk/spi/json/TestJsonString.java
`#presumeReferenceSizeInBytes()` should include the size of `literal` in `JsonLong`, `JsonDouble`, and `JsonString` because `literal` consumes the Java heap.
=> Add the size of literal in presumeReferenceSizeInBytes() of JsonLong, JsonDouble, and JsonString

.github/workflows/check.yml
Current github actions workflows show warning:
* Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-java@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
* The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
See https://github.com/embulk/embulk/actions/runs/4060013260
Update to the latest plugin version
Just the github actions
Revert this PR
=> Update checkout and setup-java to v3

embulk-api/src/main/java/org/embulk/spi/Page.java, embulk-api/src/main/java/org/embulk/spi/PageBuilder.java, embulk-api/src/main/java/org/embulk/spi/PageReader.java, embulk-core/src/main/java/org/embulk/spi/PageBuilderImpl.java, embulk-core/src/main/java/org/embulk/spi/PageImpl.java, embulk-core/src/main/java/org/embulk/spi/PageReaderImpl.java, embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/PagePrinter.java, embulk-core/src/main/java/org/embulk/spi/util/Pages.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/AbstractDynamicColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/BooleanColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/DoubleColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/JsonColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/LongColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/SkipColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/StringColumnSetter.java, embulk-core/src/main/java/org/embulk/spi/util/dynamic/TimestampColumnSetter.java
This is almost the last step 4 in the draft EEP: JSON Column Type: #1538
> 4. Update `Page`, `PageBuilder`, and `PageReader` to represent JSON values by the new JSON classes, along with :
>     * Adding new Embulk plugin SPI methods with the new JSON classes in parallel to the existing methods
>         * Existing :
>             * `org.embulk.spi.Page`
>                 * `Page setValueReferences(List<org.msgpack.value.ImmutableValue>)`
>                 * `List<org.msgpack.value.ImmutableValue> getValueReferences()`
>                 * `org.msgpack.value.ImmutableValue getValueReference(int)`
>             * `org.embulk.spi.PageBuilder`
>                 * `void setJson(int, org.msgpack.value.Value)`
>                 * `void setJson(Column, org.msgpack.value.Value)`
>             * …
=> Use JsonValue in Page, PageBuilder, and PageReader, instead of org.msgpack.value.Value

build.gradle, embulk-api/build.gradle, embulk-api/gradle/dependency-locks/compileClasspath.lockfile, embulk-api/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-core/gradle/dependency-locks/compileClasspath.lockfile, embulk-core/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-deps/gradle/dependency-locks/compileClasspath.lockfile, embulk-junit4/build.gradle, embulk-junit4/gradle/dependency-locks/compileClasspath.lockfile, embulk-junit4/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-spi/gradle/dependency-locks/compileClasspath.lockfile, embulk-spi/gradle/dependency-locks/runtimeClasspath.lockfile
Let's update SLF4J and Logback to the (available) latest before we go into Embulk v0.11!
SLF4J v2.0 should basically have a compatible interface with SLF4J v1.7, just with :
* Fluent logging interface in addition, and
* Better support for Java 9+ modules (Jigsaw).
Logback needs to be updated to v1.3 to follow. (I believe that v1.3 will work with Java 9+ whiel v1.4 does not work with Java 8.)
Plugins should be depending on `embulk-api` just with `compileOnly`. The actual SLF4J and Logback artifacts are bundled only with the Embulk executable binary. The dependency on `embulk-api` from plugins should not be a big problem.
=> Upgrade embulk-api's slf4j-api to 2.0.6, and executable's logback-classic to 1.3.5

build.gradle
It should have been updated in v0.10.43, but overlooked.
=> Update links to the slf4j-api Javadoc

build.gradle
The `embulk-plugins` Gradle plugin has been no longer used after the standards plugins were moved to: https://github.com/embulk/embulk-standards
=> Remove the Gradle embulk-plugins plugin from build

embulk-deps/build.gradle, embulk-deps/gradle/dependency-locks/compileClasspath.lockfile, embulk-deps/gradle/dependency-locks/runtimeClasspath.lockfile, embulk-deps/src/main/java/org/embulk/deps/cli/CommandLineImpl.java
JLine has been included in Embulk since v0.10.20 along with refactoring the command line parser.
See pull request: #1333
We, however, do not see a big benefit to keep it. It is not critical, but taking a certain amount in Embulk's executable size. Let's remove it.
We may get it back if we receive many requests to do it again in the future.
=> Remove JLine

.github/workflows/check.yml, build.gradle
`META-INF/INDEX.LIST` and `META-INF/versions/9/module-info.class` have conflicted in the executable all-in-one JAR file. Gradle 7+ started to fail when there is a conflict in building a JAR file.
Better not to have a conflict in the JAR file, anyway.
They can be just removed while Embulk basically expects Java 8.
=> Remove conflicts in the executable all-in-one JAR file

build.gradle, embulk-core/build.gradle, embulk-core/gradle.lockfile, embulk-deps/build.gradle, embulk-junit4/build.gradle
The compiled class files of "embulk-spi" are mixed into the "embulk-core" JAR file, and the "embulk-core" Maven artifact has the dependency on "embulk-spi" as "provided" in pom.xml.
The artifacts are structured like this so that they can bypass the restriction of Java (9+) Module System that multiple JAR files (modules) cannot contain the same Java package classes.
This mixing is not necessary when using Embulk with the executable all-in-one binary. But, it would not work well with Java 9+ in case of using Embulk with self-hosted deployment of the separated artifacts, embulk-spi, embulk-core, and else.
----
With this change, `embulk-core`'s `pom.xml` would be like following:
```xml
<dependencies>
<dependency>
<groupId>org.slf4j</groupId>
<artifactId>slf4j-api</artifactId> …
```
=> Mix embulk-spi's classes into embulk-core

embulk-core/src/main/java/org/embulk/EmbulkDependencyClassLoader.java, embulk-core/src/main/java/org/embulk/cli/ByteBufferInputStream.java, embulk-core/src/main/java/org/embulk/cli/JarEmbeddedUrlStreamHandler.java, embulk-core/src/main/java/org/embulk/cli/Main.java, embulk-core/src/main/java/org/embulk/cli/Resource.java, embulk-core/src/main/java/org/embulk/cli/SelfContainedJarAwareURLClassLoader.java, embulk-core/src/main/java/org/embulk/cli/SelfContainedJarFile.java, embulk-core/src/main/java/org/embulk/cli/SelfContainedJarFiles.java, embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java, embulk-core/src/main/java/org/embulk/plugin/SelfContainedPluginRegistry.java, embulk-core/src/main/java/org/embulk/plugin/jar/JarPluginLoader.java
Wanted not to have classes under org.embulk.deps in embulk-core, for the same motivation with #1589, #1590, #1591, and #1592.
"Self-contained JAR files" are used for the all-in-one executable JAR file, then those classes are used with CLI, therefore nice to locate them in `org.embulk.cli`.
=> Move classes about self-contained JAR files to org.embulk.cli

build.gradle, embulk-core/src/main/bat/selfrun.bat, embulk-core/src/main/sh/selfrun.sh
The plan for Embulk v0.11.0 is announced: https://www.embulk.org/articles/2023/04/13/embulk-v0.11-is-coming-soon.html
To get this reached out for more users, I think about releasing v0.9.25 as `embulk-latest.jar` with a warning message.
=> Warn for v0.11.0 in v0.9.25 as embulk-latest.jar

docs/eeps/eep-0001.md, docs/eeps/eep-0002.md, docs/eeps/eep-0003.md, docs/eeps/eep-0004.md, docs/eeps/eep-0005.md, docs/eeps/eep-0006.md
The "Created" date of an EEP has not been very clear. It may be the date of the first draft, the date of getting ready for review, or the date of publishing.
This pull request changes "Created" to "Published" so that the date would be clear. The "Published" date would be the date when an EEP number is assigned after being reviewed, and the EEP gets effective.
=> Change EEP's "Created" to "Published"

embulk-core/src/main/java/org/embulk/exec/PreviewValueFormatter.java
preview command is failed when values have a Boolean value.
Because PreviewValueFormatter can't accept Boolean object.
This PR fixes it.
=> Fix PreviewValueFormatter that can't accept Boolean value

embulk-core/src/test/java/org/embulk/exec/TestPreviewValueFormatter.java
A follow-up to #1630 to add some test cases for `PreviewValueFormatter`.
=> Test PreviewValueFormatter

embulk-core/src/main/java/org/embulk/spi/json/JsonParser.java
`org.embulk.spi.json.JsonParser` is deprecated, and we may remove it in the future. Let's dump a duplication message for use of that.
=> Warn against use of org.embulk.spi.json.JsonParser

docs/eeps/draft-new-plugin-tests-with-junit5.md
This draft EEP summarizes a design of the new Embulk plugin testing framework with JUnit 5.
It still has some missing links, such as:
* How to avoid requiring other Embulk plugins to test the target Embulk plugin?
* How to provide the test input, and check the results?
* ...
However, implementing it would need some time, and the design may change through implementation.
If the design so far seems okay with the Core Team, I wanted to merge this EEP still as "Draft", and to revisit it later along with implementation.
=> Draft EEP: Testing Embulk plugins with JUnit 5

.github/workflows/check.yml
Temurin OpenJDK 8 is unavailable in `macos-latest` (Apple M1 / aarch64).
https://github.com/actions/setup-java/issues/625
=> Use macos-13 in GitHub Actions

build.gradle
Its `build.gradle` has had the `:checkDependencies` task to check dependencies (to fail when dependencies are invalid), but it has not iterated over subprojects. It was not very convenient.
This pull request makes the `:chedkDependencies` task to iterate over all subprojects.
(Note: we may consider applying this to other repositories, but only in this repository as of now. We may find another better approach.)
=> Set the ":checkDependencies" task to check for all projects

docs/eeps/eep-0000.md
We didn't have an index for EEPs while we now have 10 EEPs. It's inconvenient when we look into published EEPs.
Like [Python's PEP-0](https://peps.python.org/pep-0000/), it'd be nice to have EEP-0 as the index.
=> EEP-0: Index of Embulk Enhancement Proposals (EEPs)

docs/eeps/eep-0003.md, docs/eeps/eep-0005.md, docs/eeps/eep-0007.md
Forgot to update the `Post-History` headers of the updated EEPs in #1675 
(`Post-History` is explained in https://github.com/embulk/embulk/blob/master/docs/eeps/eep-0001.md#eep-header-preamble )
=> Update the "Post-History" headers of updated EEPs

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java, embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java, embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderFactoryImpl.java, embulk-core/src/main/java/org/embulk/spi/ExecSessionInternal.java, embulk-core/src/main/resources/embulk/parent_first_packages.properties, embulk-core/src/main/resources/embulk/parent_first_resources.properties, embulk-junit4/src/main/java/org/embulk/test/EmbulkTestRuntime.java
`parent_first_packages.properties` and `parent_first_resources.properties` have been used to suppress some classes from being loaded by plugin class loaders. However, it was not working properly, then we have planned to remove this mechanism, as declared in EEP-9:
https://github.com/embulk/embulk/blob/master/docs/eeps/eep-0009.md#parent_first_packages-and-parent_first_resources
The time has come. As the first step, this pull request removes those files, and hard-code them directly in `PluginClassLoader`.
----
In addition, we needed `PluginClassLoader` to be more flexible so that the class loading mechanism could work with testing a plugin, hopefully with a new test helper `embulk-junit5`.
=> Discard "parent_first_*.properties" files, and hard-code them in PluginClassLoader

embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java, embulk-core/src/test/java/org/embulk/plugin/TestPluginClassLoader.java
To be prepared for changing the logic of "parent_first", adding tests to detect unexpected behaviors.
=> Test PluginClassLoader.isParentFirstPackage and PluginClassLoader.isParentFirstPath

embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java
This may seem like a stupid change, but intentional. I am going to make another change to check not only with `startsWith`, but some more detailed check. This is a preparation for the change.
=> Hard-code PluginClassLoader.isParentFirstPackage and isParentFirstPath

embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java, embulk-core/src/test/java/org/embulk/plugin/TestPluginClassLoader.java
Resources under `msgpack/` have been included in "parent_first", but actually, the existing `msgpack-core` does not contain any resource under `msgpack/`, then the Embulk packages does not include any resource under `msgpack/`.
It's no longer needed. Let's remove it.
=> Exclude "msgpack/" resources from "parent_first"

embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java
In implementing a new testing framework for Embulk plugins, we needed a way to load a specified class forcibly in `PluginClassLoader`, with ignoring the parent class loader.
This is only a helper method for the testing framework.
=> Add PluginClassLoader#loadClassInThisClassLoader, for internal use

embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java
Found that the comment in `PluginClassLoader#loadClass(String, boolean)` was wrong.
`ClassLoader#findLoadedClass(String)` does not find the class from its parent class loader indeed. I confirmed it at: https://gist.github.com/dmikurube/ac1480b4eeaf5e925ead3aec719a5441
=> Fix the comment on ClassLoader#findLoadedClass(String) in PluginClassLoader

docs/eeps/eep-0007.md, docs/eeps/eep-0012.md, docs/eeps/eep-0013.md
Found that the `Published:` fields were missing in some EEPs (including the recent EEP-13). ;)
=> Fix EEP "Published" dates for EEP-7, EEP-12, and EEP-13
