README.md

fix gem name "embulk-plugin-postgres-json"

Fix gem name.

---

embulk-core/src/main/java/org/embulk/exec/LocalExecutor.java
embulk-core/src/main/java/org/embulk/jruby/JRubyPluginSource.java
embulk-core/src/main/java/org/embulk/spi/FilterPlugin.java
embulk-core/src/main/java/org/embulk/spi/util/Filters.java
lib/embulk/command/embulk_run.rb
lib/embulk/data/bundle/embulk/filter_example.rb
lib/embulk/filter_plugin.rb
lib/embulk/java/imports.rb
lib/embulk/plugin.rb

This changes add FilterPlugin SPI to Java and JRuby. #26

Adding filter plugin

---

lib/embulk/page.rb

We have already implement Page#each.
So, we could use other convenient methods if including Enumerable.

Add Enumerable behavior to Page

---

embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java
lib/embulk/command/embulk_example.rb

This change also changes configuration parameter 'paths' to 'path_prefix'.
Fixes #48

Implement last_path to LocalFileInputPlugin

---

embulk-standards/src/main/java/org/embulk/standards/LocalFileOutputPlugin.java

* Before: directory + "/" + file_name + ".%03d.%02d" + file_ext
* After: path_prefix + sequence_format + file_ext

LocalFileOutputPlugin uses path_prefix, file_ext and sequence_format config parameters

---

embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java
lib/embulk/guess_csv.rb

This change makes CsvParserPlugin more flexible.

CsvParserPlugin accepts more values as true

---

lib/embulk/data/new/ruby/filter.rb.erb
lib/embulk/data/new/ruby/gemspec.erb
lib/embulk/data/new/ruby/input.rb.erb

fix ERB templates

---

build.gradle
embulk-core/build.gradle

Gradle 'release' task actually releases jars to Bintray and RubyGems

---

embulk-core/src/main/java/org/embulk/exec/PreviewExecutor.java

exec.PreviewExecutor runs filter plugins

---

lib/embulk/data_source.rb
lib/embulk/guess_plugin.rb

Guess encoding fix

---

embulk-core/src/main/java/org/embulk/exec/GuessExecutor.java
embulk-core/src/main/java/org/embulk/exec/LocalExecutor.java
embulk-core/src/main/java/org/embulk/exec/LoggerProvider.java
embulk-core/src/main/java/org/embulk/exec/PreviewExecutor.java
embulk-core/src/main/java/org/embulk/exec/SetCurrentThreadName.java
lib/embulk/command/embulk_run.rb

include processor index to log messages

---

embulk-core/src/main/java/org/embulk/exec/PreviewExecutor.java
embulk-core/src/main/java/org/embulk/spi/Exec.java
embulk-core/src/main/java/org/embulk/spi/ExecSession.java

added Exec.isPreview()

---

README.md

from [embulk-plugin-postgres-json] to [embulk-output-postgres-json]

Fix gem name

---

lib/embulk/buffer.rb
lib/embulk/command/embulk_run.rb
lib/embulk/data/new/ruby/filter.rb.erb
lib/embulk/data/new/ruby/formatter.rb.erb
lib/embulk/data/new/ruby/output.rb.erb
lib/embulk/data/new/ruby/parser.rb.erb
lib/embulk/file_input.rb
lib/embulk/file_output.rb
lib/embulk/formatter_plugin.rb
lib/embulk/parser_plugin.rb
lib/embulk/plugin.rb

This pull-request adds `#read` method to #90.

Add IO interface to Embulk::FileInput

---

lib/embulk/buffer.rb
lib/embulk/command/embulk_run.rb
lib/embulk/data/new/ruby/filter.rb.erb
lib/embulk/data/new/ruby/formatter.rb.erb
lib/embulk/data/new/ruby/output.rb.erb
lib/embulk/data/new/ruby/parser.rb.erb
lib/embulk/file_input.rb
lib/embulk/file_output.rb
lib/embulk/formatter_plugin.rb
lib/embulk/parser_plugin.rb
lib/embulk/plugin.rb

For #34. This pull-request assumes #90.

Ruby formatter plugin

---

embulk-core/src/main/java/org/embulk/exec/GuessExecutor.java
embulk-core/src/main/java/org/embulk/exec/SamplingParserPlugin.java
embulk-core/src/main/java/org/embulk/spi/ExecSession.java
embulk-core/src/main/java/org/embulk/spi/FileInputRunner.java
embulk-core/src/main/java/org/embulk/spi/InputPlugin.java
lib/embulk/command/embulk_run.rb
lib/embulk/input_plugin.rb

added InputPlugin.guess

---

lib/embulk/column.rb
lib/embulk/guess/csv.rb
lib/embulk/guess/schema_guess.rb
lib/embulk/schema.rb
test/guess/test_schema_guess.rb
test/helper.rb

added SchemaGuess to make guess implementation easy

---

lib/embulk/command/embulk_new_plugin.rb
lib/embulk/data/new/README.md.erb
lib/embulk/data/new/ruby/decoder_guess.rb.erb
lib/embulk/data/new/ruby/parser_guess.rb.erb

This pull-request generates guess plugin template if the generating type is parser or decoder.

Generates guess plugin template for parser and decoder plugins

---

embulk-core/src/main/java/org/embulk/spi/util/FileOutputOutputStream.java

Please see https://github.com/embulk/embulk/pull/141

Increase buffer size of FileOutputOutputStream

---

embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java
embulk-standards/src/main/java/org/embulk/standards/CsvTokenizer.java

CsvParserPlugin stupidly ignores all exceptions. But it should catch only CsvTokenizer exceptions.

CsvParserPlugin should not ignore all exceptions #147

---

embulk-docs/src/customization.rst
embulk-docs/src/index.rst

I wrote a document for plugin development.

Added document for plugin development

---

README.md
embulk-docs/src/built-in.rst
embulk-docs/src/customization.rst
embulk-docs/src/recipe/scheduled-csv-load-to-elasticsearch-kibana4.rst

- correct misspellings
- correct Ubuntu version

Fix document

---

lib/embulk/plugin_registry.rb

show loaded plugin name and version to stdout

---

lib/embulk/command/embulk_run.rb

Gem.ruby fix

---

embulk-core/src/main/java/org/embulk/spi/ProcessTask.java

Workaround for https://github.com/embulk/embulk-executor-mapreduce/issues/1

ProcessTask uses SchemaConfig as a workaround

---

lib/embulk/data/new/README.md.erb

embulk install -> gembulk gem install

Update README.md template. Fix typo

---

embulk-docs/src/built-in.rst
embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java
embulk-standards/src/main/java/org/embulk/standards/CsvTokenizer.java
embulk-standards/src/test/java/org/embulk/standards/TestCsvTokenizer.java
lib/embulk/guess/csv.rb

Add comment_line_marker to CsvParserPlugin

---

lib/embulk/data_source.rb

config object includes IndifferentAccess

---

lib/embulk/guess/csv.rb

Guessed type becomes "string" if null_string is not an empty string.
This pull-request fixes this problem.

guess-csv: fixed type guessing when null_string is not empty

---

embulk-standards/src/main/java/org/embulk/standards/CsvTokenizer.java
lib/embulk/guess/csv.rb

guess-csv: guess trim_if_not_quoted

---

Gemfile.lock
embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java
embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnNotFoundException.java
embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnSetter.java
embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnSetterFactory.java
embulk-core/src/main/java/org/embulk/spi/util/DynamicPageBuilder.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/AbstractDynamicColumnSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/BooleanColumnSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/DefaultValueSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/DoubleColumnSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/LongColumnSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/NullDefaultValueSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/SkipColumnSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/StringColumnSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/TimestampColumnSetter.java
lib/embulk/java/imports.rb
lib/embulk/page_builder.rb

This utility class makes it easy to develop a filter plugin.

add DynamicPageBuilder utility

---

lib/embulk/command/embulk.rb
lib/embulk/command/embulk_run.rb

rather than show "no such file to load -- bundler"

install bundler if it is not available

---

lib/embulk/plugin_registry.rb

Fixes this issue: https://gist.github.com/tasuku-s/bf37b1c1c8d16c663655
This shows "Loaded plugin embulk-input-oracle (0.5.0)" twice but it should be once.

fix PluginRegistry#require_and_show not to show gems twice

---

embulk-core/src/main/java/org/embulk/spi/PageBuilder.java
embulk-core/src/main/java/org/embulk/spi/util/DynamicPageBuilder.java

PageBuilder sets null if addXxx is not called to the column

---

embulk-core/src/main/java/org/embulk/EmbulkService.java
embulk-core/src/main/java/org/embulk/command/Runner.java

add EmbulkService.overrideModules so that apps can use Modules.override [#239]

---

embulk-core/src/main/java/org/embulk/spi/unit/ToString.java
embulk-core/src/main/java/org/embulk/spi/unit/ToStringMap.java

Add spi.unit.ToStringMap for a Task field which accepts fuzzy string-to-string map

---

embulk-core/src/main/java/org/embulk/exec/PooledBufferAllocator.java

Fix https://github.com/embulk/embulk/issues/246
I verified this patch worked well with embulk-output-vertica. 
Please let me know if there is a way to write a test.

Add an option to change page buffer size with -J-Dembulk.pageSize=N

---

embulk-core/src/main/java/org/embulk/config/DataSource.java
embulk-core/src/main/java/org/embulk/config/DataSourceImpl.java

That's useful for accessing ConfigSource object.

Add a has method to config.DataSource

---

embulk-core/src/main/java/org/embulk/config/DataSourceImpl.java

see:
http://fasterxml.github.io/jackson-databind/javadoc/2.5/com/fasterxml/jackson/databind/node/ObjectNode.html#put(java.lang.String,%20com.fasterxml.jackson.databind.JsonNode)

Suppress deprecation warnings for JsonNode put method

---

.gitignore
build.gradle
test/helper.rb

I tried to measure embulk's ruby code test coverage with simplecov.
I'm not sure whether always measuring coverage or not is better.

Measure ruby code test coverage with simplecov

---

lib/embulk/data_source.rb
lib/embulk/error.rb

Config error extends config exception

---

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java
embulk-core/src/main/java/org/embulk/EmbulkService.java
embulk-core/src/main/java/org/embulk/command/Runner.java
embulk-core/src/main/java/org/embulk/exec/ExecModule.java
embulk-core/src/main/java/org/embulk/exec/PooledBufferAllocator.java
embulk-core/src/main/java/org/embulk/guice/Bootstrap.java
embulk-core/src/main/java/org/embulk/guice/CloseableInjector.java
embulk-core/src/main/java/org/embulk/guice/CloseableInjectorProxy.java
embulk-core/src/main/java/org/embulk/guice/InjectorProxy.java
embulk-core/src/main/java/org/embulk/guice/LifeCycleManager.java
embulk-core/src/main/java/org/embulk/guice/LifeCycleMethods.java
embulk-core/src/main/java/org/embulk/guice/LifeCycleMethodsMap.java
embulk-core/src/main/java/org/embulk/guice/LifeCycleModule.java

EmbulkEmbed is a new interface to embed Embulk in an application. This
class will replace EmbulkService once the API is designed.

Add EmbulkEmbed with JSR 250 Lifecycle support

---

build.gradle

Upgrade jruby verison to 9k

---

lib/embulk/command/embulk_run.rb
lib/embulk/command/embulk_selfupdate.rb

Fix native library installation on jruby 9k

---

lib/embulk/data/new/gitignore.erb

Hello.
I use eclipse.
ignore eclipse setting files.
thanks.

Add files to .gitignore for eclipse.

---

lib/embulk/guess/csv.rb

This change enhances CSV guess plugin so that it may detect header line
even if all values are string. This guess succeeds if values in a CSV
file are (almost) fixed-length and its column name at the first line is
longer or shorter enough compared to length of values. Fixes #284.

CSV guess plugin uses variance of column lengths to detect heder line

---

embulk-docs/src/recipe/scheduled-csv-load-to-elasticsearch-kibana4.rst

Add default timezone note on tutorial.
someone confused. 
http://qiita.com/gingi99/items/8ed18cc0dae48e8796bc
Please fix English.

Add default timezone note on tutorial

---

embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java
embulk-standards/src/main/java/org/embulk/standards/CsvTokenizer.java

CsvTokenizer needs to track skipped header lines to calculate lineNumber

---

embulk-docs/src/index.rst

http://www.embulk.org/docs/
No encoder and decoder categories.

Add encoder and decoder categories

---

lib/embulk/command/embulk_selfupdate.rb

Fix selfupdate wrong version number [Fix #316]

---

lib/embulk/runner.rb

Liquid supports `include` tag to include another file. This is useful
to organize complex configuration file.
This implementation uses the directory of input configuration file to
load another file. For example, if 'mydir/config.yml.liquid' includes
following data:
```yaml
{% include 'commons/mysql' %}
out:
type: stdout
```
It includes `mydir/commons/_mysql.yml.liquid` file. Because of Liquid's
security limitation, file path can't include `.` (including `..`).

Enable 'include' tag in liquid template

---

embulk-core/src/main/java/org/embulk/exec/GuessExecutor.java
embulk-core/src/main/java/org/embulk/exec/SamplingParserPlugin.java

GuessExecutor.GuessParserPlugin.run reads sample data and using it
repeatedly. When it reads data from a decoder plugin, it needs to more
than one buffer because decoder plugin splits a buffer passed by
SamplingParserPlugin into multiple buffers.
Fixes #339.

GuessExecutor should read more than one buffer

---

lib/embulk/command/embulk_run.rb

`--help` shows -J and -R options.

embulk --help shows VM options

---

embulk-core/src/main/java/org/embulk/spi/ExecSession.java

This is useful when an application embedding Embulk wants to hook log
messages of the session.

Add ExecSession.setLoggerFactory

---

embulk-core/src/main/java/org/embulk/command/PreviewPrinter.java

fix preview of json column to use Value#toString

---

embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java

Alternative implementation of #357.

JRubyScriptingModule takes gem_home system parameter

---

embulk-core/src/main/java/org/embulk/exec/LocalExecutorPlugin.java

ScatterTransactionalPageOutput.add() should have higher priority than
completeWorkers call. Otherwise, if add() is waiting but completeWorkers
runs first, the waiting page is lost.
Volatile keyword was also missing.
Fixes #381

Fixes race condition at ScatterTransactionalPageOutput

---

lib/embulk/plugin_registry.rb

Serializes access to Gem.loaded_specs to mitigate probability of
possible deadlock.

Workaround for deadlock issue in require method of rubygems

---

embulk-core/src/main/java/org/embulk/spi/json/JsonParser.java

Usage at a parser plugin:
```java
FileInputInputStream in = new FileInputInputStream(fileInput);
while (in.nextFile()) {
try {
JsonParser.Stream stream = new JsonParser().open(in);
Value value;
while ((value = stream.next()) != null) {
...
}
}
catch (IOException ex) {
throw Throwables.propagate(ex);
}
}
```

Add JsonParser.Stream for streaming deserialization of JSON

---

lib/embulk/runner.rb

accept .yaml as well as .yml as a config file name

---

embulk-docs/src/recipe/scheduled-csv-load-to-elasticsearch-kibana4.rst

Update tutorial. use ``-c`` option instead of ``-o``
Before: ``embulk run next-config.yml -o /path/to/next-config.yml``
After: ``embulk run config.yml -c diff.yml``
And Update ES 2.2

Update recipe. Use -c option instead of -o. And update ES 2.2

---

embulk-docs/src/built-in.rst
embulk-standards/build.gradle
embulk-standards/src/main/java/org/embulk/standards/Bzip2FileDecoderPlugin.java
embulk-standards/src/main/java/org/embulk/standards/Bzip2FileEncoderPlugin.java
embulk-standards/src/main/java/org/embulk/standards/StandardPluginModule.java
lib/embulk/guess/bzip2.rb

as a built-in plugin.
guess is also available.

Add bzip2 encoder and decoder plugin

---

embulk-core/src/test/java/org/embulk/spi/MockParserPlugin.java
embulk-core/src/test/java/org/embulk/spi/TestFileInputRunner.java
embulk-core/src/test/java/org/embulk/spi/TestFileOutputRunner.java
embulk-core/src/test/java/org/embulk/spi/TestPageBuilderReader.java

I added unit tests for PageReader and PageBuilder

Add unit tests for PageReader/PageBulder

---

build.gradle

Release note:
http://jruby.org/2016/01/26/jruby-9-0-5-0.html

update jruby to 9.0.5.0

---

embulk-core/src/main/java/org/embulk/spi/util/LineDecoder.java

UTF-8 encoding allows to have BOM (0xEF 0xBB 0xBF) at the header although it does nothing at all.
BufferedReader returns 0xFE 0xFF when it detects a BOM at the head of UTF-8 file.

LineDecoder skips UTF-8 BOM if necessary

---

embulk-core/build.gradle

Release notes:
https://github.com/msgpack/msgpack-java/blob/develop/RELEASE_NOTES.md

Update msgpack from 0.8.6 to 0.8.7

---

embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java
embulk-standards/src/main/java/org/embulk/standards/CsvTokenizer.java
embulk-standards/src/test/java/org/embulk/standards/TestCsvTokenizer.java

Fix https://github.com/embulk/embulk/issues/433

CSV Parser: Do not always convert empty string into null (revisit)

---

embulk-core/build.gradle

Let's upgrade latest version to avoid https://github.com/msgpack/msgpack-java/pull/375

Upgrade msgpack-core v0.8.8

---

lib/embulk/command/embulk_run.rb

This commit updated Gem.ruby implementation:
https://github.com/jruby/jruby/commit/fa4846f2c12fef66b31f0973cc58c66fb30cb4fa
Old implementation returned `java -jar JAR_PATH` which doesn't work if
Main-Class is overriden. New implementation returns
`java -cp CLASS_PATH org.jruby.Main` which always works well.
Fixes [#450]

Gem.ruby doesn't need hack any more

---

embulk-docs/src/customization.rst

http://www.embulk.org/docs/customization.html
⏬

Fix typo in customization.html

---

lib/embulk/command/embulk_run.rb

Gem::StubSpecification is an internal API that seems chainging often.
Gem::Specification.add_spec is deprecated also. Therefore, here makes
-L <path> option alias of -I <path>/lib by assuming that *.gemspec file
always has require_paths = ["lib"].
Fixes #457.

Fix -L option that is failing since JRuby 9.1.2.0

---

embulk-standards/src/main/java/org/embulk/standards/RenameFilterPlugin.java
embulk-standards/src/test/java/org/embulk/standards/TestRenameFilterPlugin.java

Add the "rules" element in RenameFilterPlugin with initial renaming operators "lower_case_to_upper" and "upper_case_to_lower".

Add the "rules" element in RenameFilterPlugin

---

embulk-standards/src/main/java/org/embulk/standards/RenameFilterPlugin.java
embulk-standards/src/test/java/org/embulk/standards/TestRenameFilterPlugin.java

@muga @frsyuki Can you PTAL at this?

Add initial renaming rules

---

embulk-docs/src/built-in.rst

Not urgent. Can you have a look? @muga

Reractor underlines in built-in.rst to eliminate warnings.

---

embulk-standards/src/test/java/org/embulk/standards/TestRenameFilterPlugin.java

@muga Finally, fixing the tests. ;)

Fix (re-enable) test cases that expect validation errors by java.validation.constraints.*.

---

embulk-standards/src/main/java/org/embulk/standards/RenameFilterPlugin.java
embulk-standards/src/test/java/org/embulk/standards/TestRenameFilterPlugin.java

@muga Can you take a look?
It's just adding comments to note: do not change the existing behavior.

Add comments in |RenameFilterPlugin| about behavior changes.

---

README.md

Change words on https://github.com/embulk/embulk/pull/475

Fix quick start

---

embulk-core/src/main/java/org/embulk/spi/util/ResumableInputStream.java

ResumableInputStream.in can be null if reopen() method call temporarily
fails and call of ResumableInputStream still calls read methods.

ResumableInputStream may throw NPE

---

lib/embulk/java/time_helper.rb

I refined several commits on #468. @hiroyuki-sato could you check if this fix works for you or now?

Support timestamp format "%Q" v2

---

embulk-docs/src/built-in.rst

Add document for remove_columns filter plugin

---

embulk-core/build.gradle

https://github.com/msgpack/msgpack-ruby/blob/master/ChangeLog

Update msgpack-ruby v1.1.0

---

embulk-docs/src/developers/index.rst
embulk-docs/src/index.rst

@muga Adding resources for developers, with "Embulk v2" resources.

Add resources for developers with some design docs on "Embulk v2"

---

embulk-docs/src/developers/index.rst

@muga The listing in Resources for Developers are broken... Trying to fix the listing.
http://www.embulk.org/docs/developers/index.html

Fix listing in Resources for Developers.

---

embulk-docs/src/developers/index.rst

Fix indent
http://www.embulk.org/docs/developers/index.html#design-docs-for-core-developers
Current results.
```
Summary * Un-JRuby in the boot process * [TBD] Update plugin loading: non-Gem plugins, namespaces, and versions * [TBD] Un-JRuby in the plugin load process * [TBD] Provide better OAuth support in plugins * [TBD] Buffer in output plugins * [TBD] Structure documents: configs and errors * [TBD] Deliver errors and notifications more flexibly
```

[Doc] Add newline for item lists.

---

embulk-docs/src/recipe.rst
embulk-docs/src/recipe/scheduled-csv-load-to-elasticsearch-kibana5.rst

I tested on the macOS. 
Maybe It will work well on the Ubuntu. 
@sakama Please take a look.

Update recipe. Use elasticsearch and kibana5

---

build.gradle
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.19.rst
lib/embulk/version.rb

This PR prepares Embulk 0.8.19 release.

Release v0.8.19

---

build.gradle
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.20.rst
lib/embulk/version.rb

This PR prepares Embulk 0.8.20 release.

Release v0.8.20

---

embulk.gemspec

The latest version(0.8.19) `mkbundle` generate following output.
It install `msgpack(0.7.6)` and `liquid(3.0.6)`
These gems in core updated to newer versions with the following PR.
It needs to update to the same version in gemspec too.
* msgpack to 1.1.0 [#553]
* liquid to 4.0.0 [#587]
I can't check this change correctly on the local environment. 
Maybe `mkbundle` refer gemspec in the rubygems. 
```
embulk mkbundle mkbundle_0_8_19
2017-05-14 00:53:25.387 +0900: Embulk v0.8.19
Initializing mkbundle_0_8_19...
Creating mkbundle_0_8_19/Gemfile
Creating mkbundle_0_8_19/.ruby-version
Creating mkbundle_0_8_19/.bundle/config
Creating mkbundle_0_8_19/embulk/input/example.rb
Creating mkbundle_0_8_19/embulk/output/example.rb
Creating mkbundle_0_8_19/embulk/filter/example.rb
Fetching gem metadata …
```

Update msgpack in gemspec.

---

build.gradle
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.21.rst
lib/embulk/version.rb

This PR prepares Embulk 0.8.21 release.

Release v0.8.21

---

build.gradle
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.22.rst
lib/embulk/version.rb

This PR prepares 0.8.22 release.

Release v0.8.22

---

build.gradle
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.23.rst
lib/embulk/version.rb

@sakama Can you have a look?  (Cc: @muga)
Plan: #662

Release v0.8.23

---

bin/embulk
embulk-cli/src/main/bat/selfrun.bat
embulk-cli/src/main/sh/selfrun.sh
lib/embulk/command/embulk_bundle.rb

@muga WIP yet, but let me share. (.bat needs to be fixed.)

Make environment variables immutable in JRuby/Java.

---

embulk-cli/src/main/bat/selfrun.bat

Fixing: https://github.com/embulk/embulk/issues/665#issuecomment-306423707
Can you have a look? @muga

Fix selfrun.bat so that selfrun.sh works correctly without error messages.

---

build.gradle
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.24.rst
lib/embulk/version.rb

https://github.com/embulk/embulk/issues/665

Release v0.8.24

---

embulk-core/src/main/java/org/embulk/exec/BulkLoader.java
embulk-core/src/main/java/org/embulk/plugin/DefaultPluginType.java
embulk-core/src/main/java/org/embulk/plugin/PluginType.java
embulk-core/src/test/java/org/embulk/plugin/TestPluginType.java
embulk-core/src/test/java/org/embulk/plugin/TestPluginTypeSerDe.java
embulk-standards/src/main/java/org/embulk/standards/StandardPluginModule.java

@muga It's WIP yet (no tests!), but can I have your impressions on this change?

Support complex (mapping-style) PluginType.

---

lib/embulk/command/embulk_bundle.rb

Fixes #680. Can you have a look? @muga

Fix "NameError: undefined local variable or method `bundle_path_index' for main:Object" when using Bundler.

---

build.gradle
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.25.rst
lib/embulk/version.rb

Release v0.8.25

---

embulk-core/src/main/java/org/embulk/plugin/jar/InvalidJarPluginException.java
embulk-core/src/main/java/org/embulk/plugin/jar/JarPluginLoader.java
embulk-core/src/test/java/org/embulk/EmbulkTestRuntime.java
embulk-core/src/test/java/org/embulk/plugin/jar/ExampleJarSpiV0.java
embulk-core/src/test/java/org/embulk/plugin/jar/JarBuilder.java
embulk-core/src/test/java/org/embulk/plugin/jar/TestJarPluginLoader.java

@muga Next to #686, implementing a class that actually loads a JAR-based plugin class. #684 will be after this PR.
Order: #686 ==> This (#687) ==> #684

Add JarPluginLoader to load a JAR-based plugin class.

---

embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java

@muga Before tweaking `PluginClassLoader` and the "parent-first" things, commenting some description on them. Can you have a look?

Describe "parent-first" in PluginClassLoader.

---

embulk-core/src/main/java/org/embulk/plugin/InjectedPluginSource.java

@muga Just refactoring. It is unnecessarily `public`. PTAL?

Refactor: make InjectedPluginSource.PluginFactory private.

---

embulk-core/src/main/java/org/embulk/EmbulkService.java
embulk-core/src/main/java/org/embulk/plugin/PluginSourceNotMatchException.java
embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginSource.java
embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginSourceModule.java

@muga While it's yet WIP, can you have a quick look at the current implementation?
* `MavenPluginSource`: Not yet done. Almost just a copy from #592.
* `MavenArtifactFinder`: New, almost done and tested. It looks for local Maven artifact in the local file system.
* `TestMavenArtifactFinder`: Tests for `MavenArtifactFinder`. It looks for a dummy Maven artifact in a dummy Maven repository at `embulk-core/src/test/resources/m2.test`.

Add MavenPluginSource to load JAR-based plugins into Embulk.

---

embulk-core/src/main/java/org/embulk/plugin/MavenPluginType.java
embulk-core/src/main/java/org/embulk/plugin/PluginType.java
embulk-core/src/main/java/org/embulk/plugin/maven/MavenArtifactFinder.java
embulk-core/src/main/java/org/embulk/plugin/maven/MavenArtifactNotFoundException.java
embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginSource.java
embulk-core/src/test/java/org/embulk/plugin/TestPluginType.java
embulk-core/src/test/java/org/embulk/plugin/TestPluginTypeSerDe.java
embulk-core/src/test/java/org/embulk/plugin/maven/TestMavenArtifactFinder.java

@muga As chatted directly, we're supporting "classifier" in Maven configurations.

Support "classifier" in Maven-based plugin configurations.

---

embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java

@dmikurube Please take a look when you can.

Fix typo: modifieid -> modified.

---

build.gradle

To improve embulk-standards tests stability, this PR changes configuration of Gradle test processes with forkEvery=1. It recreates Gradle test processes every test class execution and expect reduction of the heap memory consumption. As the result, it might make the test faster.
https://docs.gradle.org/3.2.1/dsl/org.gradle.api.tasks.testing.Test.html
---
forkEvery=1
```
$ ./gradlew :embulk-standards:test
Publication bintrayMavenRelease not found in project :.
Publication bintrayMavenRelease not found in project :embulk-cli.
Publication bintrayMavenRelease not found in project :embulk-docs.
:embulk-jruby-strptime:compileJava UP-TO-DATE
:embulk-jruby-strptime:processResources UP-TO-DATE
:embulk-jruby-strptime:classes UP-TO-DATE
:embulk-jruby-strptime:jar UP-TO-DATE
:embulk-core:compileJava …
```

Set forkEvery=1 for stability improvement of embulk-standards tests

---

embulk-docs/src/release/release-0.8.27.rst

This PR adds #714 to v0.8.27 release note.

Release v0.8.27 v2, Add #714

---

embulk-docs/src/release/release-0.8.27.rst

This PR adds #719 to v0.8.27 release note.

Release v0.8.27 v3, Add #719

---

embulk-cli/src/main/java/org/embulk/cli/EmbulkBundle.java
embulk-cli/src/main/java/org/embulk/cli/EmbulkGlobalJRubyScriptingContainer.java

@muga Just refactoring out (extracting) the creator of `ScriptingContainer`. Can you have a look?

Refactor setting the global JRuby ScriptingContainer up.

---

embulk-cli/src/main/java/org/embulk/cli/EmbulkRun.java
embulk-core/src/main/java/org/embulk/EmbulkSetup.java
lib/embulk.rb

@muga Next, `Embulk::setup` replaced into Java. Can you have a look?

Replace Embulk::setup in Ruby into org.embulk.EmbulkSetup.setup in Java.

---

embulk-docs/src/release/release-0.8.28.rst

@muga The date in the doc was a bit old...
I'm merging this PR soon before approval. Please have a look later.

Fix the actual release date of v0.8.28.

---

embulk-cli/src/main/java/org/embulk/cli/EmbulkRun.java

Fix the broken "bundle" subcommand rewritten in Java.

---

embulk-cli/src/main/java/org/embulk/cli/EmbulkGlobalJRubyScriptingContainer.java

Fix how to get the CodeSource location on Windows.

---

build.gradle
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.29.rst
lib/embulk/version.rb

@muga To be releasing v0.8.29. Merging this soon -- ping me (later) if you have any concerns.

Release v0.8.29

---

embulk-core/src/main/java/org/embulk/EmbulkSetup.java
lib/embulk/runner.rb

Refactoring: Ruby EmbulkRunner to receive Java org.embulk.EmbulkRunner directly.

---

embulk-core/src/main/java/org/embulk/spi/util/PagePrinter.java

Avoid calling the deprecated constructor in org.embulk.spi.util.PagePrinter: Fix #760

---

embulk-core/src/main/java/org/embulk/spi/ExecSession.java
embulk-core/src/main/java/org/embulk/spi/time/TimestampFormat.java

Stop using old |TimestampFormatter.FormatterTask|

---

build.gradle
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.30.rst
lib/embulk/version.rb

Thought to release the next version before merging other big changes. Can I have your thoughts? @muga

Release v0.8.30

---

embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatter.java
embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java

@muga Can you have a look? This is trying to relax: #768
Cc: @hiroyuki-sato @hito4t

Relax deprecation messages of TimestampFormatter/Parser constructors: #768

---

build.gradle
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.31.rst
lib/embulk/version.rb

Release v0.8.31

---

build.gradle
embulk-core/build.gradle

See also: https://github.com/jruby-gradle/jruby-gradle-plugin/issues/297
Cc: @hiroyuki-sato

Workaround against the rubygems.lasagna.io problem.

---

embulk-core/src/test/java/org/embulk/spi/json/TestJsonParser.java

Test org.embulk.spi.json.JsonParser with TestJsonParser

---

embulk-core/src/main/java/org/embulk/spi/Page.java

(It summarizes Japanese tweets from https://twitter.com/frsyuki/status/904996360729931780.)

Add JavaDoc for |org.embulk.spi.Page|

---

embulk-core/src/main/java/org/embulk/spi/Page.java

@muga Adding just some on #784. Can you have a look?

Describe interoperability on org.embulk.spi.Page on JavaDoc

---

embulk-core/src/test/java/org/embulk/spi/json/TestJsonParser.java

@muga Sorry for frequent changes. Just adding some more tests...

Add more tests on org.embulk.spi.json.JsonParser

---

build.gradle
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.32.rst
lib/embulk/version.rb

@muga Releasing v0.8.32... v0.8 has been long-lived. ;)

Release v0.8.32

---

bin/embulk
build.gradle
embulk-cli/src/main/bat/selfrun.bat
embulk-cli/src/main/java/org/embulk/cli/EmbulkCommandLine.java
embulk-cli/src/main/java/org/embulk/cli/EmbulkRun.java
embulk-cli/src/main/sh/selfrun.sh
embulk-cli/src/test/java/org/embulk/cli/SelfrunTest.java
embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java

@muga Can you have a look? We're dropping back the complicated part of the selfrun batch file!
A release plan of mine then is:
* This (#779) + #790 => v0.8.33
* JRuby 9.1.3.0 (#791) => v0.8.34
What do you think of the plan?

Configure environment variables in JRuby again, instead of the selfrun scripts

---

bin/embulk
embulk-cli/src/main/bat/selfrun.bat
embulk-cli/src/main/java/org/embulk/cli/EmbulkRun.java
embulk-cli/src/main/sh/selfrun.sh

@muga Can you have a look? I guess it (indirectly) solves #778...
Will be releasing v0.8.33 after merging this PR.

Add a CLI option "-E" running an external script to configure environment variables

---

build.gradle
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.33.rst
lib/embulk/version.rb

@muga @sakama Can you have a look? Releasing v0.8.33 soon!

Release v0.8.33

---

embulk-core/src/main/java/org/embulk/plugin/PluginClassLoader.java

@muga It was blocking the embulk.org documents form updates. Can you have a look?

Fix typos in Javadoc in PluginClassLoader

---

README.md
embulk-docs/src/index.rst

Describe Embulk-announce mailing list in embulk.org and README.md

---

embulk-cli/src/main/java/org/embulk/cli/EmbulkRun.java

@muga @sakama We have no other channels to notify existing users about the mailing list... :( (It's a chicken-and-egg!)
The notification would be tentative until we believe the mailing list gets well-known to existing users.
What do you think?

Notify Embulk-announce mailing list in CLI

---

embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnSetterFactory.java
embulk-core/src/main/java/org/embulk/spi/util/DynamicPageBuilder.java

Do not use numeric prefixes (like "%6N") in default date/time format specifiers in parsing

---

embulk-cli/src/main/java/org/embulk/cli/EmbulkRun.java

@muga @sakama Updating the message introduced in #816 to have more explicit notion on compatibility-breaking changes. Can you have a look?

Modify notification message on Embulk-announce mailing list

---

embulk-core/src/main/java/org/embulk/spi/ExecSession.java

@muga Removing straightforward. Can you have a look?

Stop creating TimestampFormatter.FormatterTask in ExecSession

---

embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnSetterFactory.java
embulk-core/src/main/java/org/embulk/spi/util/DynamicPageBuilder.java
lib/embulk/input_plugin.rb
lib/embulk/page_builder.rb

@muga Trying to make Ruby plugins more flexible... Not yet sure this is the right design, though.
Can I have your opinions?

Enable setting timestamp formats from Columns' in Ruby plugins

---

build.gradle
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.36.rst
lib/embulk/version.rb

@muga @sakama To be releasing v0.8.36 after the following PRs are merged. Can you have a look?
- https://github.com/embulk/embulk/pull/814
- https://github.com/embulk/embulk/pull/821
- https://github.com/embulk/embulk/pull/822
- https://github.com/embulk/embulk/pull/824

Release v0.8.36

---

embulk-core/src/main/java/org/embulk/spi/time/TimestampFormat.java

@muga @sakama Can you have a look? It fixes #833.

Parse Ruby-style time zone names in addition: Fix #833

---

embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java

@muga @sakama A kind of quick improvement. Just adding more information in Exception.

Add zone name in throwing TimestampParseException

---

build.gradle
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.37.rst
lib/embulk/version.rb

@muga Will be releasing v0.8.37 after #848 is merged. Can you have a look?

Release v0.8.37

---

embulk-core/src/main/java/org/embulk/EmbulkRunner.java

This PR would be merged several versions after #765 is released.

Remove any global JRuby instance from the bootstrap by removing Ruby Embulk::Runner when Embulk is triggered from Java.

---

build.gradle
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.38.rst
lib/embulk/version.rb

Merged #773. It would be released as a new version because I'm afraid it "can" have large impacts although it "shouldn't" have impacts.

Release v0.8.38

---

build.gradle
embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java
lib/embulk/data/new/java/build.gradle.vm

@sakama Can you have a look? (Cc: @muga)

Bump up to Java 8

---

build.gradle
embulk-core/build.gradle
embulk-docs/build.gradle

@muga Can you have a look? It may solve the problem of the "rubygems.lasagna.io" problem in building Embulk. (Thanks to @hiroyuki-sato's finding. :) )

Upgrade jruby-gradle-jar-plugin to 1.5.0.

---

embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java

#819 has unveiled a potential problem of Bundler (#861) to run with JRuby.
Seeing the Issue of Bundler at https://github.com/bundler/bundler/issues/4565, this PR workarounds the issue by disabling `Bundler::SharedHelpers.clean_load_path` with monkey-patching.
@sakama (Cc: @muga) Can you have a look?

Workaround "-b" problem of Bundler by monkey-patching Bundler::SharedHelpers.clean_load_path: Fix #861

---

build.gradle
embulk-core/src/main/java/org/embulk/spi/time/TimestampFormat.java
embulk-core/src/test/java/org/embulk/spi/time/TestTimestampParser.java
embulk-docs/src/release.rst
embulk-docs/src/release/release-0.8.39.rst
lib/embulk/version.rb
test/vanilla/time/test_timestamp_parser.rb

@muga @sakama Can you have a look? Backport of #863 to v0.8 series.

Release v0.8.39

---

embulk-cli/src/main/java/org/embulk/cli/EmbulkRun.java
embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java

We don't want to touch environment variables as far as possible -- they are global and too impactful. This PR cleans up them.

Call Gem.paths= instead of setting environment variables GEM_HOME and GEM_PATH with cleanups

---

.travis.yml
appveyor.yml
build.gradle
embulk-core/build.gradle
embulk-core/src/test/ruby/monkey_strptime/run-test.rb

@muga @sakama After #835, updating `rubyTest`. Can you have a look?

Simplify Ruby tests with Date._strptime monkey-patched

---

embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java

@sakama @muga Can you PTAL?
That `$LOAD_PATH` in the non-Bundler case is not required now.

Stop adding the path to the jar itself in JRuby $LOAD_PATH

---

embulk-core/src/main/java/org/embulk/jruby/ScriptingContainerDelegate.java

Making JRuby version ("9.1.13.0" at this time) and Ruby compatibility version ("2.3.3" then) available through `ScriptingContainerDelegate`. It **will** (not yet) be used for making `.ruby-version` in plugin code generated by `embulk` `bundle`, `migrate`, and `new`.

Make JRuby-related versions via ScriptingContainerDelegate

---

embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java

@sakama @muga `JRubyScriptingModule` has had bunch of unnecessary initialization code, and ineffective comments. This PR cleans up them.
Can you PTAL?

Cleanup JRuby instance initialization in JRubyScriptingModule

---

README.md

Update the description on Java versions in README.md

---

build.gradle
config/checkstyle/README.md
config/checkstyle/checkstyle.xml
config/checkstyle/google_checks.xml
embulk-core/config/checkstyle/suppressions.xml
embulk-standards/config/checkstyle/suppressions.xml
embulk-test/config/checkstyle/suppressions.xml

Nothing has been accepted nor determined yet, but just suggesting to apply checkstyle, and to change the coding style...

Checkstyle the entire project with modified Google's Java Style Guide

---

embulk-standards/config/checkstyle/suppressions.xml
embulk-standards/src/main/java/org/embulk/standards/Bzip2FileDecoderPlugin.java
embulk-standards/src/main/java/org/embulk/standards/Bzip2FileEncoderPlugin.java
embulk-standards/src/main/java/org/embulk/standards/ConfigInputPlugin.java
embulk-standards/src/main/java/org/embulk/standards/CsvFormatterPlugin.java
embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java
embulk-standards/src/main/java/org/embulk/standards/CsvTokenizer.java
embulk-standards/src/main/java/org/embulk/standards/GzipFileDecoderPlugin.java
embulk-standards/src/main/java/org/embulk/standards/GzipFileEncoderPlugin.java
embulk-standards/src/main/java/org/embulk/standards/JsonParserPlugin.java
embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java
embulk-standards/src/main/java/org/embulk/standards/LocalFileOutputPlugin.java
embulk-standards/src/main/java/org/embulk/standards/NullOutputPlugin.java
embulk-standards/src/main/java/org/embulk/standards/RemoveColumnsFilterPlugin.java
embulk-standards/src/main/java/org/embulk/standards/RenameFilterPlugin.java
embulk-standards/src/main/java/org/embulk/standards/StandardPluginExtension.java
embulk-standards/src/main/java/org/embulk/standards/StandardPluginModule.java
embulk-standards/src/main/java/org/embulk/standards/StdoutOutputPlugin.java
embulk-standards/src/test/java/org/embulk/standards/TestCsvFormatterPlugin.java
embulk-standards/src/test/java/org/embulk/standards/TestCsvParserPlugin.java
embulk-standards/src/test/java/org/embulk/standards/TestCsvTokenizer.java
embulk-standards/src/test/java/org/embulk/standards/TestJsonParserPlugin.java
embulk-standards/src/test/java/org/embulk/standards/TestRemoveColumnsFilterPlugin.java
embulk-standards/src/test/java/org/embulk/standards/TestRenameFilterPlugin.java
embulk-standards/src/test/java/org/embulk/standards/guess/TestCsvAllStringsGuessPlugin.java
embulk-standards/src/test/java/org/embulk/standards/guess/TestCsvGuessPlugin.java
embulk-standards/src/test/java/org/embulk/standards/preview/TestFilePreview.java

After #915, enabling checkstyle for embulk-standards.

Enable checkstyle for embulk-standards' Java files

---

embulk-test/config/checkstyle/suppressions.xml
embulk-test/src/main/java/org/embulk/test/EmbulkTests.java
embulk-test/src/main/java/org/embulk/test/PreviewResultInputPlugin.java
embulk-test/src/main/java/org/embulk/test/TestingBulkLoader.java
embulk-test/src/main/java/org/embulk/test/TestingEmbulk.java

At last after #916, enabling checkstyle for embulk-test.

Enable checkstyle for embulk-test' Java files

---

embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java

The `gem`, `bundle`, `exec`, and `irb` subcommands were not working well. We needed to configure `GEM_HOME` environment variable.

Configure GEM_HOME and GEM_PATH for subcommands gem, bundle, exec, and irb

---

embulk-core/src/main/java/org/embulk/plugin/maven/MavenPluginSource.java

Setting by environment variables is often confusing us. We basically should configure by Embulk's own system config prioritized over OS environment variables.
We may want to stop reading the env `M2_REPO`, not only prioritizing the system config.
@muga @sakama What do you think?

Configure M2_REPO from Embulk's system config with moving the default to ~/.embulk/lib/m2/reposotory

---

embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java
embulk-core/src/main/java/org/embulk/cli/EmbulkSelfUpdate.java
embulk-core/src/main/java/org/embulk/exec/BulkLoader.java
embulk-core/src/main/java/org/embulk/exec/LocalExecutorPlugin.java

Restyle (reformat) back some code that `google-code-format` did too much at #914. Can you have a look? @muga @sakama

Restyle back code of EmbulkRun, EmbulkSelfUpdate, BulkLoader, and LocalExecutorPlugin

---

README.md

Updating README.md for a bit updated release process.

Update README.md about version, jrubyVersion, and releasing

---

embulk-docs/src/release.rst
embulk-docs/src/release/release-0.9.0.rst

@muga @sakama We're going to release v0.9.0 next week (planned for Jan 30 (PST)). Can you have a look?

Prepare for v0.9.0

---

docs/design/README.md
docs/design/timestamp_parsing.md

@muga @sakama Drafted a design doc of timestamp parsing in Embulk. Can you have a look?

Add a design doc of Timestamp parsing

---

embulk-core/src/main/java/org/embulk/config/TaskInvocationHandler.java
embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatter.java
embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java
embulk-core/src/main/java/org/embulk/spi/util/DynamicPageBuilder.java

By #951, the indirection is no longer required. It's like reverting #889.

Remove @Config indirection by default implemantations

---

embulk-docs/src/release/release-0.9.1.rst

Prepare for v0.9.1

---

embulk-docs/src/release.rst

Index release-0.9.1.rst

---

build.gradle

Bump to v0.9.3-SNAPSHOT

---

embulk-core/src/main/java/org/embulk/EmbulkRunner.java
embulk-core/src/main/java/org/embulk/cli/EmbulkMigrate.java
embulk-core/src/main/java/org/embulk/cli/EmbulkNew.java
embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java
embulk-core/src/main/java/org/embulk/jruby/JRubyInitializer.java
embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java
embulk-core/src/main/java/org/embulk/jruby/LazyScriptingContainerDelegate.java
embulk-core/src/main/java/org/embulk/jruby/ScriptingContainerDelegate.java
embulk-core/src/main/java/org/embulk/jruby/ScriptingContainerDelegateImpl.java

@sakama @muga Trying to initialize JRuby lazily. Can you have a look?

Initialize JRuby's ScriptingContainer lazily

---

build.gradle

Bump to v0.9.4-SNAPSHOT

---

embulk-core/src/main/ruby/embulk/schema.rb
embulk-core/src/test/ruby/vanilla/test_schema.rb

@muga @sakama Can you have a look? It is trying to fix #970.

Use Time objects in Ruby: Fix #970

---

embulk-core/src/test/java/org/embulk/config/TestConfigSource.java
embulk-core/src/test/java/org/embulk/spi/time/TestTimestampParser.java

Just SuppressWarnings. Can you have a look?

Suppress deprecation warnings in tests

---

embulk-docs/src/release.rst
embulk-docs/src/release/release-0.9.4.rst

Not concluded yet, but we may release v0.9.4 with the fix of #971 if we agree. What do you think? @sakama @muga

Prepare for v0.9.4

---

embulk-core/src/main/java/org/embulk/jruby/JRubyInvalidRuntimeException.java
embulk-core/src/main/java/org/embulk/jruby/JRubyInvokeFailedException.java
embulk-core/src/main/java/org/embulk/jruby/JRubyNotLoadedException.java
embulk-core/src/main/java/org/embulk/jruby/JRubyPluginSource.java
embulk-core/src/main/java/org/embulk/jruby/JRubyRuntimeException.java
embulk-core/src/main/java/org/embulk/jruby/LazyScriptingContainerDelegate.java
embulk-core/src/main/java/org/embulk/jruby/ScriptingContainerDelegateImpl.java

It is not fixing #978, but making it a bit more clear.

Throw more explicit Exceptions from JRuby ScriptingContainerDelegate

---

embulk-core/src/main/java/org/embulk/jruby/JRubyInitializer.java
embulk-core/src/test/java/org/embulk/jruby/TestJRubyInitializer.java

Fixing #987. Can you have a look? @sakama

Fix the CLI option "-I" was inverted with "-C": Fix #987

---

embulk-docs/src/release.rst
embulk-docs/src/release/release-0.9.5.rst

Will be releasing v0.9.5. Can you have a look? @sakama

Prepare for v0.9.5

---

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java
embulk-core/src/main/java/org/embulk/config/ModelManager.java
embulk-core/src/main/java/org/embulk/exec/BulkLoader.java
embulk-core/src/main/java/org/embulk/exec/GuessExecutor.java
embulk-core/src/main/java/org/embulk/exec/LocalExecutorPlugin.java
embulk-core/src/main/java/org/embulk/exec/PreviewExecutor.java
embulk-core/src/main/java/org/embulk/plugin/compat/InputPluginWrapper.java
embulk-core/src/main/java/org/embulk/plugin/compat/TransactionalFileInputWrapper.java
embulk-core/src/main/java/org/embulk/plugin/compat/TransactionalFileOutputWrapper.java
embulk-core/src/main/java/org/embulk/plugin/compat/TransactionalPageOutputWrapper.java
embulk-core/src/main/java/org/embulk/spi/CloseResource.java
embulk-test/src/main/java/org/embulk/test/EmbulkTests.java
embulk-test/src/main/java/org/embulk/test/TestingEmbulk.java

See https://github.com/google/guava/wiki/Why-we-deprecated-Throwables.propagate
Can you have a look? @sakama (Cc: @muga)

Eliminate using Guava's Throwables#propagate

---

docs/design/README.md
docs/design/undocumented.md

Can you have a look? @sakama 
See related conversation at Twitter (in Japanese): https://twitter.com/dmikurube/status/984345295264690176

Add docs/design/undocumented.md with describing prints_column_names in "stdout"

---

.github/CONTRIBUTING.md

Fix markdown format in CONTRIBUTING.md

---

embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java
embulk-standards/src/test/java/org/embulk/standards/TestLocalFileInputPlugin.java

It refactors `LocalFileInputPlugin` after #1040. It's just refactoring, and it shouldn't change any behavior.
@kamatama41 @sakama Can you have a look?

Refactor LocalFileInputPlugin and its test

---

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java

`EmbulkEmbed.Bootstrap#overrideModules` turned out not to be "overriding" standard modules correctly. There must be something wrong in `EmbulkEmbed.Bootstrap#overrideModules`, or guice-bootstrap (even before #1038).
For example, when I tried to override a binding to `ILoggerFactory` over the standard `org.embulk.exec.LoggerProvider` (with Logback) by `EmbulkEmbed.Bootstrap#overrideModules`, `org.embulk.exec.LoggerProvider` was still loaded, and it caused a logging driver conflict in our local environment.
In addition, I couldn't find any `@PostConstruct` and `@PreDestroy` usage with Embulk. Guice-bootstrap may not be required if those annotations are actually not used.
Then, I'm introducing a new `SimpleBootstrap` for trial without guice-bootstrap that overrides correctly. Note that …

Build EmbulkEmbed without Life Cycle Management (guice-bootstrap)

---

embulk-docs/src/release.rst
embulk-docs/src/release/release-0.9.9.rst

To be releasing v0.9.9 soon... Can you have a look? @sakama @kamatama41

Prepare for v0.9.9

---

build.gradle

Bump to v0.9.10-SNAPSHOT

---

embulk-docs/src/release.rst
embulk-docs/src/release/release-0.9.10.rst

After #1068 is merged, we'll be releasing v0.9.10. Can you have a look, @sakama @kamatama41 ?

Prepare for v0.9.10

---

build.gradle

@kamatama41 @sakama v0.9.10 has been released. Next is v0.9.11.

Bump up to v0.9.11

---

build.gradle

Bumping up to v0.9.12-SNAPSHOT.

Bump up to v0.9.12

---

embulk-docs/src/release.rst
embulk-docs/src/release/release-0.9.12.rst

Releasing v0.9.12. Can you have a look, @sakama @kamatama41?

Prepare for v0.9.12

---

build.gradle

Forgot to bump up... @sakama @kamatama41

Bump up to v0.9.13

---

README.md
build.gradle

Along with that, it updates README.md about the release operation.
@sakama @kamatama41 Can you have a look when you have time?

Bump up to v0.9.15-SNAPSHOT

---

embulk-standards/src/main/java/org/embulk/standards/JsonParserPlugin.java
embulk-standards/src/test/java/org/embulk/standards/TestJsonParserPlugin.java

For #1102 and a follow-up of #1101 
Sample JSON
```json
{"id": 1, "name": "Alice", "tags": ["a", "b", "c"]}
```
Config YAML
```yaml
in:
type: ...
parser:
type: json
__experimental__columns:
- {name: name, type: string}   
- {name: first_tag, type: string, json_pointer: "/tags/0"}   
```
Result 
```
+---------+-------------+------------------+
| id:long | name:string | first_tag:string |
+---------+-------------+------------------+
|       1 |       Alice |                a |
+---------+-------------+------------------+
```

[Experimental] Add an option to select any value in JSON record by JSON Pointer expression.

---

embulk-standards/src/main/java/org/embulk/standards/JsonParserPlugin.java
embulk-standards/src/test/java/org/embulk/standards/TestJsonParserPlugin.java

For #1102 and a follow-up of #1103 
Sample JSON
```json
[
{"id": 1, "name": "Alice"},
{"id": 2, "name": "Bob"},
]
```
Config YAML
```yaml
in:
type: ...
parser:
type: json
__experimental__flatten_json_array: true
```
Result 
```
+-------------------------+
|             record:json |
+-------------------------+
| {"id":1,"name":"Alice"} |
|   {"id":2,"name":"Bob"} |
+-------------------------+
```

[Experimental] Add an option to flatten JSON array to each Embulk record for JSON Parser plugin

---

build.gradle

v0.9.15 is out. Next v0.9.16... @sakama @kamatama41

Bump up to v0.9.16

---

embulk-docs/src/release.rst

Leave a link to GitHub Releases from https://www.embulk.org/docs/release.html

---

embulk-docs/src/built-in.rst

For #1102 
As we fixed option names in #1120, it's time to add them into the official doc.

Add descriptions for new options for JSON parser plugin.

---

build.gradle

Bump up to v0.9.17-SNAPSHOT

---

docs/design/deprecations.md

Just an internal document update. @sakama Can you have a look when you have time?

Document planned deprecations

---

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java
embulk-core/src/main/java/org/embulk/exec/BulkLoader.java
embulk-core/src/main/java/org/embulk/exec/PreviewExecutor.java
embulk-core/src/main/java/org/embulk/exec/SamplingParserPlugin.java
embulk-core/src/main/java/org/embulk/plugin/PluginClassLoaderModule.java
embulk-core/src/test/java/org/embulk/EmbulkTestRuntime.java
embulk-test/src/main/java/org/embulk/test/TestingBulkLoader.java

Another cleanup. Removing unnecessary use of system configs. @sakama Can you have a look when you have time? (No hurry.)

Remove unnecessary uses of SystemConfig

---

embulk-core/src/main/java/org/embulk/exec/ExecModule.java
embulk-core/src/main/java/org/embulk/exec/SimpleTempFileSpaceAllocator.java
embulk-core/src/main/java/org/embulk/exec/TempFileAllocator.java
embulk-core/src/main/java/org/embulk/spi/ExecSession.java
embulk-core/src/main/java/org/embulk/spi/TempFileSpace.java
embulk-core/src/main/java/org/embulk/spi/TempFileSpaceAllocator.java

One of cleanups. @sakama Can you have a look when you have time?

Cleanup TempFile-related classes

---

embulk-core/src/main/java/org/embulk/EmbulkEmbed.java
embulk-core/src/main/java/org/embulk/exec/PreviewExecutor.java
embulk-core/src/main/java/org/embulk/plugin/PluginManager.java

Simply removing unnecessary injections. Can you have a look, @sakama ?

Remove unnecessary injections

---

embulk-core/src/main/java/org/embulk/exec/TempFileAllocator.java

After #1157, another unnecessary injection found.
@sakama Can you have a look when you get time?

Remove unnecessary injection in TempFileAllocator

---

embulk-core/src/test/java/org/embulk/cli/TestSelfUpdate.java

Adding a long-forgotten test... Can you have a look, @sakama ?

Add TestSelfUpdate

---

embulk-core/src/main/java/org/embulk/jruby/JRubyInitializer.java
embulk-core/src/main/java/org/embulk/jruby/JRubyScriptingModule.java
embulk-core/src/test/java/org/embulk/jruby/TestJRubyInitializer.java

@trung-huynh Can you have a look?

Add a system config to require 'sigdump' gem

---

embulk-core/src/main/java/org/embulk/deps/SelfContainedJarFile.java

Closing JarInputStream on failure.

Closing JarInputStream on failure. fixes #1184

---

build.gradle

Note that v0.9.22-SNAPSHOT has been forgotten...

Bump up to v0.9.23-SNAPSHOT

---

embulk-core/src/main/java/org/embulk/spi/Exec.java
embulk-core/src/main/java/org/embulk/spi/ExecSession.java
embulk-core/src/main/java/org/embulk/spi/PageBuilder.java
embulk-core/src/main/java/org/embulk/spi/PageReader.java
embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatterJava.java
embulk-core/src/main/java/org/embulk/spi/time/TimestampFormatterRuby.java
embulk-core/src/main/java/org/embulk/spi/time/TimestampParser.java
embulk-core/src/main/java/org/embulk/spi/util/DynamicColumnSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/AbstractDynamicColumnSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/BooleanColumnSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/DoubleColumnSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/JsonColumnSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/LongColumnSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/SkipColumnSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/StringColumnSetter.java
embulk-core/src/main/java/org/embulk/spi/util/dynamic/TimestampColumnSetter.java

Suppress internal deprecation warnings for org.embulk.spi.time.Timestamp

---

embulk-core/src/main/java/org/embulk/spi/ColumnJacksonModule.java

`Column` has been deserialized through `ColumnJacksonModule` since #1290, but I found that `ColumnJacksonModule` is more strict than `@JsonCreator` -- `index` was able to be empty in `@JsonCreator`.
Although we've observed no problems with it, relaxing it back just in case.

Relax the restriction in building Column from JSON without index

---

embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java

Fix the mkbundle subcommand with bundler 2.1.4 (#1348)

---

embulk-core/src/main/ruby/embulk/plugin.rb

Fix uninitialized constant Forwardable::INSTANCE error (#1353)

---

embulk-core/src/main/java/org/embulk/deps/json/DepsJsonParser.java
embulk-core/src/main/java/org/embulk/spi/json/JsonParser.java
embulk-deps/build.gradle
embulk-deps/gradle/dependency-locks/compileClasspath.lockfile
embulk-deps/gradle/dependency-locks/runtimeClasspath.lockfile
embulk-deps/src/main/java/org/embulk/deps/json/DepsJsonParserImpl.java

This is one of the steps to hide Jackson behind embulk-deps.

Use embulk-util-json's JsonParser inside org.embulk.spi.json.JsonParser

---

embulk-guess-csv/src/main/java/org/embulk/guess/csv/SchemaGuess.java
embulk-guess-csv/src/test/java/org/embulk/guess/csv/TestCsvGuessPlugin.java

The same fix with https://github.com/embulk/embulk-util-guess/pull/14

Fix schema guess for so large a long integer value

---

embulk-core/src/main/java/org/embulk/cli/EmbulkSystemPropertiesBuilder.java

This is to "kaizen" the issue #1471.

Log how gem_home, gem_path, and m2_repo are set (Fix #1471)

---

embulk-core/src/main/java/org/embulk/cli/SelfUpdate.java

Deprecate `embulk selfupdate`

---

embulk-core/src/main/bat/selfrun.bat
embulk-core/src/main/sh/selfrun.sh

Deprecate running Embulk by a single 'embulk' command

---

embulk-junit4/src/main/java/org/embulk/EmbulkTestRuntime.java

org.embulk.EmbulkTestRuntime was revised in Embulk v0.10.33 along with the Guice removal.
Pull request: https://github.com/embulk/embulk/pull/1444 Commit: 656504422c93a24581c4f45e01618dd2fadbb027
It turned out that it might not be working well after the revision.
We were not aware of that because EmbulkTestRuntime was an old obsolete test runner. Modern plugins are tested with org.embulk.test.TestingEmbulk, the latest test runner.
This change is giving a try to revive EmbulkTestRuntime. We may backport this to older versions of embulk-junit4.

Revive EmbulkTestRuntime

---

embulk-api/src/main/java/org/embulk/spi/json/JsonString.java
embulk-api/src/test/java/org/embulk/spi/json/TestJsonString.java

Some addition in Javadoc, and add some test cases that are exampled in the EEP Draft: #1538

Add some Javadoc and some tests for JsonString

---

build.gradle

Same as: https://github.com/embulk/embulk-standards/pull/25

Remove grgit from build

---

gradle/dependency-locks/depsEmbedded.lockfile

`depsEmbedded.lockfile` was not properly updated. This pull request updates it.

Update depsEmbedded properly

---

embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java
embulk-core/src/main/java/org/embulk/jruby/LazyScriptingContainerDelegate.java
embulk-core/src/main/java/org/embulk/jruby/ScriptingContainerDelegate.java
embulk-core/src/main/java/org/embulk/jruby/ScriptingContainerDelegateImpl.java

Exit from `gem` with Gem's intended exit code

---

embulk-core/src/main/java/org/embulk/cli/EmbulkRun.java

Same as #1599 for `embulk bundle`.

Exit from `bundle` with Bundler's intended exit code

---

.github/ISSUE_TEMPLATE.md

Add a discussion forum link in the issue template.

---

.github/workflows/check.yml
.github/workflows/main.yml
.github/workflows/publish.yml

Finally, going to release Embulk core packages from GitHub Actions.

Upload the executable JAR file to GitHub Releases from GitHub Actions

---

docs/eeps/eep-0003.md
docs/eeps/eep-0005.md
docs/eeps/eep-0007.md

EEPs so far had some "forward references" for future EEPs, such as:
> ... will be explained in another EEP.
> ... is another effort to be explained in another EEP.
> ... will be explained in another upcoming EEP.
This pull request is to resolve those forward references in past EEPs.

Resolve forward references in EEPs until EEP-10
